SUSE/DeepSea

srv/modules/runners/push.py
PR cause I'd like someone to look at the indentation of the long line split here https://github.com/SUSE/DeepSea/compare/master...jan--f:master#diff-bc35b5fa836936a3136544887240f188R141
I also took the chance and cleand up some trailing whitespaces.
=> push runner: correct the comment string in customization yaml files

deepsea.spec
Because we ship /etc/salt/master.d/modules.conf, salt-master
needs to be restarted after deepsea is installed, or it won't
notice the necessary config changes.
=> spec: restart salt-master on install (bsc#1000620)

deepsea.spec
Previously, deepsea took ownership of a few directories that
are also owned by salt-master.  Given that deepsea actually
requires salt-master in order to operate, I've udated the
Requires: and BuildRequires: appropriately, and removed
the relevant %dir lines to avoid conflicts in future.
=> spec: don't take ownership of salt-master dirs (bsc#1000670)

srv/modules/runners/validate.py
`salt-run --out=json validate.pillars` will now print
the report as JSON object.
Signed-off-by: Sebastian Wagner <sebastian.wagner@it-novum.com>
=> Add support for JSON output to validate.py

deepsea.spec
The nettests need to be added to the rpm.
Signed-off-by: Owen Synge <osynge@suse.com>
=> Add nettests to spec file

srv/salt/ceph/igw/restart/default.sls, srv/salt/ceph/mds/restart/default.sls, srv/salt/ceph/mon/restart/default.sls, srv/salt/ceph/osd/restart/default.sls, srv/salt/ceph/restart/default.sls, srv/salt/ceph/rgw/restart/default.sls
Change the position where we wait for the cluster due to keyring/permissions
Also add failhard to OSDS to avoid ending up with N broken OSDS
(cherry picked from commit 415e9177d897330dd705d69af0bf172b4b58cb49)
=> Change the position where we wait for the cluster due to

Makefile, README.md, deepsea.spec
This moves all the `install` invocations from the specfile to
the Makefile, and collapses as many as possible with wildcards.
Where wildcards are not used, it's usually because there's
still a custom.sls file in the source tree that we don't want
to be installed.
Having `make install` means it's easy to try DeepSea on
arbitrary non-RPM-based distros (`git clone ; make install`)
and should also hopefully help with packaging for other distros.
=> Makefile: create install target

deepsea.spec
DeepSea needs the salt master to also be a salt minion.
May as well make this easy for people and add salt-minion to
the Requires in the spec file.
=> spec: require salt-minion

srv/modules/runners/ready.py, srv/modules/runners/validate.py, srv/salt/ceph/stage/deploy/default.sls
The first parameter of a runner function cannot be named "name",
as it is used internally by salt.
Fixes: #50
=> Fix runner parameter names in newer salt version (Boron)

Makefile, deepsea.spec, srv/modules/runners/disengage.py, srv/modules/runners/populate.py, srv/salt/_modules/purge.py, srv/salt/_modules/retry.py, srv/salt/ceph/purge/default.sls, srv/salt/ceph/purge/init.sls, srv/salt/ceph/rescind/client-nfs/default.sls, srv/salt/ceph/rescind/client-nfs/init.sls, srv/salt/ceph/rescind/default.sls, srv/salt/ceph/rescind/ganesha/default.sls, srv/salt/ceph/rescind/ganesha/init.sls, srv/salt/ceph/rescind/storage/default.sls, srv/salt/ceph/reset/default-all.sls, srv/salt/ceph/reset/default.sls, srv/salt/ceph/reset/init.sls
Add a runner to allow the resetting of a cluster and DeepSea configuration.  Require another runner to prevent accidental purging.
=> Add disengage.safety and ceph.purge

.travis.yml, tests/unit/_modules/test_validate.py, tox.ini
Runs just tox at the moment, also setting pip cache so that we don't
download packages between builds
=> tests: add Travis CI integration

.gitignore
Adding the gitignore python template from https://github.com/github/gitignore
So that while testing etc. we're not annoyed by stuff tox brings in
=> gitignore: adding the std. python gitignore

deepsea.spec
We use ipaddress python module in validate, while it might be installed
in many systems there is no explicit requires and it would lead to
interesting failures if not installed
=> rpm: add python-ipaddress to the rpm requires

srv/salt/ceph/configuration/files/ceph.conf-shared.j2, srv/salt/ceph/configuration/files/ceph.conf.j2
With the SES5 repo and kernel 4.4.38-93-default, iSCSI gateways fail to configure with the demo image.  Set rbd images to currently supported features.
=> Disable unsupported kernel features for rbd images

srv/salt/_modules/rgw.py
use the `set` builtin instead of the `import Set` which was only around
for the older python 2.6 days. Also minions report a warning otherwise.
`DeprecationWarning: the sets module is deprecated
from sets import Set`
=> rgw: import Set is deprecated, use builtin instead

srv/salt/ceph/stage/deploy/default.sls
Currently if time service is set to disabled we still call ceph.time
which tries to sync to the configured ntp server (default master), and
we fail since the time server was disabled, there wouldn't be an ntp
server in master, the other option of actually creating a no op sls file
seems counterintuitive to the validate check and global option of
setting a value to disabled.
Fixes: #102
=> stage3: don't do time sync if not configured

srv/modules/runners/populate.py, srv/modules/runners/push.py
Since python mangles anything inside a class with a double underscore
assuming private methods these would again raise NameErrors.
As an example:
```py
In [1]: def __foo():
...:     return 1
...:
In [2]: class A():
...:     def __init__(self):
...:         self.a = 1
...:     def bar(self):
...:         return __foo() + self.a
...:
In [3]: a = A()
In [4]: a.bar()
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-4-4b57aad064bc> in <module>()
----> 1 a.bar()
<ipython-input-2-4bba0c494767> in bar(self)
3         self.a = 1
4     def bar(self):
----> 5         return __foo() + self.a
6
NameError: global name '_A__foo' is not defined
```
Signed-off-by: Abhishek Lekshmanan …
=> populate: dont use double underscored functions from outside

srv/modules/runners/populate.py
In the populate.py module runner, the creation of the ganesha role directory was using the missing `create_dirs` function, which was renamed to `_create_dirs` in a recent PR.
=> stage1: fix the creation of ganesha role directory

srv/modules/runners/populate.py, srv/modules/runners/validate.py, tests/unit/_modules/test_validate.py
The purpose of this patch is to generalize the public/cluster network Ceph config option to support more than one network, as discussed in http://lists.suse.com/pipermail/deepsea-users/2016-December/000022.html
The algorithm for assigning the public/cluster networks work as follows:
1. assign the network with more hosts as public network
2. assign the second network with more hosts (but with at least 2 hosts) as cluster network
3. any network with a single host is assigned as a public network
4. in the end, if cluster network does not have any assignment than it inherits the same networks as the public network
=> stage 1,3: support for multiple public/cluster networks

Makefile, deepsea.spec
Adding state files to the Makefile (and RPM spec file), to allow the installation and usage of the salt-api.
=> cherrypy: add state files to Makefile and RPM spec files

srv/salt/ceph/mds/pools/default.sls
This should be adequate for even the smallest clusters and can be
increased for an existing pool if needed. The pg_count cannot be lowered
for an existing pool.
=> mds/pools: create cephfs pools with smallest recommended pg_count

Makefile, deepsea.spec
Until now the Makefile only copied files to the correct location.
Further steps were necessary to get a functional installation. This
commit adds the necessary step while keeping the build process working.
Also a chown was added to the rpm's post section to complete
installation.
=> Makefile/spec: complete installation with make and rpm

srv/salt/ceph/cherrypy/files/eauth.conf
This permission is needed for salt-api client query the state of
minions keys.
=> cherrypy: Add '@wheel' permission to salt-api clients

srv/salt/ceph/cherrypy/files/cherrypy.conf.j2
=> salt-api: use default host (0.0.0.0) for cherrypy

srv/salt/ceph/stage/prep/minion/default.sls
This PR forces the ordering of salt states applied to the minions in stage 0 to guarantee that mine functions have all the package dependencies installed before executing.
=> stage 0: force ordering of salt state items

deepsea.spec
=> spec file: add python-netaddr dependency for Opensuse 42.2

srv/salt/_modules/rgw.py, srv/salt/ceph/stage/radosgw/default.sls
Check in module instead of salt file
=> RGW: add users only if rgw_configurations are defined.

contributing.md
Replace the current Developer's Certificate of Origin 1.1 that
questionably may have had modifications with the verbatim version found
at https://developercertificate.org/.
From above website:
> Everyone is permitted to copy and distribute verbatim copies of this
> license document, but changing it is not allowed.
In addition, enclose the Certificate in a code block, as well as the
signed-off-by example so that the sections stand out more easily to the
reader, whether of the md file itself or of the rendered version.
Also fix header H1-H2 mix-up.
Signed-off-by: Blaine Gardner <blaine.gardner@suse.com>
=> Fix certificate of origin

srv/salt/_modules/ganesha.py
https://docs.python.org/2/library/sets.html
-> Deprecated since version 2.6: The built-in set/frozenset types replace this module.
LGTM
=> ganesha: import Set is deprecated, use builtin instead

deepsea.spec
use sle_version and is_opensuse instead.
=> spec: leap_version conditional is not reliable.

srv/salt/ceph/igw/restart/init.sls, srv/salt/ceph/mds/restart/default-shared.sls, srv/salt/ceph/mds/restart/init.sls, srv/salt/ceph/mon/restart/init.sls, srv/salt/ceph/osd/restart/init.sls, srv/salt/ceph/rgw/restart/default-shared.sls, srv/salt/ceph/rgw/restart/init.sls
* adapt the init from 'restart' to '<role>_restart_init'
* avoids collision and allows more fine grained control
resolves: #34 
=> Add default-shared.sls to mds/rgw

srv/modules/runners/push.py
If policy.cfg has a line like
profile-1Disk40GB-1/cluster/*sls #hey there
push would throw an exception. This commit strips comments before
further processing.
Fixes bsc#1030884.
=> push runner: policy.cfg strip comments at end of line

srv/modules/runners/push.py
This takes care of tabs as well. Multiple white spaces get removed by
the following rstrip. '#' without a separating white space are not
stripped, since they might belong to an 're=' modifier. Comments at the
end of lines should be separated by a white space.
=> push: eat any white space preceding a comment

srv/modules/runners/advise.py, srv/modules/runners/benchmark.py, srv/modules/runners/cephprocesses.py, srv/modules/runners/configure.py, srv/modules/runners/disengage.py, srv/modules/runners/filequeue.py, srv/modules/runners/minions.py, srv/modules/runners/net.py, srv/modules/runners/populate.py, srv/modules/runners/push.py, srv/modules/runners/ready.py, srv/modules/runners/rescinded.py, srv/modules/runners/select.py, srv/modules/runners/validate.py, srv/salt/_modules/advise.py, srv/salt/_modules/cephdisks.py, srv/salt/_modules/cephprocesses.py, srv/salt/_modules/ganesha.py, srv/salt/_modules/kernel.py, srv/salt/_modules/keyring.py, srv/salt/_modules/mon.py, srv/salt/_modules/multi.py, srv/salt/_modules/osd.py, srv/salt/_modules/purge.py, srv/salt/_modules/retry.py, srv/salt/_modules/rgw.py, srv/salt/_modules/wait.py, srv/salt/_modules/zypper_locks.py
Salt dictates that module files should have UTF-8 encoding, which is
done with a special comment per PEP-263. Inspecting the example modules
given by SaltStack at
https://github.com/saltstack/salt/tree/develop/salt/runners
Signed-off-by: Blaine Gardner <blaine.gardner@suse.com>
Fixes #176
=> Specify utf-8 encoding for python module files

srv/salt/ceph/ganesha/configure/default.sls, srv/salt/ceph/stage/configure/default.sls, srv/salt/ceph/stage/ganesha/default.sls
rgw creates users at stage 4, which is passed on to ganesha config.
=> Move ganesha config from stage 2 to 4. 

.pylintrc, bootstrap-virtualenv, requirements.txt
Add a linter to the project. In this case, we are using saltpylint as per discussion in #107. As part of this effort:
- Add linter config file copied from saltstack/salt (with a few modifications)
- Add requirements.txt which includes saltpylint and all of our related needs
- Add a script to create and bootstrap the venv so it's easier for other contributers to get the linter environ up and running quickly
Closes #107
=> Add linter

srv/modules/runners/populate.py
Commit bbf8df8 removed the storage role to prevent the creation of a directory that confused users; however, available_roles must still contain storage.  This fixes the ceph.purge functionality.
=> Fixes rescind of storage for ceph.purge

srv/salt/ceph/packages/common/default.sls
This accounts for different package names in various distros. More to be
added later.
=> pkg.install: add distribution conditional

srv/salt/ceph/openattic/default.sls
openATTIC 2.0.19 removed the XML-RPC API provided by the `openattic-rpcd` background service. Updated the Salt state file accordingly.
Signed-off-by: Lenz Grimmer <lgrimmer@suse.com>
=> Removed installing and enabling openattic-rpcd

srv/salt/ceph/stage/prep/minion/default.sls
For more information about the issue in question, see
https://github.com/SUSE/DeepSea/issues/213
In summary, the restart is causing a race condition with `ceph.mines`
such that the run of `ceph.mines` is not populating the salt mine
appropriately despite the fact that Salt reports `ceph.mines` is running
successfully.
Fixes #213
Signed-off-by: Blaine Gardner <blaine.gardner@suse.com>
=> Stage 0: reorder ceph.mines before restart

deepsea.spec
On Red Hat distributions, Python scripts are automatically byte-compiled
during the RPM packaging process. Adapted the file list accordingly to
include these files. Also needed to pass DOCDIR to the installation
target, to adapt to the different path on these distributions.
Signed-off-by: Lenz Grimmer <lgrimmer@suse.com>
=> Fixed building on RHEL/CentOS/Fedora

srv/salt/ceph/rescind/igw/lrbd/default.sls, srv/salt/ceph/stage/removal/default.sls
* Stop lrbd service only if the binary exists.
* Rename ID to match the other ones.
If i apply state 'ceph.rescind' i get the following error:
```
dev-vtheile-ceph-1:~ # salt 'dev-*1*' state.apply ceph.rescind
dev-vtheile-ceph-1.xxx:
Name: nop - Function: test.nop - Result: Clean Started: - 15:17:04.343550 Duration: 0.926 ms
..
Name: . /etc/sysconfig/lrbd; /usr/sbin/lrbd $LRBD_OPTIONS -W || : - Function: cmd.run - Result: Clean Started: - 15:17:04.547318 Duration: 4.94 ms
----------
ID: stop lrbd
Function: service.dead
Name: lrbd
Result: False
Comment: The named service lrbd is not available
Started: 15:17:04.552419
Duration: 7.528 ms
Changes:
Name: lrbd - Function: pkg.removed - Result: Clean Started: - 15:17:04.805288 Duration: 134.066 ms
..
Name: client-nfs nop - Function: test.nop - …
```
=> Fix some issues.

srv/modules/runners/ui-iscsi.py
Small changes to ui-iscsi:canned_populate() and ui-iscsi:save()
@swiftgist @rjfd and @ricardoasmarques - Can you guys take a look at ui-iscsi:save() and make sure it works for you? I modified the original to handle URI encoded kwargs['data'] which shouldn't require any changes to the oA frontend. However, I did remove json.dumps() and am relying that the frontend will perform it's own JSON.stringify() of the lrbd data before shipping it over to the salt-master. I found json.dumps() to misbehave and not format lrbd.conf properly. Should be just a small one line change at the oA frontend.
=> Update to wip-ui

srv/modules/runners/ui-iscsi.py
This PR adds the functions to query the status of lrbd service, and allows to deploy/undeploy lrbd from the iSCSI API.
=> iSCSI API: status, deploy and undeploy functions

srv/salt/ceph/cherrypy/start.sls
Only enable the service in 'enable salt-api' as the target name implies. It is not necessary to start/restart it there because this will be done in the 'restart salt-api' target.
=> Do not start salt-api.service twice.

Makefile, deepsea.spec, srv/modules/runners/populate.py, srv/pillar/ceph/init.sls, srv/pillar/ceph/openattic.sls-example, srv/salt/ceph/openattic/default.sls, srv/salt/ceph/openattic/oaconfig/default.sls, srv/salt/ceph/remove/openattic/default.sls, srv/salt/ceph/remove/openattic/init.sls, srv/salt/ceph/rescind/openattic/default.sls, srv/salt/ceph/rescind/openattic/init.sls, srv/salt/ceph/rescind/openattic/keyring/default.sls, srv/salt/ceph/rescind/openattic/keyring/init.sls, srv/salt/ceph/stage/openattic/default.sls, srv/salt/ceph/stage/removal/default.sls, srv/salt/ceph/stage/services/default.sls
* Make openATTIC configurable via policy.cfg.
* Use module.run instead of cmd.run to let Salt choose which init system to use to restart services.
* Remove packages openattic openattic-base openattic-pgsql (stage 5)
* If configured, then purge openattic postgres database during uninstall (stage 5)
* Add support for custom pillar data via /src/pillar/openattic.sls to customize oA orchestration.
=> Improve openATTIC orchestration

srv/salt/ceph/stage/prep/minion/default.sls
The commit 20b528c introduces a regression on the salt mines,
which prevents the mines from being populated because the packages
necessary for the mine functions have not been installed yet
at that phase.
=> stage 0: fix mines update regression

srv/modules/runners/ui_iscsi.py
The salt-api 2016.11.4-2.3 adds the parameter `'__current_eauth_user': 'admin'` when calling runner functions.
=> iscsi-api: fix runner function args to comply with salt-api calling convention

Makefile, deepsea.spec, srv/salt/ceph/configuration/files/ceph.conf.j2
This should provide an easy way to to add custom configuration options
to ceph.conf. Each file can contain global configuration (for the cluster
of a daemon type) and per daemon configuration. Note that per daemon
configuration must be preceded by the daemon name, e.g. [osd.1].
This addresses #205.
=> configuration: add include for [global,osd,mon,mds,client].conf

srv/salt/ceph/time/README, srv/salt/ceph/time/default.sls, srv/salt/ceph/time/ntp.sls
When ntp is running, do not overwrite ntp.conf since we can assume that
ntp is all setup. This should be a better default then blindly blowing
away a running ntp setup. The old behaviour can still be enabled by
setting 'time_init: ntp'.
=> ntp: detect if ntp is running and if so do nothing

srv/modules/runners/validate.py, srv/salt/ceph/stage/configure/default.sls
We had a user issue where the syntax of a osd file was slightly messed up. The parsing exception was swallowed by salt and as a result, the user got irritating results.
avoid that by preparsing
* any file that the policy.cfg points to
* any file under /srv/pillar/stack
as an additional check I added
* check if you have any files under the profiles directory (or even a directory)
and fails at stage 2
=> check human editable yaml files for syntax

Makefile, deepsea.spec, srv/salt/ceph/monitoring/default.sls, srv/salt/ceph/monitoring/disabled.sls, srv/salt/ceph/monitoring/init.sls, srv/salt/ceph/monitoring/prometheus/ceph_exporter.sls, srv/salt/ceph/monitoring/prometheus/init.sls, srv/salt/ceph/monitoring/prometheus/node_exporter.sls
This adds support for installation and deployment of the prometheus exporters. Assumption is that the repos offer the requested packages. The ceph_exporter is installed on the salt_master (since it needs an admin keyring), the node_exporter is installed on all nodes that are targeted.
This is not yet integrated into any particular stage, but it's easy enough to do.
=> Install and deploy prometheus exporters

Makefile, deepsea.spec, srv/salt/ceph/remove/storage/default.sls, srv/salt/ceph/remove/storage/drain/default.sls, srv/salt/ceph/remove/storage/drain/init.sls, srv/salt/ceph/rescind/storage/default.sls, srv/salt/ceph/rescind/storage/terminate/default.sls, srv/salt/ceph/rescind/storage/terminate/init.sls, srv/salt/ceph/stage/removal/default.sls
I thought I had cherry-picked this from the SES4 branch in the past, but the logic is still broken in main.  I verified that removal works properly against master with these changes.
=> Fix ordering of Storage node removal

srv/modules/runners/validate.py
currently fresh deployments are broken because the validation expects the cluster pillar data to be set.
=> static targeting if pillar not populated

srv/salt/ceph/ganesha/configure/default.sls, srv/salt/ceph/ganesha/files/ganesha.service
NFS-Ganesha package installs the service file "nfs-ganesha" at /etc/sysconfig.
For SUSE, we use the service file name as "nfs-ganesha". Other distributions require
service file to be named "ganesha".
=> NFS-Ganesha: Remove installation of service file.

srv/modules/runners/ui_rgw.py, tests/unit/runners/test_ui_rgw.py
The use of the string `'__opts__'` was triggering an exception inside salt code, and `**kwargs` was missing in the `credentials` function, which is required to call the runner from salt-api.
=> ui_rgw: fixed bugs in ui_rgw runner

srv/salt/_modules/osd.py
10000000000 bytes -> 10 gibabytes
The current version identifies any disk smaller than 10TB as 'small'
=> byte to gb conversion

srv/salt/_modules/osd.py
resolves deployment issues on bare-metal
=> Internal vs external rep of disks

srv/salt/_modules/cephdisks.py, srv/salt/_modules/osd.py
bare-metal returns by-id disk path while virtualized env return only the short path.
while the previous fixes for the disk identifier solved the initial problem, this is a followup fix for is_prepared() and is_activated()
fix: don't use the raw device as it comes from osd.configured() but rather the converted/sanitized attribute
part2)
data+journals struct wasn't correctly accessed hence not parsed.
=> is_prepared and is_activated needs correct device identifier

deepsea.spec
The munging of master_minion.sls only needs to happen once, on initial install
of the package.
=> build/ops: munge master_minion.sls only once

srv/salt/ceph/ganesha/files/ganesha.conf.j2
NFS-Ganesha is compiled with kerberos. In system without
kerberos, it complain. Set "Active_Krb5" to False.
=> NFS-Ganesha: Disable kerberos.

.travis.yml
Looks like travis changed their behaviour recently, run the tox job for 2.7 explicitly
=> try running py27 explicitly on travis

qa/common/common.sh, qa/suites/basic/health-mds.sh, qa/suites/basic/health-ok.sh
This PR creates a `suites/basic` hierarchy and moves the existing `basic-health-ok.sh` script into it. It also implements a `suites/basic/health-mds.sh` script for use in CephFS deployment testing.
https://github.com/SUSE/DeepSea/issues/321 was found while implementing this test.
=> qa: implement basic CephFS integration test

qa/README, qa/common/common.sh, qa/common/json.sh, qa/suites/basic/health-mds.sh, qa/suites/basic/health-ok.sh
For the time being we're introducing a `qa/.config` (which must be populated for each run) to tell the integration testing script how many storage nodes there are. If the number is less than three, then the necessary ceph.conf knobs are twiddled to ensure the cluster reaches HEALTH_OK.
No longer tolerate HEALTH_WARN.
Use "wait.until status=HEALTH_OK" to give the cluster some time to reach HEALTH_OK. The timeout seems to be five minutes. Don't know could that be extended, but it seems to reach HEALTH_OK pretty quick, so perhaps 5 minutes is enough.
=> qa: make 1- and 2-node clusters reach HEALTH_OK

srv/salt/_modules/osd.py
If only run on the device there is a chance that partprobe returns with
success, but dd after does not find the partition (on the second
partition created on a device). If partprobe is run on the created
partition everything works.
=> osd.py: run partprobe on the newly created partition

qa/common/common.sh, qa/common/json.sh, qa/common/nfs-ganesha.sh, qa/suites/basic/health-mds.sh, qa/suites/basic/health-nfs-ganesha.sh, qa/suites/basic/health-ok.sh
This PR adds a minimalistic `suites/basic/health-nfs-ganesha.sh` script to the integration test suite. It:
* adds a ganesha role
* configures NFS-ganesha for "No_root_squash" and "NIV_DEBUG"
* runs Stages 0-4
* works around buggy behavior (first attempt to communicate with the NFS server times out about half the time)
* mounts the NFS export as root
* touches a file
* unmounts the export
=> qa: implement basic NFS-Ganesha integration test

srv/salt/ceph/admin/files/keyring.j2
This otherwise causes various ceph pg related commands to fail like
`ceph pg dump`
Fixes: http://tracker.ceph.com/issues/20296
Reported-by: Patrick Nawracay <pnawracay@suse.com>
=> allow mgr full permissions for admin keyring

srv/modules/runners/populate.py, srv/salt/_modules/cephinspector.py
This removes the need to talk via librados to a running cluster on
the master_minion node, which might not yet be set up to talk to
the existing cluster at the time of import.
=> populate: get existing cluster's fsid from ceph.conf

srv/salt/ceph/configuration/files/ceph.conf.rgw
In RGW we do a suffix validation of the hostname, and in current case
the default DeepSea deployment sets the hostname as the short hostname
which would fail the default GET request at `/` and possibly a few other
tests that may depend on absoulte/subdomin/host style calling formats.
The reason for a suffix validation is that hostname is a part of the s3
signature and this needs to be extracted from the request
Fixes: https://github.com/SUSE/DeepSea/issues/341
Reported-by: Nathan Cutler <ncutler@suse.com>
=> rgw: conf: set `rgw_dns_name` as the fqdn

srv/salt/_modules/cephinspector.py
When ceph-disk encounters /dev/sr0, that's included in its output, but the
dict for that device has no "partitions" key, which results in a traceback
(KeyError: 'partitions') a couple of lines later.  That traceback then lands
in the generated YAML file (yuck).
In general, we need a good way of dealing with failures like this from
cephinspector so that we don't accidentally do Stupid Things[TM] later :-/
=> cephinspector: skip "disks" with no partitions

srv/salt/ceph/mds/pools/default.sls
This should avoid creating cephfs_data and cephfs_metadata pools in case
a cephfs instance was created using different pool names.
=> cephfs: don't create pools in case there is a cephfs instance

srv/salt/ceph/monitoring/grafana/init.sls
This fixes stage 2 failing on state "add prometheus ds".
=> grafana: wait for http api server to come up before adding datasource

srv/salt/ceph/rescind/openattic/default.sls
Starting with version 3.2.0, openATTIC consists only of a single `openattic` RPM package that obsoletes/replaces all other RPM subpackages (see https://tracker.openattic.org/browse/OP-2342 for details).
Remove `openattic-base` and `openattic-pgsql` from the list of packages to remove.
The upstream [PR#241](https://bitbucket.org/openattic/openattic/pull-requests/241/packaging-consolidate-subpackages-into-a/diff) has been merged and will be released in openATTIC 3.2.0,
which will also be included in the next SES5 Milestone 7 release.
Signed-off-by: Lenz Grimmer <lgrimmer@suse.com>
=> Fixes removal of openATTIC packages

srv/modules/runners/ui_rgw.py, tests/unit/runners/test_ui_rgw.py
Since PR #343 the RGW endpoint URL is using the FQDN. The ui_rgw runner must also be updated accordingly.
=> ui_rgw: Use FQDN for RGW endpoints url

Makefile, deepsea.spec, srv/modules/runners/ui_rgw.py, srv/salt/_modules/rgw.py, srv/salt/ceph/ganesha/files/ganesha.conf.j2, srv/salt/ceph/ganesha/files/gold.conf.j2, srv/salt/ceph/ganesha/files/silver-common.conf.j2, srv/salt/ceph/ganesha/files/silver.conf.j2, srv/salt/ceph/packages/common/default.sls, srv/salt/ceph/rgw/buckets/default.sls, srv/salt/ceph/rgw/buckets/init.sls, srv/salt/ceph/rgw/users/default.sls, srv/salt/ceph/stage/radosgw/default.sls
Currently NFS-Ganesha exports using RGW backend are being configured to export the `/` path. This poses some limitations to what the user can do when mounting such export. For instance, it cannot create a file, only directories.
This PR changes the RGW based exports configuration to export a bucket `demo` that is created for every RGW user configured by DeepSea.
=> ganesha: RGW exports should export a user bucket instead of "/"

Makefile, deepsea.spec, srv/modules/runners/populate.py, srv/salt/_modules/cephinspector.py, srv/salt/_modules/keyring.py, srv/salt/ceph/configuration/default-import.sls, srv/salt/ceph/configuration/files/ceph.conf.import
Here's the idea:
- Install DeepSea on some node (your salt master).
- Install salt-minion on every existing ceph node
- Hook up the minions to the masters as usual.
- Run `salt-run populate.engulf_existing_cluster`.  This will:
1) Distribute all the needed Salt and DeepSea modules to all the
minions.
2) Inspect the running Ceph cluster and populate
/srv/pillar/ceph/proposals with a layout of the cluster (ie.
roles, hardware profiles, policy.cfg).
3) Verify and save ceph.conf to DeepSea's internal directory
structure.
4) Save the various admin, mon, osd, mds and rgw keyrings to
DeepSea's internal directory structure.
5) Detect cluster and write out cluster fsid, internal and cluster
networks to DeepSea's internal directory structure. …
=> Add ability to import existing clusters

Makefile, deepsea.spec
> srv/salt/ceph/maintenance/upgrade/default.sls
``` yml
include:
- .master
- .minion
- .report
```
but we forgot to add it to the deepsea.spec and Makefile
=> Add missing report dir/* to spec and Makefile

Makefile, srv/salt/ceph/configuration/files/ceph.conf.j2
This PR fixes a Jinja syntax error in `srv/salt/ceph/configuration/files/ceph.conf.j2`, and adds the new configuration file to the Makefile.
Fixes regression introduced in da73d3e
=> Fix regression introduced in da73d3e

qa/common/common.sh, qa/common/rbd.sh, qa/suites/ceph-test/librbd.sh
At first I intended for this test to *run* ceph_test_librbd but that didn't work out because that executable produces quite a lot of output and Salt chokes on it. (The only way I know of to run the test script on the client node being `cmd.run`.)
```
2017-06-29T09:02:00.575 INFO:teuthology.orchestra.run.target147135132188.stderr:+ salt target147135132188.teuthology cmd.r
un 'sh /tmp/rbd_api_test.sh'
2017-06-29T09:07:16.693 INFO:teuthology.orchestra.run.target147135132188.stderr:ERROR: Minions returned with non-zero exit
code
2017-06-29T09:07:16.694 INFO:teuthology.orchestra.run.target147135132188.stdout:target147135132188.teuthology:
2017-06-29T09:07:16.695 INFO:teuthology.orchestra.run.target147135132188.stdout:    VALUE_TRIMMED
```
To get around that bogosity, I removed the …
=> qa: add a test that deploys a cluster capable of running ceph_test_librbd

srv/modules/runners/proposal.py
According to the [pydocs](https://docs.python.org/2/reference/expressions.html#is)
> The operators is and is not test for object identity: x is y is true if and only if x and y are the same object. x is not y yields the inverse truth value. [6]
This caused the proposal. func<_propose> to drop in the else block and define a journal_size although bluestore was defined.
=> Use == instead of is operator in str comp

srv/modules/runners/populate.py
My fault... facepalm-type moment.
=> populate: fix an unassigned reference error

srv/salt/_modules/packagemanager.py
Fixes bug in the upgrade_init: migration path.
When upgrading more than one base product, which we do, there is a selection to make, hence passing `-n`
Only difference is the order in which you have to provide the `--non-interactive` switch. in `zypper migration` you have to pass it to the subcommand(migration) instead of zypper.
Intentionally _NOT_ passing the `--allow-vendor-change`.
=> add -n, --replacefiles flags to zypper migration

srv/modules/runners/rescinded.py
If a minion returns a function exception(str) it will be transformed in a list of strings and passed to the jinja template, giving the user something like this:
``` 
- e
- x
- c
- e 
```
Only allow list() to be passed down to jinja and log.debug the remaining results.
=> Don't allow function exceptions to be passed to jinja

Makefile, deepsea.spec, doc/examples/policy.cfg-generic, doc/examples/policy.cfg-regex, doc/examples/policy.cfg-rolebased, qa/common/common.sh, srv/modules/runners/orderednodes.py, srv/modules/runners/populate.py, srv/modules/runners/validate.py, srv/salt/_modules/keyring.py, srv/salt/ceph/mgr/auth/default.sls, srv/salt/ceph/mgr/auth/init.sls, srv/salt/ceph/mgr/default.sls, srv/salt/ceph/mgr/files/keyring.j2, srv/salt/ceph/mgr/init.sls, srv/salt/ceph/mgr/key/default.sls, srv/salt/ceph/mgr/key/init.sls, srv/salt/ceph/mgr/keyring/default.sls, srv/salt/ceph/mgr/keyring/init.sls, srv/salt/ceph/mgr/restart/default.sls, srv/salt/ceph/mgr/restart/init.sls, srv/salt/ceph/rescind/mgr/default.sls, srv/salt/ceph/rescind/mgr/init.sls, srv/salt/ceph/rescind/mgr/keyring/default.sls, srv/salt/ceph/rescind/mgr/keyring/init.sls, srv/salt/ceph/restart/default.sls, srv/salt/ceph/restart/mgr/default.sls, srv/salt/ceph/restart/mgr/init.sls, srv/salt/ceph/stage/configure/default.sls, srv/salt/ceph/stage/deploy/default.sls
PROBLEMS:
- Error EINVAL: entity mgr.ses4-2 exists but key does not match
(when run over an existing cluster with auto-deployed mgrs)
TODO:
- remove
- rescind
- only mandatory on Luminous+
ALSO:
- add mgr support to engulfer
Fixes: https://github.com/SUSE/DeepSea/issues/183
=> Add role-mgr, to deploy ceph-mgr instances

srv/salt/ceph/pool/default.sls
The rbd pool is longer created as of https://github.com/ceph/ceph/pull/15894 - so don't create a demo image in it, either.
=> Refrain from creating a demo RBD image

srv/salt/ceph/igw/files/lrbd.conf.j2, srv/salt/ceph/igw/import/default.sls, srv/salt/ceph/stage/configure/default.sls, srv/salt/ceph/stage/iscsi/default.sls
This PR addresses the issue of configuring an iSCSI target when no RBD demo image was created.
This PR is related to #401 
=> iscsi: handle iscsi configure when no demo rbd image exists

srv/salt/_modules/osd.py, tests/unit/_modules/test_osd.py
Leave osd_partition intact for normal activation command.  Have is_prepared and is_activated call directly.
=> Wip partition check

srv/modules/runners/sharedsecret.py, srv/salt/ceph/openattic/default.sls, srv/salt/ceph/stage/openattic/default.sls, tests/unit/runners/test_sharedsecret.py
This PRs adds to the openattic installation the automatic configuration of the salt-api credentials and the configuration of the grafana hostname.
=> Added automatic configuration of openATTIC

srv/salt/ceph/mds/files/keyring.j2
Otherwise it would allow the mds keyring can be used to change mds
config options. This should be reserved for the admin keyring.
This commit aligns with what ceph-deploy does.
=> mds: daemon keyring only needs 'allow mds'

deepsea.spec
python-netaddr is part of the POOL repo in both SLE-12-SP2 and SLE-12-SP3, so
there's no danger.
=> build/ops: require python-netaddr unconditionally

Makefile, deepsea.spec
=> rpm: fix upgrade path when moving to sharedsecret eauth

qa/common/common.sh
If enough storage nodes are present no ceph.conf adjustment is
necessary.
=>  qa: don't fail on missing global.conf

srv/modules/runners/push.py, tests/unit/runners/test_push.py
strip: 
> Return a copy of the string with the leading and trailing characters removed. The chars argument is a string specifying the set of characters to be removed. If omitted or None, the chars argument defaults to removing whitespace. The chars argument is not a prefix or suffix; rather, all combinations of its values are stripped:
as opposed to rstrip:
> Return a copy of the string with trailing characters removed. The chars argument is a string specifying the set of characters to be removed. If omitted or None, the chars argument defaults to removing whitespace. The chars argument is not a suffix; rather, all combinations of its values are stripped:
=> remove leading and trailing whitespace

srv/salt/ceph/openattic/files/keyring.j2
This is necessary in order for openATTIC to access CephFS mounts.
=> Added "mds" caps to openATTIC keyring.

srv/salt/_modules/openattic.py, srv/salt/ceph/openattic/default.sls, tests/unit/_modules/test_openattic.py, tox.ini
This PR implements an openattic salt module to make it easy for DeepSea to configure the salt-api and grafana settings in the openATTIC configuration file.
=> openattic module implementation for configuring oA

srv/pillar/ceph/rgw-ssl.sls.example, srv/salt/ceph/configuration/files/ceph.conf.rgw-ssl, srv/salt/ceph/rgw/cert/default.sls, srv/salt/ceph/rgw/cert/init.sls, srv/salt/ceph/rgw/default-ssl.sls, srv/salt/ceph/rgw/files/rgw-ssl.j2
use rgw_configurations to create a role rgw-ssl alongside rgw, and have
an easier helper function that would copy certificates in pem format in
salt://ceph/rgw/cert/rgw.pem to the rgw nodes
=> wip: rgw: add examples for deploying rgw with ssl

srv/salt/ceph/igw/config/default.sls, srv/salt/ceph/mds/pools/default.sls
"ceph osd pool application enable" is a very new command, added quite late
in the luminous development cycle.
There are two basic scenarios in which this command might get run:
1. installation of recent luminous cluster - command should simply succeed
2. upgrade of an older cluster to luminous - command might not be recognized
Each of these has two subscenarios:
a. iscsi-image pool exists
b. iscsi-image pool does not exist (unlikely, but theoretically possible)
Provided the command is recognized, "ceph osd pool application enable" is of
course idempotent. The problem arises when the command is not recognized by the
MON we are talking to. In that case, Stage 4 currently fails, which is not a
satisfactory outcome for such a trivial error.
By using "onlyif", we try to handle all these …
=> igw: do not fail Stage 4 if command not recognized

srv/modules/runners/minions.py, srv/salt/ceph/maintenance/upgrade/master/default.sls, srv/salt/ceph/maintenance/upgrade/minion/default.sls
Moving the initial minions.ready to the beginning of the conditional check in the master file allows that step to fail faster.  Otherwise, the other runners must timeout on any minion but succeed and then finally fail on the minions.ready runner.
Salt uses failhard which is not passed from orchestrate to the runner.  The runner must raise an exception to cause the loop to fail in the minions/default.sls.  Jinja does not do dynamic evaluation which is why a conditional is not used.  Orchestrate does not honor return values from other runners.  Avoid using hardfail to prevent confusion.
Be more explicit about the timeout variable by prefixing the full runner name.
=> Move check to conditionals, change variable name

Makefile, srv/salt/ceph/monitoring/grafana/files/ceph-rgw-users.json, srv/salt/ceph/monitoring/grafana/init.sls, srv/salt/ceph/monitoring/prometheus/exporters/ceph_rgw_exporter.sls, srv/salt/ceph/monitoring/prometheus/exporters/files/ceph_rgw.py, srv/salt/ceph/monitoring/prometheus/files/prometheus.yml.j2, srv/salt/ceph/monitoring/prometheus/init.sls, srv/salt/ceph/rescind/rgw/default.sls, srv/salt/ceph/rescind/rgw/monitoring/default.sls, srv/salt/ceph/rescind/rgw/monitoring/init.sls, srv/salt/ceph/stage/deploy/default.sls
* Implement a Prometheus exporter for RGW statistics. The exporter is running on port 9156 by default. Additional RGW stats can be retrieved by this exporter in future, e.g. bucket stats.
* Add systemd service unit to manage Prometheus Ceph RGW exporter. The command 'systemctl daemon-reload' is executed via service.systemctl_reload after the service unit has been installed.
* Add Grafana 'Ceph - Object Gateway users' dashboard
* The Prometheus exporter is based on Python. The required Python package prometheus_client is installed via [python-prometheus-client](https://build.suse.de/package/show/SUSE:SLE-12-SP3:Update:Products:SES5/python-prometheus-client).
* The systemd unit and Prometheus exporter will be deinstaller on the minions when the RGW role is removed.
* Restart prometheus if …
=> Add Prometheus exporter for Ceph RGW user bandwidth stats

srv/salt/_modules/proposal.py
Otherwise this a function cannot assume that it was passed non-empty
lists. Fixed by moving the test for empty lists into said function.
=> proposal module: test for empty disks list after filtering

.gitignore
This PR adds the PyCharm project files to .gitignore
Signed-off-by: Ricardo Marques <rimarques@suse.com>
=> Add PyCharm project files to .gitignore

srv/salt/ceph/rescind/rgw/default.sls
I suspect the problem has to do with the globbing of the service name and that Salt is transforming the string along the way.  Settling for what works.
=> Giving up on salt state, calling systemctl directly

Makefile
Currently we set the master minion_id as fqdn, in vagrant systems and
such if a machine has multiple host entries, for different interfaces
the mininon_id may not match what hostname -f reports. Since we assume
salt-master and salt-minion is installed anyway for make install, we can
safely assume that `/etc/salt/minion_id` is already populated
=> Make install: set salt-master to minion_id from /etc/salt

srv/salt/ceph/stage/discovery/default.sls
Doing a pillar refresh before we discover profiles, this can help cases
where a global/cluster.yml already contains a custom role and we need
populate to use this role so that we can use the role in stage2's
policy.cfg, an existing example would be using rgw_configurations and
creating the rgw-ssl role in global.yml before stage1 which would not be
populated unless a pillar.refresh is done
Fixes: #529
=> stage1: try doing a pillar refresh before we push proposals

Makefile, deepsea.spec, man/deepsea.ceph_tgt.7, srv/modules/runners/ceph_tgt.py, srv/modules/runners/configure.py, srv/modules/runners/net.py, srv/modules/runners/populate.py, srv/modules/runners/proposal.py, srv/modules/runners/validate.py, srv/pillar/ceph/ceph_tgt.sls, srv/pillar/ceph/init.sls, srv/salt/ceph/maintenance/upgrade/minion/default.sls, srv/salt/ceph/stage/configure/default.sls, srv/salt/ceph/stage/discovery/default.sls, srv/salt/ceph/stage/prep/minion/default-no-update-no-reboot.sls, srv/salt/ceph/stage/prep/minion/default-no-update-reboot.sls, srv/salt/ceph/stage/prep/minion/default-update-no-reboot.sls, srv/salt/ceph/stage/prep/minion/default.sls
New mandatory variable to constrain the scope of minions considered for Ceph.  
The man page has details.  The /srv/pillar/ceph/ceph_tgt.sls has examples.  Note that 'make install' will still default to all minions.
=> ceph_tgt support

srv/modules/runners/ui_rgw.py
This commit makes ui_rgw only search for rgw conf bits in filenames that
we deploy the configuration files for ie. all the members of
`rgw_configurations` or `rgw` if nothing is configured, otherwise the
current runner just overrides the value with the last filename that
contains rgw_frontends which may not be valid anymore as more conf files
are added but not actually deployed
=> ui_rgw: don't glob over all conf files searching for rgws

srv/salt/ceph/stage/discovery/default-notimeout.sls
Since we're only overriding one function call and the rest remains the
same, use includes and excludes to achieve the same goal and avoid the
need to update this file when newer functions are called in default
=> stage2: keep default-notimeout in sync with default

Makefile
While this was already merged earlier, there seems to have been another
PR that came in that rewrote the old hostname -f above causing this to
be unused
=> Makefile: set master minion id from /etc/salt

srv/pillar/ceph/init.sls
This commit fixes a regression introduced in #0051a27
Fixes: #548 
=> Re-added the loading of rgw.sls to the pillar/ceph/init.sls

srv/modules/runners/populate.py, srv/salt/_modules/cephinspector.py
OSDs can listen on public and internal cluster IPs.  Thus, when deriving
the cluster network during the engulf process, filter out public IPs.
=> populate,cephinspector: improve running cluster network detection

deepsea.spec
Fixes: https://github.com/SUSE/DeepSea/issues/577
=> build/ops: omit %config for python files

Makefile, deepsea.spec, srv/salt/_modules/osd.py, srv/salt/ceph/migrate/nodes/default.sls, srv/salt/ceph/migrate/osds/default.sls, srv/salt/ceph/remove/migrated/default.sls, srv/salt/ceph/remove/migrated/init.sls
Fix removal of OSDs during Stage 5
Adjust migration to use its own removal
=> Only use ceph.client.storage.keyring when it exists

srv/salt/ceph/configuration/default.sls
Otherwise this can cause failure to distribute the config file.
=> config: only specifiy one source to force salt to look for it

srv/salt/_modules/proposal.py
Originally the code assumed that if "Device Files" was present, a by-id
path would be in it. This is not always the case.
=> proposal module: fall back to Device File in case by-id is not present

srv/modules/runners/validate.py
Fixes https://bugzilla.suse.com/show_bug.cgi?id=1057011 for the case when rgw and openattic roles are not colocated.
I discussed the colocated case with a couple folks and the consensus seemed to be that we should not support it. In other words, Stage 4 should fail if we detect colocation of rgw and openattic roles in the validation.
The colocated case is still WIP in #602 but I split this commit off into a separate PR since it's a simple fix for the usual (non-colocated) case.
=> validate: no conflict when rgw and oA are not on same node

srv/salt/ceph/maintenance/upgrade/minion/default.sls, srv/salt/ceph/stage/prep/minion/default-update-no-reboot.sls
When we get deepsea_minions from the pillar it will be understood as * without the quotation marks.
The SLS syntax requires the target to be wrapped, though.
=> Fix syntax for inline pillar [deepsea_minions] parsing.

qa/common/common.sh, qa/common/nfs-ganesha.sh, qa/common/rgw.sh, qa/suites/basic/health-nfs-ganesha.sh, qa/suites/basic/health-openattic.sh, qa/suites/basic/health-rgw-ssl.sh, qa/suites/basic/health-rgw.sh
For the time being, it only deploys openATTIC and RGW and checks
the RGW deployment for sanity. It does not do any validation of the
oA deployment.
=> qa: add openattic-with-rgw deployment test

srv/modules/runners/net.py
Taking out the dict, because salt return sort by key no matter what I do. 
So I can only return list when which look not as good as dict, unless someone has a better idea. 
What I do was taking out the text and convert the int, then sort. Instead of doing natural sort with string which I need to install another library or implement something much bigger with lots of corner case.
=> Bug fixing the sort order of iperf result which was not natural

srv/modules/runners/populate.py
This new discovery algorithm uses two new heuristics to find the
main public network and the cluster network.
The heuristic to find the public networks works like this:
If a network matches one of the "hostname -i" of the minions, then
the network is considered as a public network.
The heuristic to find the cluster networks works like this:
If a network that has more than one minion does not match any
of the salt-master interface addresses, then the network is
considered as a cluster network.
Otherwise, the discovery fails to the already existing behavior.
=> stage 1: network discovery revisited

Makefile, deepsea.spec, qa/common/rgw.sh, srv/modules/runners/ui_rgw.py, srv/pillar/ceph/init.sls, srv/salt/_modules/rgw.py, srv/salt/ceph/ganesha/files/ganesha.conf.j2, srv/salt/ceph/rgw/files/system.user.yml, srv/salt/ceph/rgw/files/users.j2, srv/salt/ceph/rgw/users/users.d/README
Users are not tied to configurations (or zones).  This has been inherently wrong.   Users can optionally be maintained under .../ceph/rgw/users/users.d with this change.  The /srv/pillar/ceph/rgw.sls is redundant with the structure under /srv/pillar/ceph/stack.  The rgw_configurations has become a simple array and can be maintained in either the global.yml or ceph/cluster.yml.
Fixes: https://github.com/SUSE/DeepSea/issues/314
=> Split users from rgw_configuration, add system user

srv/modules/runners/validate.py
Don't know exactly why (presumably the runner is a subprocess and its stdout is
not captured), but the validation report does not appear in the teuthology log.
Not being able to see the validation messages makes it hard to debug test
failures. Therefore, echo these messages to the logger at the appropriate
severity level.
Fixes: https://github.com/SUSE/DeepSea/issues/611
=> Echo validation messages to log

srv/salt/ceph/monitoring/grafana/files/ceph-rgw.json, srv/salt/ceph/monitoring/grafana/init.sls, srv/salt/ceph/monitoring/prometheus/exporters/files/ceph_rgw.py
https://tracker.openattic.org/browse/OP-2585
- Add a RGW Grafana dashboard to display user and bucket count
- Take care that the RGW Grafana dashboards are installed or uninstalled if there is a RGW node configured (this is done in stage 2)
- Modify the Prometheus RGW exporter
=> Provide additional RGW stats: number of users/buckets (OP-2585).

srv/salt/ceph/monitoring/grafana/files/ceph-rgw-users.json
Display more user usage information in the Grafana dashboard (OP-2669)
See https://tracker.openattic.org/browse/OP-2669 for more information.
=> Display more statistics on the RGW Grafana dashboard

qa/common/common.sh, qa/suites/basic/health-rgw-ssl.sh, srv/salt/ceph/rgw/cert/default.sls
Fixes: https://github.com/SUSE/DeepSea/issues/636
Reported-by: Martin Weiss <mweiss@suse.com>
=> rgw: ssl: make pem files readable only to ceph user & group

srv/salt/_modules/cephprocesses.py
currently running stage0 after having an install with rgw_configurations
would fail because cephprocesses wouldn't have the relevant keys for
rgw_configurations other than the default. Solve this by adding all the
keys of rgw_configurations which correspond to the role name to the
process dictionary
Fixes: https://github.com/SUSE/DeepSea/issues/647
=> modules/cephprocess: support rgw_configurations

qa/common/common.sh, srv/modules/runners/validate.py
Before we were emitting log messages at "warning" and "error" severity, which
meant they were appearing on the screen, causing duplicate messages.
=> validate: log validation results at info severity

qa/suites/basic/health-igw.sh, qa/suites/basic/health-mds.sh, qa/suites/basic/health-nfs-ganesha.sh, qa/suites/basic/health-ok-encrypted.sh, qa/suites/basic/health-ok.sh, qa/suites/basic/health-openattic.sh, qa/suites/basic/health-rgw.sh
Stage.0 behaves differently (executes updates sequentially and checks for cluster health and service status). To increase the exercised codepath we should run this _after_ the initial deployment.
=> Run stage.0 after deploying as bevahiour changes

srv/modules/runners/validate.py
Use file.search, which supports a regex (since file.contains_regex was
deprecated), and only match port=80, earlier we use to match port=8000
which cause issue when oa and rgw are colocated. This still fails in an
obnoxious case when someone tries ssl over port 80, since 80s would
still not match, and pass validate, and would try to install oa and
rgw-ssl with the same port 80 but 80s is a source of trouble for
many other cases anyway
Fixes: https://github.com/SUSE/DeepSea/issues/652
Reported-by: Martin Weiss <mweiss@suse.com>
=> validate: openattic validation succeeds for non 80 ports

cli/monitor.py, cli/monitors/terminal_outputter.py, cli/stage_executor.py, cli/stage_parser.py
The deepsea-cli was not handling the case when some SLS file contained syntax errors, and an ugly python stack trace was being thrown.
This PR implements the handling of SLS syntax errors.
Video with demo: https://asciinema.org/a/ap5G06hRIxR2JO2x6YOp7hAY6
=> cli: gracefully handle SLS rendering errors

srv/salt/ceph/configuration/files/rgw-ssl.conf, srv/salt/ceph/configuration/files/rgw.conf
Enable the RGW usage logging to be able to display statistics in the Grafana RGW dashboard.
https://tracker.openattic.org/browse/OP-2663
=> RGW usage log is not enabled by default (OP-2663)

Makefile
When installing via "make install", we were getting Permission denied in the runner.
Fixes: https://github.com/SUSE/DeepSea/issues/675
=> Makefile: fix permissions on ceph.conf.checksum directory

srv/modules/runners/validate.py
In case there is only one single minion (test-environment with everything on a
single server) and DEV_ENV=true is being set in the pillar, the result of
len(self.data.keys()) is 1 and with that this is not greater than 1 and
DEV_ENV=true is not detected.
Reported-by: Martin Weiss <Martin.Weiss@suse.com>
=> validate: detect DEV_ENV=true from pillar in single minion case

srv/salt/_modules/cephprocesses.py
EDIT: moved rgw-ssl role addition to #680
~Furthermore~ we don't respect openattic at all although I was pretty sure we had that in. Did i miss the reason to drop it?
=> Add openattic to list of checked processes

srv/modules/runners/select.py
Improve `select.minions` runner to be able to search for multiple roles. Now it is possible to call this function like `salt.saltutil.runner('select.one_minion', cluster='ceph', roles=['admin','rgw'])`
=> Improve select.minions runner to be able to search for multiple roles.

srv/modules/runners/ui_ganesha.py
Quotes are not allowed for CLIENT.clients field on _ganesha.conf_ file.
This PR will change the _ganesha.conf_ writer to not write quotes on this field, to prevent an error when nfs-ganesha parses the configuration file generated by DeepSea.
**VALID** _ganesha.conf_ file:
```
EXPORT {
...
CLIENT {
clients = 11.150.96.27;
access_type = "RO";
...
}
...
}
```
**INVALID** _ganesha.conf_ file:
```
EXPORT {
...
CLIENT {
clients = "11.150.96.27";
access_type = "RO";
...
}
...
}
```
Signed-off-by: Ricardo Marques <rimarques@suse.com>
=> Remove quotes from NFS Ganesha CLIENT.clients field

cli/monitor.py, cli/monitors/terminal_outputter.py
This PR handles the case where some step of the execution was parsed by the CLI parser, but during salt-run execution such step is skipped.
=> cli: gracefully handle non-started skipped steps

srv/salt/_modules/cephinspector.py
Avoids API changes introduced across psutil
versions (ie. psutil.Process.name vs .name(), etc).
Untabify.
=> cephinspector: use as_dict when examining a psutil.Process

srv/salt/ceph/monitoring/prometheus/exporters/ceph_rgw_exporter.sls, srv/salt/ceph/monitoring/prometheus/exporters/files/ceph_rgw.py, srv/salt/ceph/monitoring/prometheus/files/prometheus.yml.j2, srv/salt/ceph/rescind/rgw/default.sls, srv/salt/ceph/rescind/rgw/monitoring/default.sls, srv/salt/ceph/stage/deploy/default.sls, srv/salt/ceph/stage/radosgw/default.sls, srv/salt/ceph/stage/removal/default-remove.sls, srv/salt/ceph/stage/removal/default.sls
https://tracker.openattic.org/browse/OP-2678
- Do not run the Prometheus RGW exporter as a webserver
- Remove systemd unit to handle the RGW exporter
- Introduce cron job to execute the RGW exporter every 5 minutes and write the content to a *.prom file
- Use node_exporter to process the metrics
- RGW exporter: Create a new registry, otherwise unwanted default collectors are added automatically
- Relocate installation of Prometheus RGW exporter from ceph.stage.deploy to ceph.stage.radosgw
- The Prometheus RGW exporter will be installed on the 'master' node if there is at least one 'rgw' node. The role 'master' takes care that the required admin keyring is installed which is required by the radosgw-admin CLI tool that is used by the exporter script. See …
=> Refactor RGW Prometheus exporter to use node_exporter (OP-2678)

deepsea.spec, man/deepsea.commands.7, srv/modules/runners/fs.py, srv/salt/_modules/cephprocesses.py, srv/salt/_modules/fs.py, srv/salt/_modules/osd.py, srv/salt/ceph/migrate/subvolume/default.sls, srv/salt/ceph/migrate/subvolume/init.sls
The actual goal of this work is to help those using btrfs, to create/migrate the Ceph variable state directory to a btrfs subvolume.  The hope is that it can be extended for other filesystem related things in the future.
Runner adds:
`salt-run fs.inspect_var` - Inspection of /var/lib/ceph
`salt-run fs.create_var` - Creation of /var/lib/ceph as a btrfs subvolume
`salt-run fs.migrate_var` - Migration of existing /var/lib/ceph to a btrfs subvolume
`salt-run fs.correct_var_attrs` - Removing copy-on-write from /var/lib/ceph and it's children, while omitting /var/lib/ceph/osd/*
Use:
Automatic: `salt-run state.orch ceph.migrate.subvolume`
Controlled: `salt-run fs.inspect_var` and read/follow recommendations
Requires some testing beyond my 4 node virtual cluster.  Main pain points are actually …
=> filesystem inspection and btrfs subvol creation/migration

srv/salt/_modules/cephimages.py
This will fix the following error:
Okt 05 15:10:17 xxxxxxxx salt-minion[1689]: [ERROR   ] Failed to import module cephimages, this is due most likely to a syntax error:
Okt 05 15:10:17 xxxxxxxx salt-minion[1689]: Traceback (most recent call last):
Okt 05 15:10:17 xxxxxxxx salt-minion[1689]:   File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1333, in _load_module
Okt 05 15:10:17 xxxxxxxx salt-minion[1689]:     mod = imp.load_module(mod_namespace, fn_, fpath, desc)
Okt 05 15:10:17 xxxxxxxx salt-minion[1689]:   File "/var/cache/salt/minion/extmods/modules/cephimages.py", line 22
Okt 05 15:10:17 xxxxxxxx salt-minion[1689]:     images[pool] = []
Okt 05 15:10:17 xxxxxxxx salt-minion[1689]:          ^
Okt 05 15:10:17 xxxxxxxx salt-minion[1689]: IndentationError: expected an indented …
=> Fix missing indention.

qa/common/helper.sh
This did not work out as expected. The test goes so quickly that, if a stage
fails, the next one starts before set -x is issued.
=> qa: do not try to turn -x off and on during the test

srv/salt/ceph/osd/default.sls
should use name sdX (like the data-only type) to check if a disk is already built and mounted for data+journal type
=> fixed check method of disk activation

srv/salt/_modules/openattic.py, tests/unit/_modules/test_openattic.py
This PR is related to the oA issue: https://tracker.openattic.org/browse/OP-2808
=> openattic: Check oA config file in /etc/default and always overwrite settings

srv/salt/ceph/igw/default.sls, srv/salt/ceph/igw/import/default.sls, srv/salt/ceph/initiator/iscsiadm-salt.sls, srv/salt/ceph/initiator/iscsiadm.sls, srv/salt/ceph/monitoring/grafana/init.sls, srv/salt/ceph/monitoring/prometheus/alertmanager.sls, srv/salt/ceph/monitoring/prometheus/exporters/ceph_rgw_exporter.sls, srv/salt/ceph/monitoring/prometheus/exporters/node_exporter.sls, srv/salt/ceph/monitoring/prometheus/exporters/rbd_exporter.sls, srv/salt/ceph/monitoring/prometheus/init.sls, srv/salt/ceph/openattic/default.sls, srv/salt/ceph/packages/common/default.sls, srv/salt/ceph/rgw/buckets/default.sls, srv/salt/ceph/rgw/default-shared.sls, srv/salt/ceph/rgw/default-ssl.sls, srv/salt/ceph/rgw/default.sls, srv/salt/ceph/rgw/users/default.sls, srv/salt/ceph/time/ntp/default.sls
potential bugs:
* [prometheus package](https://github.com/SUSE/DeepSea/compare/master...jschmid1:wip-refresh-pgk-installed?expand=1#diff-9c15a59ff451861ec015955c08e85fcbR4)
* [grafana package](https://github.com/SUSE/DeepSea/compare/master...jschmid1:wip-refresh-pgk-installed?expand=1#diff-b7cf5b0b97e32158e7f5efda4e9d73a9R3)
Did you leave the `name: <pkg>` parameter by intention?
Fixes: https://github.com/SUSE/DeepSea/issues/730
=> refresh repo database before installing pkgs

qa/common/common.sh, qa/suites/basic/health-ok.sh, qa/suites/basic/health-rgw.sh
Implementing basic validation for restarted services
for now only: MON, OSD, RGW
Depends on: #734 
=> qa: Add basic restart mechanism for ceph.restart tests

srv/salt/ceph/restart/ganesha/default.sls, srv/salt/ceph/restart/igw/default.sls, srv/salt/ceph/restart/mds/default.sls, srv/salt/ceph/restart/mon/default.sls, srv/salt/ceph/restart/osd/default.sls, srv/salt/ceph/restart/rgw/default.sls
We technically have everything in place to follow the controlled/staged
restart. Adding the cephprocesses check as ceph.wait doesn't interrupt
a failed restart for interfaces/services
If you now want to _forcefully_ restart services use:
salt -I 'roles:$service' ceph.$service.restart
Addresses: #221 
=>  Staged restarts of services

srv/salt/_modules/osd.py, tests/unit/_modules/test_osd.py
Issues:
* Encryption:
ceph-disk expects the raw device and handles the creation
of the next higest partition in addition to encrypting
the wal/db/device.
* Bluestore deployment:
refer to #615 
Also refactoring the decision paths in `_bluestore_args()`.
resolves #615 
Tested:
* wal/db defined / no size specified / unencrypted
* wal/db defined  no size specified / encrypted
* wal/db defined / size specified / unencrypted
* wal/db defined / size specified / encrypted
* no wal/db defined / no size specified / unencrypted
* no wal/db defined  no size specified / encrypted
* no wal/db defined / size specified / unencrypted
* no wal/db defined / size specified / encrypted
Tackles: https://github.com/SUSE/DeepSea/issues/755
EDIT: tests can be found …
=> Properly handle bluestore args

qa/suites/basic/health-ok.sh
This fixes a regression introduced by 01833ee983e6da8b41706c3819a07ce9a86b0f49
=> qa: health-ok.sh: liberally accept both --encrypted and --encryption

srv/salt/ceph/monitoring/grafana/files/ceph-cluster.json
To fix this issue a mapping for "0" => "0 ns" is added.
The other solution to set the decimal precision to 1 seems not to work, the widget still shows 'xxx s' for example instead of 'xxx.y s' as usual.
If the decimal precision is set to any value, Grafana displays 0 values as 'ns', so the mapping above with the unit 'ns' should be the best solution.
=> "NaN ns" in Dashboard (bsc1065590)

srv/salt/_modules/fs.py
Also, avoid possible KeyError when invoking get_device_info.
=> fs: fix minor error introduced by epic pylint work

Makefile, deepsea.spec, srv/salt/ceph/maintenance/upgrade/master/default.sls, srv/salt/ceph/maintenance/upgrade/minion/default.sls, srv/salt/ceph/setosdflags/default.sls, srv/salt/ceph/setosdflags/requireosdrelease/default.sls, srv/salt/ceph/setosdflags/requireosdrelease/init.sls, srv/salt/ceph/setosdflags/sortbitwise/default.sls, srv/salt/ceph/setosdflags/sortbitwise/init.sls
Make sure to set the osd flag before we upgrade the cluster to not run
into http://tracker.ceph.com/issues/20416.
=> add sortbitwise flag and split them up nicely

srv/modules/runners/select.py
````
Usually, it's safe to assume that the short hostname (as is used for
MON, MDS, MGR and RGW instance IDs) is everything up to the first dot
in the FQDN.  Unfortunately that's not necessarily true when importing
a Ceph cluster that was deployed by Crowbar, into DeepSea.
Crowbar will give systems hostnames like this:
d52-54-00-76-21-bc.example.com
That's the FQDN of the salt minion, on Crowbar's admin network
(192.168.124.0/24).  That's fine so far.  But, when Crowbar deploys
MON, MDS, RGW, etc., these will usually be running on Crowbar's public
network (192.168.126.0/24).  There'll be a separate DNS entry for these
public IP addresses (e.g.: public.d52-54-00-76-21-bc.example.com),
and -- here's the problem -- the instance ID used for, say, the MONs,
will be:
public.d52-54-00-76-21-bc …
```
=> select: Use host grain for short hostname

tox.ini
=> pyfakefs 3.3 removes support for python 2.6

srv/pillar/ceph/deepsea_minions.sls
The man page is named `deepsea-minions`, not `deepsea.minions`.
=> Fixed typo in deepsea_minions.sls

srv/modules/runners/ui_iscsi.py
If the return code is meant then result['retcode'] must be used, see https://github.com/saltstack/salt/blob/2016.11/salt/runners/state.py#L68, otherwise feel free to decline this PR.
@rjfd Please review this PR, too.
=> Fix return code issue in ui_iscsi.deploy runner.

srv/salt/_modules/cephprocesses.py
Fix same error as in https://github.com/SUSE/DeepSea/pull/661 with client-cephfs, client-nfs, client-radosgw and client-iscsi roles
Signed-off-by: Jozef Pupava <jpupava@suse.com>
=> Add client processes to list of checked processes

srv/salt/ceph/mines/default.sls, srv/salt/ceph/stage/iscsi/default.sls
The current behavior of updating the salt mines in stage 0 using `service.running` module is making the salt-minion to lose the job information of the following step, which is `ceph.updates`, because it restarts the salt-minion. The consequence is that stage 0 finishes the execution before the ceph.updates job is finished.
This PR fixes the issue by calling the `mine.update` module instead.
=> stage 0: update mines using mines.update instead of minion restart

srv/salt/_modules/rgw.py
Fixes a regression introduced in commit 0b5116e of PR #765 
In the commit referenced above, the verification of the 'system' flag was removed and thus currently DeepSea does not create the admin user with the `--system` option.
@smithfarm could you check why our radosgw suite did not catch this regression?
**Credits for finding this bug goes to @tspmelo (Tiago Melo)**
=> radosgw: fix creation of radosgw system user

deepsea.spec
This commit adds needed SPEC changes for SR#805:
> Refactor Prometheus RGW exporter customization according to the DeepSea conventions.
=> spec/fix: add new Prometheus RGW exporter files

srv/salt/_modules/cephinspector.py, srv/salt/_modules/osd.py, tests/unit/_modules/test_osd.py
As of luminous 12.2.2 ceph-disk will emit a "loud" (and potentially
disconcerting) warning, whenever it is invocated, unless PYTHONWARNINGS is set
to "ignore".
=> Quash ceph-disk deprecation warning

tox.ini
(cherry picked from commit 10738568b80a67eb37beed7945481cfba65c1f02)
=> [backport] pyfakefs 3.3 removes support for python 2.6

qa/suites/basic/health-ok.sh
The usage() function says it should be "--encryption" but we were
only accepting "--encrypted".
Actually, we were not even doing that effectively - this commit also makes
the needed adjustment to --long option we are sending to getopt.
(cherry picked from commit 6faa1a7f83c2e6f734637b3d2c2ce4facdab65a3)
=> [backport] qa: health-ok.sh: liberally accept both --encrypted and --encryption

srv/modules/runners/select.py
Usually, it's safe to assume that the short hostname (as is used for
MON, MDS, MGR and RGW instance IDs) is everything up to the first dot
in the FQDN.  Unfortunately that's not necessarily true when importing
a Ceph cluster that was deployed by Crowbar, into DeepSea.
Crowbar will give systems hostnames like this:
d52-54-00-76-21-bc.example.com
That's the FQDN of the salt minion, on Crowbar's admin network
(192.168.124.0/24).  That's fine so far.  But, when Crowbar deploys
MON, MDS, RGW, etc., these will usually be running on Crowbar's public
network (192.168.126.0/24).  There'll be a separate DNS entry for these
public IP addresses (e.g.: public.d52-54-00-76-21-bc.example.com),
and -- here's the problem -- the instance ID used for, say, the MONs,
will be:
public.d52-54-00-76-21-bc
That …
=> [backport] select: Use host grain for short hostname

srv/salt/ceph/monitoring/grafana/files/ceph-cluster.json
To fix this issue a mapping for "0" => "0 s" is added. The other solution to set the decimal precision to 1 seems not to work, the widget still shows 'xxx s' for example instead of 'xxx.y s' as usual.
backport of #764 
(cherry picked from commit 1b860c90cac13a0189cda43361a1e6d619646a1a)
=> [backport] "NaN ns" in Dashboard (bsc1065590)

srv/modules/runners/populate.py
backport of #776 
Fixes #767
(cherry picked from commit 3cb188bd4935c94c4395c484a7bfa7cd204de492)
=> [backport] populate: explicitly import validate runner

srv/modules/runners/advise.py, srv/salt/ceph/maintenance/upgrade/minion/default.sls
backport of #779 
(cherry picked from commit 0f638c36495fe08cdc480364a937d3f056ede513)
=> [backport] Safety net for a failed engulfment

Makefile, deepsea.spec, srv/salt/ceph/maintenance/upgrade/master/default.sls, srv/salt/ceph/maintenance/upgrade/minion/default.sls, srv/salt/ceph/setosdflags/default.sls, srv/salt/ceph/setosdflags/requireosdrelease/default.sls, srv/salt/ceph/setosdflags/requireosdrelease/init.sls, srv/salt/ceph/setosdflags/sortbitwise/default.sls, srv/salt/ceph/setosdflags/sortbitwise/init.sls
backport of #780 
Make sure to set the osd flag before we upgrade the cluster to not run
into http://tracker.ceph.com/issues/20416.
(cherry picked from commit 3663a853d8d1b1768d4e3736afd42d3286256a1c)
=> [backport] add sortbitwise flag and split them up nicely

srv/salt/_modules/osd.py, tests/unit/_modules/test_osd.py
backport of #786
(cherry picked from commit b69f946)
needs extra review. variable names deviate from master due to linting changes.
=> [backport] Fix is_prepared for NVMe 

srv/salt/_modules/cephinspector.py, srv/salt/_modules/osd.py, tests/unit/_modules/test_osd.py
As of luminous 12.2.2 ceph-disk will emit a "loud" (and potentially
disconcerting) warning, whenever it is invocated, unless PYTHONWARNINGS is set
to "ignore".
backport of #809 
(cherry picked from commit 59cc23039f7859707bd4a303cb36b644a63ab2f6)
=> [backport] Quash ceph-disk deprecation warning

deepsea.spec
This commit adds needed SPEC changes for SR#805:
> Refactor Prometheus RGW exporter customization according to the DeepSea conventions.
backport of #812
(cherry picked from commit 68e732d5309819a6cff6b542815b6ed70a92e28f)
=> [backport] spec/fix: add new Prometheus RGW exporter files

srv/salt/ceph/packages/default.sls, srv/salt/ceph/stage/deploy/default.sls
(cherry picked from commit b76030976ce7c7437783eb72e23d23f18cbac91d)
no conflict but moved the failhard from stage/3/core/default.sls to
stage/3/default.sls
Fixes: #856
=> [backport] stage 3: don't update ceph packages, only install

srv/modules/runners/ui_iscsi.py, srv/salt/_modules/iscsi.py
backport of #807 
This PR introduces the support for deploying and undeploying the lrbd iSCSI configuration on individual iSCSI gateways.
It also enhances the status information retrieved from each gateway.
=> [backport] ui_iscsi: support individual management of iSCSI gateways

srv/salt/ceph/monitoring/prometheus/exporters/ceph_rgw_exporter/default.sls
backport of #815 
This adds the file instead of just changing it. The cause for it is that https://github.com/SUSE/DeepSea/pull/831 is not yet merged.
(cherry picked from commit ad01f5694154a1b63f16cf474eba47349c075e65)
=> [backport] Replace slspath with absolute file path.

deepsea.spec
fixes rpm-checks
> [   52s] deepsea-0.8+git.55.f8e460793-2.6.1.noarch.rpm: directories not owned by a package:
> [   52s]  - /srv/salt/ceph/restart/ganesha/lax
> [   52s]  - /srv/salt/ceph/restart/igw/lax
> [   52s]  - /srv/salt/ceph/restart/mds/lax
> [   52s]  - /srv/salt/ceph/restart/mgr/lax
> [   52s]  - /srv/salt/ceph/restart/mon/lax
> [   52s]  - /srv/salt/ceph/restart/openattic/lax
> [   52s]  - /srv/salt/ceph/restart/osd/lax
> [   52s]  - /srv/salt/ceph/restart/rgw/lax
> 
=> fix rpm-checks for: 'directories not owned by a package'

deepsea.spec
backport of #859 
(cherry picked from commit ac9daab79cf97d938813b1d7daa72a1332e29fb6)
=> [backport] fix directories not owned by a package

.gitignore, Makefile, deepsea.spec.in
Changing the spec file in place via automation and making manual corrections is too error prone.  Separate the automated process from the manual one.
=> Rename deepsea.spec to deepsea.spec.in, prevent side effects

Makefile, deepsea.spec.in, srv/salt/_modules/cephprocesses.py, srv/salt/ceph/processes/admin/default.sls, srv/salt/ceph/processes/admin/init.sls, srv/salt/ceph/processes/ganesha/default.sls, srv/salt/ceph/processes/ganesha/init.sls, srv/salt/ceph/processes/igw/default.sls, srv/salt/ceph/processes/igw/init.sls, srv/salt/ceph/processes/mds/default.sls, srv/salt/ceph/processes/mds/init.sls, srv/salt/ceph/processes/mgr/default.sls, srv/salt/ceph/processes/mgr/init.sls, srv/salt/ceph/processes/mon/default.sls, srv/salt/ceph/processes/mon/init.sls, srv/salt/ceph/processes/openattic/default.sls, srv/salt/ceph/processes/openattic/init.sls, srv/salt/ceph/processes/osd/default.sls, srv/salt/ceph/processes/osd/init.sls, srv/salt/ceph/processes/rgw/default.sls, srv/salt/ceph/processes/rgw/init.sls, srv/salt/ceph/restart/ganesha/lax/default.sls, srv/salt/ceph/restart/igw/lax/default.sls, srv/salt/ceph/restart/mds/lax/default.sls, srv/salt/ceph/restart/mgr/lax/default.sls, srv/salt/ceph/restart/mon/lax/default.sls, srv/salt/ceph/restart/openattic/lax/default.sls, srv/salt/ceph/restart/osd/lax/default.sls, srv/salt/ceph/restart/rgw/lax/default.sls
Fixes regression:
With https://github.com/SUSE/DeepSea/pull/841 we added restart of individual 'core' services right after the deployment finished. We tried to reduce the noise and crosschecks by targeting only the respective roles.
i.e. only target roles:mon  when you check for running services after restarting mons, instead of doing the full roundtrip and check services on all cluster nodes.
One problem in an initial deployment still persists. When you happen to have a node which holds two roles, one being a core (osd,mon,mgr) and the other being a non-core (i.e. rgw) cephprocesses.check performs on the node and checks for _all_ defined roles for that node. As you haven't executed stage.4 yet the rgw role is _defined_ for the node but not yet _deployed_ which is treated as a failure, …
=> allow indipendent service checks

srv/modules/runners/cephprocesses.py
the signature of cephprocesses.check is 
``` python
def check(results=False, quiet=False, **kwargs):
```
You can call 
``` shell
salt-call cephprocesses.check roles=['mon']
```
because salt converts this as kwargs anyways. If you do that in a module context like before the commit, the params will be just silently ignored and _all_ roles for the requested _search_ pattern are checked.
instead we have to do:
``` python
kwarg={'roles': [role]}
```
note that `kwarg` is the right syntax although the signature actually asks for kwargs ->  see the [docs](https://docs.saltstack.com/en/latest/ref/clients/#localclient)
=> pass role arg as kwargs to match process the requested role

srv/salt/ceph/monitoring/grafana/files/ceph-cluster.json
Display '0 s' instead of 'N/A' in the 'Average Monitor Latency' widget on the 'Ceph - Cluster' dashboard if no data exists.
=> Display '0 s' instead of 'N/A'

srv/salt/ceph/monitoring/grafana/files/ceph-rgw-users.json, srv/salt/ceph/monitoring/grafana/files/ceph-rgw.json, srv/salt/ceph/monitoring/prometheus/exporters/ceph_rgw_exporter/cron/default-disable-bucket-metrics.sls, srv/salt/ceph/monitoring/prometheus/exporters/ceph_rgw_exporter/files/ceph_rgw.py
Collect and display bucket statistics, e.g. actual size, utilized size and number of objects in Grafana.
This PR uses `radosgw-admin bucket stats` to collect bucket statistics like:
- Number of buckets
- Actual bucket size
- Utilized (compressed) bucket size
- Number of objects in bucket
The following widgets have been added in the 'Ceph - Object Gateway' dashboard:
- Top 10 - Buckets per user
- Top 10 - Bucket size
- Top 10 - Objects in bucket
The following widgets have been added in the 'Ceph - Object Gateway users' dashboard:
- Number of buckets
- Objects in bucket (Overall, per bucket)
- Bucket size (Overall, per bucket)
Additionally the very expensive metrics collected via 'radosgw-admin usage show' have been completely removed.
The following widgets have been removed in the 'Ceph - …
=> Refactor Prometheus RGW exporter

srv/salt/ceph/monitoring/grafana/files/ceph-cluster.json
backport of #869 
(cherry picked from commit 8423ebcb0578d91e3769281ad29a47fe9453f123)
=> [backport] Display '0 s' instead of 'N/A' 

qa/common/rbd.sh
Needed to fix the RBD tests in the CI.
=> qa: use correct path to rbd.conf custom configuration file

qa/common/rbd.sh
=> [SES5] qa: use correct path to rbd.conf custom configuration file

qa/common/common.sh, qa/common/json.sh, qa/suites/basic/health-igw.sh, qa/suites/basic/health-mds.sh, qa/suites/basic/health-nfs-ganesha.sh, qa/suites/basic/health-openattic.sh, qa/suites/ceph-test/pynfs.sh
Without this, Stage 4 creates certain pools with pg_num 128, often causing tests to fail because of too many, or too few, PGs per OSD.
Backport PR is #909
=> qa: pre-create pools before running Stage 4

Makefile, deepsea.spec.in, srv/modules/runners/benchmark.py, srv/modules/runners/populate.py, srv/pillar/ceph/benchmarks/collections/default.yml, srv/pillar/ceph/benchmarks/fio/blockdev_krbd.yml, srv/pillar/ceph/benchmarks/templates/blockdev_krbd.j2, srv/salt/_modules/cephprocesses.py, srv/salt/ceph/benchmarks/blockdev.sls, srv/salt/ceph/benchmarks/blockdev/cleanup_clients.sls, srv/salt/ceph/benchmarks/blockdev/prepare_clients.sls, srv/salt/ceph/benchmarks/blockdev/prepare_master.sls
@jan--f you probably have something to say about the srv/salt/ceph/benchmarks/blockdev/ path usage ;-) . I still think it makes sense to nest all of the benchmark backend files under the parent _benchmarks_ path, would you be open to using separate subdirectories per module here?
=> Block device benchmark module

srv/salt/ceph/stage/prep/master/default-no-update-no-reboot.sls, srv/salt/ceph/stage/prep/master/default-no-update-reboot.sls, srv/salt/ceph/stage/prep/master/default-update-no-reboot.sls, srv/salt/ceph/stage/prep/master/default.sls
This appears to be a regression introduced by
9f450a2ebe4caf56412128c9465ef4097ee51339 which was merged via
https://github.com/SUSE/DeepSea/pull/718 on October 6, 2017.
If salt-api is deployed before syncing modules, Stage 0 fails with:
Rendering SLS 'base:ceph.salt-api.configure' failed: Jinja variable
'salt.utils.templates.AliasedLoader object' has no attribute 'deepsea.user'
Fixes: https://github.com/SUSE/DeepSea/issues/914
Signed-off-by: Denis Kondratenko <denis.kondratenko@suse.com>
=> Sync modules before deploying salt-api

Makefile, deepsea.spec.in, srv/modules/runners/populate.py, srv/salt/ceph/rescind/time/chrony/default.sls, srv/salt/ceph/rescind/time/chrony/init.sls, srv/salt/ceph/rescind/time/default.sls, srv/salt/ceph/rescind/time/init.sls, srv/salt/ceph/rescind/time/ntp/default.sls, srv/salt/ceph/rescind/time/ntp/init.sls, srv/salt/ceph/time/README, srv/salt/ceph/time/chrony/default.sls, srv/salt/ceph/time/chrony/files/chrony.conf.j2, srv/salt/ceph/time/chrony/init.sls, srv/salt/ceph/time/default.sls, srv/salt/ceph/time/ntp/default.sls
Same strategy as ntp setup.  DeepSea only handles client configuration.  Available commands are
```
salt '*' state.apply ceph.time
salt '*' state.apply ceph.time.chrony
salt '*' state.apply ceph.time.ntp
```
```
salt '*' state.apply ceph.rescind.time
salt '*' state.apply ceph.rescind.time.chrony
salt '*' state.apply ceph.rescind.time.ntp
```
The default for a fresh install is chrony.  This will work with ntpd or chronyd as a server.  (Be sure to add the 'allow' directive for chronyd to listen on port 123.)
Chrony supports immediately sync'ing, so no separate step needed.  The Salt commands are plain enough that I am hopeful these will work on other distros without exceptions.  The rescind functionality cannot be part of Stage 5 or the purge orchestration.  
Existing installations can …
=> Support chrony, set as default, add rescind

qa/common/helper.sh
Hostnames are ordered randomly and it causes failures when e.g. test tries to umount nfs on node4 while priously was nfs mounted on master
```
Testing NFS-Ganesha with NFS version ->3<-
master.openqa.de:
- master
- admin
- mon
- mgr
- mds
- ganesha
master.openqa.de:
----------
master.openqa.de:
----------
/tmp/test-nfs-ganesha.sh:
True
master.openqa.de:
+ trap 'echo "Result: NOT_OK"' ERR
+ echo 'nfs-ganesha mount test script'
nfs-ganesha mount test script
+ test '!' -e /root/mnt
+ mkdir /root/mnt
+ test -d /root/mnt
+ mount -t nfs -o sync,nfsvers=3 master.openqa.de:/ /root/mnt
+ ls -lR /root/mnt
/root/mnt:
total 0
+ echo 'Result: OK'
Result: OK
node4.openqa.de:
----------
/tmp/test-nfs-ganesha-write.sh:
True
ERROR: Minions returned with non-zero exit code
node4.openqa.de:
+ trap 'echo …
```
=> Avoid random _client_node name

Makefile
Fixes: https://github.com/SUSE/DeepSea/issues/949
Signed-off-by: David Disseldorp <ddiss@suse.de>
=> Makefile: install benchmark-blockdev rescind stubs

Makefile, deepsea.spec.in, srv/modules/runners/benchmark.py, srv/modules/runners/populate.py, srv/pillar/ceph/benchmarks/collections/default.yml, srv/salt/_modules/cephprocesses.py, srv/salt/ceph/benchmarks/fs.sls, srv/salt/ceph/benchmarks/fs/cleanup.sls, srv/salt/ceph/benchmarks/fs/prepare_clients.sls, srv/salt/ceph/benchmarks/fs/prepare_master.sls, srv/salt/ceph/rescind/benchmark-fs/default.sls, srv/salt/ceph/rescind/benchmark-fs/init.sls
changes since v1 (https://github.com/SUSE/DeepSea/pull/933):
- add rescind stubs
This functionality triggers fio, using a local path as destination
(work_dir), with the assumption that work_dir has already been mounted.
In future, this functionality will be inherited by CephFS and SMB/CIFS
benchmark backends.
Signed-off-by: David Disseldorp <ddiss@suse.de>
=> benchmarks/fs: add generic filesystem benchmark

qa/common/helper.sh
Backport of #939
Hostnames are ordered randomly and it causes failures when
e.g. test tries to umount nfs on node4 while priously was nfs mounted on master
(cherry picked from commit 2a70b84344e3f7bd9773b222b8096a7ab9439a33)
=> [backport][SES5] Avoid random _client_node name

srv/salt/ceph/monitoring/prometheus/exporters/node_exporter.sls, srv/salt/ceph/monitoring/prometheus/exporters/node_exporter_package.sls, srv/salt/ceph/stage/configure/default.sls
This is needed so the jinja if statement in node_exporter.sls is
executed after the package was installed.
Fixes: #981
=> monitoring: move node_exporter install to its own sls

deepsea.spec.in
Partly addresses #993 by moving the abi requirement.  Also, I think the requires communicate a bit better to anyone wanting to understand the dependency differences between the Salt portions and the cli.
Also, I do not know if I have the best wording for the cli description.
=> Create cli subpackage

srv/salt/ceph/time/chrony/files/chrony.conf.j2
The 1 second default is too large for Ceph.  Trying 1/10th.
While experimenting with the qa suite, Ceph complained about a clock skew.  Restarting chrony  had no effect because the time difference was 120ms.
=> Tuning Chrony

Makefile
Description:
'make rpm' is broken.
Reproducer:
rm setup.py (that is carried over from older branches)
make rpm
> 
> raise tox.exception.MissingFile(setup)
> tox.MissingFile: MissingFile: /home/jxs/projects/deepsea/setup.py
> make: *** [Makefile:787: test] Error 1
>
=> Copy the generated setup.py back to the builddir in order to make tox happy

deepsea.spec.in, qa/common/common.sh, qa/common/nfs-ganesha.sh, qa/common/rgw.sh
Fixes: https://github.com/SUSE/DeepSea/issues/977
(This fixes the problem to the extent that it occurs in the test code. It does not help when zypper is being run by `pkg.installed` calls within DeepSea orchestrations.)
=> qa: run zypper refresh in try/wait loop

qa/common/common.sh, qa/suites/ceph-test/fs_to_bs_migration.sh
New QA test case for testing migration from filestore to bluestore:
- Disabled restart in stage 0
- Cluster deployed with filestore OSDs
- Then migration run with DS command ceph.migrate.osds
- No services deployed, not special settings for OSDs
New functions added to common.sh :
- configure_OSD_to_filestore
- check_OSD_type
- migrate_to_bluestore
- disable_restart_in_stage_0
=> QA test  - migration from filestore to bluestore

srv/modules/runners/select.py
This allows a minion list to be formatted with e.g. a port number or a
path.
=> select runner: add format option to get a formatted list of minions

srv/modules/runners/populate.py
This removes the assumption in the engulfer that there can be no more
than one public or cluster network.  Without this change, running engulf
on a cluster with (e.g.) public_network = 10.27.21.0/24, 10.27.20.0/24
will result in the following error:
[ERROR   ] Failed to determine cluster's public_network.
[ERROR   ] Failed to replace derived public_network with public_network
of existing cluster.
Note that this still leaves the public_network and cluster_network settings
as strings in the pillar data (changing the pillar data to be an array would
have been somewhat more invasive).
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1076010
Fixes: https://github.com/SUSE/DeepSea/issues/582
(cherry picked from commit …
=> [backport][SES5]populate: support multiple public, cluster networks in engulf (bsc#1076010)

qa/common/common.sh, qa/suites/basic/health-ok.sh, qa/suites/basic/health-rgw.sh
In addition to the backported commits from master, this PR includes a SES5-only commit to fix the "too few PGs" issue in health-rgw.sh.
=> [backport][SES5] qa: rados_write_test

srv/modules/runners/proposal.py, srv/salt/ceph/stage/discovery/default-nvme.sls
The proposal runner handles kwargs, but Salt is passing the kwargs dict
as a keyword 'kwargs'.  This change allows Stage 1 to be part of the
process rather than requiring manual discovery.
=> Support kwargs in orchestrations

srv/modules/runners/ready.py
aa-status is the actual executable, apparmor-status just a link to it.
has potential to be SUSE specific or change in the future.
=> runner/ready: use aa-status instead of apparmor-status

Makefile, deepsea.spec.in, srv/salt/ceph/monitoring/prometheus/exporters/ceph_rgw_exporter/CentOS/default-install.sls, srv/salt/ceph/monitoring/prometheus/exporters/ceph_rgw_exporter/CentOS/default.sls, srv/salt/ceph/monitoring/prometheus/exporters/ceph_rgw_exporter/CentOS/init.sls, srv/salt/ceph/monitoring/prometheus/exporters/ceph_rgw_exporter/SLES-15/default-install.sls, srv/salt/ceph/monitoring/prometheus/exporters/ceph_rgw_exporter/SLES-15/default.sls, srv/salt/ceph/monitoring/prometheus/exporters/ceph_rgw_exporter/SLES-15/init.sls, srv/salt/ceph/monitoring/prometheus/exporters/ceph_rgw_exporter/default-exporter.sls, srv/salt/ceph/monitoring/prometheus/exporters/ceph_rgw_exporter/default-install.sls, srv/salt/ceph/monitoring/prometheus/exporters/ceph_rgw_exporter/default.sls, srv/salt/ceph/monitoring/prometheus/exporters/ceph_rgw_exporter/init.sls
Description:
SLE-15 changed package name, implement distro init.sls
This addresses the same issue as #1010, but using the #998 approach.  I ran into the same problem #1009 but thought this would work as an ideal example since the original change is minor.
The default is still python-prometheus-client, but CentOS and SLES-15 have specific package names.  All three share default-exporter logic, so no duplicate code.  I think this is about as ideal as it gets for refactoring a configuration into DRY setup that is fairly obvious.
=> refactor ceph_rgw_exporter

srv/salt/_modules/osd.py, srv/salt/_modules/proposal.py, tests/unit/_modules/test_osd.py
Many symlinks in /dev/disk/by-id match a single device, but the most
useful for the administrator has the best description.
Intentional code duplication to not conflate issues.
Fixes #952
=> Prefer underscore device names

srv/salt/_modules/cephinspector.py
The find command may return multiple symlinks, but only one is needed.
SUSE internal: bnc#1080102
=> Return a single device

srv/modules/runners/filequeue.py
Use functions since `__func_alias__`  cannot support two aliases for the
same key.
=> Add push,add back to filequeue

srv/modules/runners/proposal.py, srv/salt/ceph/stage/discovery/default-nvme.sls
The proposal runner handles kwargs, but Salt is passing the kwargs dict
as a keyword 'kwargs'.  This change allows Stage 1 to be part of the
process rather than requiring manual discovery.
(cherry picked from commit aff143dc5a4f38893b0cee6688530c466cb389d1)
backport of #1023 
=> [backport][SES5] Support kwargs in orchestrations

Makefile, deepsea.spec.in, srv/salt/_modules/osd.py, srv/salt/ceph/redeploy/nodes/default-10m.sls, srv/salt/ceph/redeploy/osds/default-10m.sls, srv/salt/ceph/smoketests/quiescent/init.sls, srv/salt/ceph/tests/quiescent/init.sls, srv/salt/ceph/tests/quiescent/timeout/init.sls, tests/unit/_modules/test_osd.py
Before removing an OSD, ensure that all PGs are active+clean.
Includes unit and functional tests.
(cherry picked from commit 678becc)
(cherry picked from commit dd688e1)
backport of #1026 
_**!Review with caution. Lots of conflicts!**_
=> [backport][SES5] Add active+clean wait for migrations 

srv/salt/_modules/cephinspector.py
The find command may return multiple symlinks, but only one is needed.
(cherry picked from commit 8131286dc4be3fa0a3204febd5bd47315b2aeb08)
backport of #1049 
=> [backport][SES5] Return a single device

srv/salt/_modules/osd.py, srv/salt/_modules/proposal.py, tests/unit/_modules/test_osd.py
Many symlinks in /dev/disk/by-id match a single device, but the most
useful for the administrator has the best description.
Intentional code duplication to not conflate issues.
(cherry picked from commit a0168a10092c906f20b9516a1b3dfcc4eb691e3d)
backport of #1061 
**conflicts, review with caution** 
=> [backport][SES5] Prefer underscore device names

srv/salt/ceph/mds/pools/default.sls
While we do not have a magic calculator for pools yet to be created,
changing the defaults will help convey to administrators the expected
ratio when increasing the PGs.
Fixes #887
=> Change PG ratio to 4:1

srv/salt/ceph/igw/files/lrbd.conf.j2
If the pool and image exist, generate a full lrbd.conf.  When neither
exists, use the minimal configuration.
=> Correct conditional

qa/suites/basic/health-ok.sh
Commit ea7af31f0 added a --mini option to health-ok.sh, but it was
not possible to use because it was not added to the getopt command.
=> [backport][SES5] qa: health-ok: fix --mini option

srv/salt/ceph/configuration/create/default.sls, srv/salt/ceph/ganesha/auth/default.sls, srv/salt/ceph/ganesha/config/default.sls, srv/salt/ceph/ganesha/key/default.sls, srv/salt/ceph/igw/auth/default.sls, srv/salt/ceph/igw/config/default.sls, srv/salt/ceph/igw/key/default.sls, srv/salt/ceph/mds/auth/default.sls, srv/salt/ceph/mds/key/default.sls, srv/salt/ceph/mds/pools/default.sls, srv/salt/ceph/mgr/auth/default.sls, srv/salt/ceph/mgr/key/default.sls, srv/salt/ceph/monitoring/default.sls, srv/salt/ceph/monitoring/grafana/init.sls, srv/salt/ceph/monitoring/prometheus/update_service_discovery.sls, srv/salt/ceph/remove/ganesha/default.sls, srv/salt/ceph/remove/mds/default.sls, srv/salt/ceph/remove/mgr/default.sls, srv/salt/ceph/remove/migrated/default.sls, srv/salt/ceph/remove/mon/default.sls, srv/salt/ceph/remove/openattic/default.sls, srv/salt/ceph/remove/rgw/default.sls, srv/salt/ceph/remove/storage/default.sls, srv/salt/ceph/rgw/auth/default.sls, srv/salt/ceph/rgw/key/default.sls
Any state file including Jinja templates that call a salt runner
indirectly creates a Salt job owned by root.  Dropping privileges in the
runner will break the state.  This kludge will keep the Salt cron
equivalent from crashing with a permissions exception.
Fixes #935, #1004
=> Correct permissions on job cache

deepsea.spec.in
OBS build error:
```
[   63s] deepsea-qa-0.8.4+git.0.e7e325073-2.15.1.noarch.rpm: directories not owned by a package:
[   63s]  - /srv/salt/ceph/smoketests
[   63s]  - /srv/salt/ceph/tests
```
after moving on par with master and merging: 3310c127891c7e046a6e4666de67156516184318 SES5 needs to be adapted as keyringstests have not been backported
=> [SES5] Add missing directories to deepsea-qa package

tox.ini
`lint` virtualenv defaults to python2 on travis but can default to python3 (e.g. on Tumbleweed). That is a problem for two reasons: the first problem is the lack of consistency between travis and dev setups, the second is that `make lint` does not work with python3 properly.
This change forces a python2 virtualenv to ensure the same `pylint` is used locally and on travis.
I also fixed the broken tox documentation URL.
=> force python2 virtualenv for pylint

srv/modules/runners/validate.py
Calling master modules in runners evaluated in Jinja causes states to
fail in later orchestrations.
=> Correct master_minion check

srv/salt/ceph/monitoring/prometheus/files/prometheus.yml.j2
The master.minion module is not available in Jinja templates.  Since
prometheus is undergoing a reimplementation as a role, use the
/etc/salt/minion_id directly as a stop gap.
Fixes #1112
=> Fix template

srv/salt/ceph/mon/key/default.sls, srv/salt/ceph/stage/configure/default.sls
Mimic monitors generate their own keyring.  Continue to use the DeepSea
generated keyring to allow others to be unblocked.
=> Add osd bootstrap keyring to monitor creation keyring

Makefile, deepsea.spec.in, srv/salt/ceph/macros/os_switch.sls, srv/salt/ceph/monitoring/prometheus/exporters/ceph_rgw_exporter/init.sls
An attempt to simplify the new dist switch mechnism introduced in #1016.
Any init.sls can do the import from ```ceph.foo.sls``` (name pending) which should greatly simplify the swithching proposed in #1016. The rest works as before...if a distro specific path is present it is taken. fallback is default.
I think this makes it less painfull to roll out throughout deepsea.
=> [DNM] [RFC] use jinja macros for simpler dist switch in init.sls

srv/salt/_modules/cephprocesses.py
(cherry picked from commit 5e40503ee0edd0cfe321a715d3537f3280179bdc)
backport of #1099 
=> [backport][SES5] Add missing role to cephprocesses map

srv/salt/_modules/helper.py
Change ascii to default since 'activate' uses characters outside of
ascii.
=> Fix stderr to be stderr

srv/salt/ceph/maintenance/upgrade/cleanup/default.sls, srv/salt/ceph/stage/configure/default.sls
This is a partial reversion of https://github.com/SUSE/DeepSea/pull/1101.
Since that commit, there's been a problem running ceph.stage.2, where the
first time you run it, the mon, osd, admin and openattic keys are created,
but mgr, rgw, and any other role-based keys are not created until you
run ceph.stage.2 a *second* time.
It turns out that refresh_pillar1 in configure/default.sls was previously
targeting all minions, which updated all roles in the pillar data correctly.
PR #1101 changed this to only target the master, which means only the roles
for the master were present in the pillar data, not the roles for any other
nodes, which caused select.minions in the various role-based key state files
to return nothing.  By some sort of miracle, applying …
=> Fix initial mgr keyring creation failure in ceph.stage.2

qa/common/rbd.sh
Before, we were relying on teuthology's install task to install the ceph-test
package. We (recently) turned that behavior off and began relying on DeepSea's
Stage 0 to install the ceph RPMs, but that doesn't install ceph-test.
Fixes: https://github.com/SUSE/DeepSea/issues/1124
=> qa: ensure ceph-test RPM is installed

srv/salt/ceph/smoketests/init.sls, srv/salt/ceph/smoketests/restart/common.sls
Depended on: https://github.com/SUSE/DeepSea/pull/1133
Description:
Instead of running:
```
salt-run state.orch ceph.smoketest.restart.mds
salt-run state.orch ceph.smoketest.restart.mgr
salt-run state.orch ceph.smoketest.restart.mon
salt-run state.orch ceph.smoketest.restart.rgw
salt-run state.orch ceph.smoketest.quiescient
salt-run state.orch ceph.smoketest.keyrings
```
this patch allows you to do:
```
salt-run state.orch ceph.smoketest
```
in case you want to run _all_ tests
=> be able to run condensed smoketests

qa/common/rbd.sh
Before, we were relying on teuthology's install task to install the ceph-test
package. We (recently) turned that behavior off and began relying on DeepSea's
Stage 0 to install the ceph RPMs, but that doesn't install ceph-test.
Fixes: https://github.com/SUSE/DeepSea/issues/1124
(cherry picked from commit f1921eabb9b55496ce0f0126703881dec737dc23)
backport of #1125 
=> [backport][SES5] qa: ensure ceph-test RPM is installed

Makefile, deepsea.spec.in, srv/salt/ceph/smoketests/restart/common.sls
Pr that introduced smoketests: https://github.com/SUSE/DeepSea/pull/1054
Description:
If you try to run the smoketests.restart you get the following error:
```
mon1.ceph:
Data failed to compile:
----------
No matching sls found for 'ceph.tests.restart.mds.forced' in env 'base'
Summary for admin.ceph_master
------------
Succeeded: 2 (changed=2)
Failed:    1
```
Which is due to the missing directives in the spec/makefile for the subdirectories under `ceph/test/restart/$role`
=> Add ceph/test/restart/$role sub-directories to make/spec files

Makefile
Fixes:
Fix the Makefile for Fedora.
**Description**:
`cd DeepSea && make install` does not work on Fedora.
```              stderr:
make: python3-setuptools: Command not found
make: *** [Makefile:795: install-deps] Error 127
stdout:
#make sure to create bytecode with the correct version
find srv/ -name '*.py' -exec python3 -m py_compile {} \;
find cli/ -name '*.py' -exec python3 -m py_compile {} \;
python3-setuptools python3-click
```
And `make test` fails.
```
$ sudo make test
tox -e py27
make: tox: Command not found
make: *** [Makefile:830: test] Error 127
```
**version**:
```
$ cat /etc/os-release 
NAME=Fedora
VERSION="27 (Workstation Edition)"
ID=fedora
...
```
**Testing ***
Verified on Fedora 27: See : [junit-py27.out.txt](https://github.com/SUSE/DeepSea/files/1989904/junit-py27.out.t …
=> Fix Makefile on Fedora

Makefile, deepsea.spec.in, srv/salt/ceph/macros/os_switch.sls, srv/salt/ceph/smoketests/init.sls, srv/salt/ceph/smoketests/macros/os_switch/init.sls, srv/salt/ceph/tests/os_switch/init.sls
Before we were using file.file_exists with an absolute path, that is
only valid on the master. As a result we'd get different results on the
master vs. a minion. This relies on salts caching mechanism and works
reliably on all minions.
=> macros: fix os_switch macro to work on minions.

srv/modules/runners/net.py
Fixes #
Description: Converting commented out prints to logs was listed as a TODO
=> Convert commented out print statements to log.debug

.coveragerc, tox.ini
Description:
Ricardo used this in his PR #1149. Nice addon, we might want to have that too.
We still have to re-add the travis checks via the new 'checks api'. Issue for this is here: (#1128)
=> Add py-coverage

srv/salt/_modules/multi.py
Remove bare except clause. If MatchObject is
None the group method will raise an AttributeError
in both py2 and py3
Description:
=> Catch only one exception

.pylintrc, .travis.yml, srv/modules/runners/cephprocesses.py, srv/modules/runners/changed.py, srv/modules/runners/disengage.py, srv/modules/runners/filequeue.py, srv/modules/runners/proposal.py, srv/modules/runners/push.py, srv/modules/runners/select.py, srv/modules/runners/status.py, srv/modules/runners/ui_ganesha.py, srv/modules/runners/ui_iscsi.py, srv/modules/runners/validate.py, srv/salt/_modules/cephdisks.py, srv/salt/_modules/fs.py, srv/salt/_modules/kernel.py, srv/salt/_modules/keyring.py, srv/salt/_modules/multi.py, srv/salt/_modules/osd.py, srv/salt/_modules/packagemanager.py, srv/salt/_modules/purge.py, srv/salt/_modules/rgw.py, tests/unit/_modules/test_cephdisks.py, tox.ini
This is the follow up on https://github.com/SUSE/DeepSea/pull/1110 which migrates the lint environment from python2 to python3. This change introduced new messages, most reports were about `return` statements. 
I got rid of implicit `return None`s and extracted `return` statements from `if-else` branches where it made sense to me. I also refactored some code (e.g. `_hw_raid_ctrl_detection` in cephdisks.py [0]) and the unittests are all passing, but please double check that I did not introduce new bugs.
---
[0] - https://github.com/alexandergraul/DeepSea/blob/2cf5c74c7b2f1e44dc652a8ead8b78e682f2a8e0/srv/salt/_modules/cephdisks.py#L185
=> migrate linter to python3

srv/modules/runners/validate.py
Description:
Previously a ValueError was expected but if salt-api is disabled,
an IndexError is raised.
=> Fix salt-api validation

srv/modules/runners/validate.py
Description:
Previously a ValueError was expected but if salt-api is disabled,
an IndexError is raised.
(cherry picked from commit 8c6fed8a5b62d57130932dc06343a38b886a675b)
Backport of #1155
=> [Backport] [SES5] Fix salt-api validation

srv/salt/ceph/configuration/create/default.sls, srv/salt/ceph/ganesha/auth/default.sls, srv/salt/ceph/ganesha/config/default.sls, srv/salt/ceph/ganesha/key/default.sls, srv/salt/ceph/igw/auth/default.sls, srv/salt/ceph/igw/config/default.sls, srv/salt/ceph/igw/key/default.sls, srv/salt/ceph/mds/auth/default.sls, srv/salt/ceph/mds/key/default.sls, srv/salt/ceph/mds/pools/default.sls, srv/salt/ceph/mgr/auth/default.sls, srv/salt/ceph/mgr/key/default.sls, srv/salt/ceph/monitoring/default.sls, srv/salt/ceph/remove/ganesha/default.sls, srv/salt/ceph/remove/mds/default.sls, srv/salt/ceph/remove/mgr/default.sls, srv/salt/ceph/remove/migrated/default.sls, srv/salt/ceph/remove/mon/default.sls, srv/salt/ceph/remove/openattic/default.sls, srv/salt/ceph/remove/rgw/default.sls, srv/salt/ceph/remove/storage/default.sls, srv/salt/ceph/rgw/auth/default.sls, srv/salt/ceph/rgw/key/default.sls
When there's a lot of files in the salt job cache, using salt's
builtin file.directory construct is remarkably slow.  Let's start
with about 10,000 files in the cache, all correctly owned:
````
9920
0
````
Then, run ceph.stage.2:
````
[...]
Summary for admin.ceph_master
-------------
Succeeded: 14 (changed=10)
Failed:     0
-------------
Total states run:     14
Total run time:  409.141 s
````
That's 409 seconds, or a bit under seven minutes.  Now, with this
change applied, which instead invokes `find ... -exec chown ...`,
it only takes a minute twenty, which is quite a bit better:
````
[...]
Summary for admin.ceph_master
-------------
Succeeded: 14 (changed=10)
Failed:     0
-------------
Total states run:     14
Total run time:   82.443 s
````
Fixes: …
=> Invoke `find` to fix salt job cache permissions

.codecov.yml, tox.ini
Description:
Codecov uses code coverage generated by pytest-cov and generates stats
and rich diffs for PRs.
Before we can use this, two things have to happen:
1. We need to discuss the numbers (how much % drop do we allow before the check fails) [[docs](https://docs.codecov.io/docs/commit-status)]
2. Someone with admin rights needs to enable [Travis](https://github.com/marketplace/travis-ci/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW43MA==#pricing-and-setupl) (see #1128) and [Codecov](https://github.com/marketplace/codecov/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW4xNg==#pricing-and-setup)
=> Add codecov integration to Travis CI

.codecov.yml
Description:
Comments only show diff and checks are non-blocking.
An example of this config in action can be see at  https://github.com/alexandergraul/DeepSea/pull/8
=> Correct codecov config

Makefile
Fixes #
```
$ sudo make install 
...
...
systemctl restart salt-master
Failed to restart salt-master.service: Unit salt-master.service not found.
make: *** [Makefile:806: install] Error 5
```
Description:
The service `salt-master` may be absent before `salt-api` package gets installed.  Once `salt-api` is installed the `salt-master.service` will definitely exist.  This PR handles the scenario to ensure `salt-master.service` is running and `make install` completes successfully.
Testing: [junit-py27.out.txt](https://github.com/SUSE/DeepSea/files/1996911/junit-py27.out.txt)
=> Make salt-api an explicit 'make install' dependency

cli/common.py
Description:
It appears that in some terminals the `sys.stdout.encoding` returns `None`. This PR fixes the utf-8 support detector for this scenario.
=> cli: common: fix terminal utf-8 support detector

Makefile, deepsea.spec, srv/salt/ceph/metapackage/default.sls, srv/salt/ceph/metapackage/init.sls, srv/salt/ceph/packages/common/default.sls, srv/salt/ceph/stage/prep/master/default.sls
original PR #1160 
This cannot be applied onto SES4 due to alot of structural changes in SES5/master. Trying to do adaptive changes to SES4.
Here, we don't need the metapackage to be installed explicitly on the minions as we do call ceph.packages.common before the update.
=> [backport][SES4] Implement meta package code on SES4

tox.ini
salt2018 was pushed onto pip just recently and is somehow messed up.
As SES5 is using salt2016 anyways this is good idea.
=> Force SES5's tox to use salt<2017.0.0

tox.ini
=> Let tox use salt2016 until the pip packages in pypi are sane again

Makefile, deepsea.spec.in, srv/modules/utils/ready.py, srv/salt/ceph/apparmor/default-complain.sls, srv/salt/ceph/apparmor/default-disable.sls, srv/salt/ceph/apparmor/default-enforce.sls, srv/salt/ceph/apparmor/default.sls, srv/salt/ceph/apparmor/files/ceph.d/common, srv/salt/ceph/apparmor/files/usr.bin.ceph-mds, srv/salt/ceph/apparmor/files/usr.bin.ceph-mgr, srv/salt/ceph/apparmor/files/usr.bin.ceph-mon, srv/salt/ceph/apparmor/files/usr.bin.ceph-osd, srv/salt/ceph/apparmor/files/usr.bin.radosgw, srv/salt/ceph/apparmor/files/usr.sbin.httpd-prefork, srv/salt/ceph/apparmor/files/usr.sbin.oaconfig, srv/salt/ceph/apparmor/init.sls, srv/salt/ceph/apparmor/install/SUSE.sls, srv/salt/ceph/apparmor/install/default.sls, srv/salt/ceph/apparmor/install/init.sls, srv/salt/ceph/apparmor/profiles.sls, srv/salt/ceph/smoketests/apparmor/init.sls, srv/salt/ceph/smoketests/init.sls
Fixes #937 
Description:
Adds initial apparmor support. By default nothing is done. Setting one of those three pillar variables below installs apparmor, starts the service, pushes the profiles and puts them in the respective mode:
```
apparmor_init: default-enforce
apparmor_init: default-complain
apparmor_init: default-disable
```
I guess we could add this to stage 0 (not yet implemented)?
=> apparmor: add initial profiles

srv/salt/ceph/mgr/default.sls, srv/salt/ceph/mon/default.sls, srv/salt/ceph/stage/deploy/default.sls
`service.running` will start and enable the service, which is nice, but it reports the service as up and running even if it fails, e.g., 0.5 seconds after being started.
Add a small bash script that waits a short time and checks the service status, so we don't continue with a failed MGR.
Do the same with the MONs (and migrate them to `service.running`).
Also, restart the MGRs before the OSDs since the OSDs cannot start if MGRs are not running.
Fixes: https://github.com/SUSE/DeepSea/issues/1019
=> Stage 3: fail immediately if MONs or MGRs do not stay up after starting

Makefile, deepsea.spec.in
These should not have been merged.  Master is currently broken.  We can resolve the pycache issue in another change.
=> Add missing endif, remove __pycache__, add metapackage

srv/salt/_modules/osd.py, srv/salt/ceph/smoketests/quiescent/init.sls, srv/salt/ceph/tests/quiescent/check_pgs.sls, tests/unit/_modules/test_osd.py
Update smoketest to fail on empty cluster as well.
=> Support active+clean checks on empty clusters

Makefile
Fixes #
Do not handle salt packages in Makefile.   Reverses #1140 
Description:
I had issues with Salt 2018.3.1 so used Salt 2017.7.6 installed via`salt-bootstrap` script.  Later I ran `salt.highstate` which included DeepSea `cmd.run: make install` step and Salt was having weird errors.
```
2018-06-25 13:35:09,974 [salt.loader      :1718][ERROR   ][1369] Exception raised when processing __virtual__ function for salt.loaded.int.executor.sudo. Module will not be loaded: 'module' object has no attribute 'clean_kwargs'
2018-06-25 13:35:09,975 [salt.loader      :1736][WARNING ][1369] salt.loaded.int.executor.sudo.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'sudo', please fix this.
2018-06-25 …
```
=> don't install salt packages in Makefile (revert PR1140)

srv/modules/runners/populate.py
Fixes #1201
Description:
`uuid.py` does not understand utf-8 encoding.
Tested locally and resolves #1201 
```
$ sudo salt-run state.orch ceph.stage.discovery
[WARNING ] All minions are ready
[ERROR   ] Verify that targeted minions have proposal.generate
[ERROR   ] Verify that targeted minions have proposal.generate
[ERROR   ] Verify that targeted minions have proposal.generate
[ERROR   ] Verify that targeted minions have proposal.generate
[ERROR   ] Verify that targeted minions have proposal.generate
{u'*': {'data': 0,
'db-ratio': 5,
'db-size': '500m',
'encryption': '',
'format': 'bluestore',
'journal': 0,
'journal-size': '5g',
'leftovers': False, …
```
=> runners/populate.py: uuid.py only takes ascii

Makefile, deepsea.spec.in, srv/modules/runners/validate.py, srv/salt/ceph/stage/discovery/default-nvme.sls, srv/salt/ceph/stage/discovery/default.sls, srv/salt/ceph/stage/prep/master/default-no-update-no-reboot.sls, srv/salt/ceph/stage/prep/master/default-no-update-reboot.sls, srv/salt/ceph/stage/prep/master/default-update-no-reboot.sls, srv/salt/ceph/stage/prep/master/default.sls, srv/salt/ceph/stage/validate/default-nobypass.sls, srv/salt/ceph/stage/validate/default.sls, srv/salt/ceph/stage/validate/init.sls, tests/unit/runners/test_validate.py
Changed serial salt call to a single call.  Refactored as well.  Added
conditional bypass to skip checks on working clusters.
A new ci_validate.py runner still gives the original behavior but is part of
the qa package.
Fixes #1104
=> Fix ceph_version

srv/modules/runners/validate.py
Fixes # 1189
Description:
The _monitor_check method is not called in validate.py and needs to be removed.
=> Remove _monitor_check method

srv/modules/runners/validate.py
Fixes # similar to 1189
Description:
This is in a similar lane as an issue: 1189.
The method is there but the call is commented out and the doc string explains why:  "Originally here to stop the process, but commented out. Intend to remove since we have minions.ready"
=> Remove _minion_check since it is superceded my minions.ready

Makefile
Tox seems to need the setup.py file, which is not generated before running the test.
=> Generate setup.py file before running the tests

srv/modules/runners/proposal.py
This has the downside of not being able to dump python objects which
we don't really do in that case anyways.
SUSEInternal: bsc#1100136
=> Use safe_dump rather than dump

deepsea.spec.in
Fixes: https://github.com/SUSE/DeepSea/issues/1218
=> build/ops: add jq runtime dependency to spec file

tox.ini
Fixes #1224 
Description: enforces the working version of pylint (1.9) which is supported until 2020
=> enforce pylint version 1.9.x

Makefile, deepsea.spec.in
Top-level smoketests state file is not installed, either by Makefile or by spec file.
=> build/ops: install top-level smoketests state file

srv/salt/ceph/remove/storage/drain/default.sls
Description:
Stage.5 reports:
> drain osd.6: The following arguments are missing: osd_id
which comes from ` ceph.remove.storage.drain (/srv/salt/ceph/remove/storage/drain)`
~dd688e193~  was changing the func header but we missed to change that also in the sls files
EDIT: it was actually fa78d09df00d3197ecc6d084c186514e82569311
=> passed arg was not changed in sls file after changed in function header

srv/salt/ceph/apparmor/install/SUSE.sls
On SLE15 at least, installing "patterns-base-apparmor" does not cause
apparmor-utils to be installed, and apparmor/default-enforce.sls fails
due to missing executable "aa-enforce".
Fixes: https://github.com/SUSE/DeepSea/issues/1234
=> apparmor: install apparmor-utils package on SUSE

man/deepsea-commands.7, man/deepsea-customization.7, man/deepsea-mines.7, man/deepsea-stage-0.7, man/deepsea-stage-1.7, man/deepsea-stage-2.7, man/deepsea-stage-3.7, man/deepsea-stage-4.7, man/deepsea-stage-5.7
Adding 
- deepsea-stage-0 (7),
- deepsea-stage-1 (7), 
- deepsea-stage-2 (7),
- deepsea-stage-3 (7),
- deepsea-stage-4 (7),
- deepsea-stage-5 (7),
- deepsea-customization (7),
- deepsea-mines (7)
=>  Adding more information to the man pages

Makefile, qa/osd-config/ovh/README.md, qa/osd-config/ovh/bs_dedicated_db.yaml, qa/osd-config/ovh/bs_dedicated_db_crypt.yaml, qa/osd-config/ovh/bs_dedicated_db_sizes.yaml, qa/osd-config/ovh/bs_dedicated_db_sizes_crypt.yaml, qa/osd-config/ovh/bs_dedicated_db_sizes_mixed.yaml, qa/osd-config/ovh/bs_dedicated_db_sizes_mixed_crypt.yaml, qa/osd-config/ovh/bs_dedicated_wal.yaml, qa/osd-config/ovh/bs_dedicated_wal_crypt.yaml, qa/osd-config/ovh/bs_dedicated_wal_db.yaml, qa/osd-config/ovh/bs_dedicated_wal_db_crypt.yaml, qa/osd-config/ovh/bs_dedicated_wal_db_sizes_all.yaml, qa/osd-config/ovh/bs_dedicated_wal_db_sizes_all_crypt.yaml, qa/osd-config/ovh/bs_dedicated_wal_db_sizes_mixed.yaml, qa/osd-config/ovh/bs_dedicated_wal_db_sizes_mixed_crypt.yaml, qa/osd-config/ovh/bs_dedicated_wal_sizes.yaml, qa/osd-config/ovh/bs_dedicated_wal_sizes_crypt.yaml, qa/osd-config/ovh/bs_dedicated_wal_sizes_mixed.yaml, qa/osd-config/ovh/bs_dedicated_wal_sizes_mixed_crypt.yaml, qa/osd-config/ovh/fs_dedicated_journal.yaml, qa/osd-config/ovh/fs_dedicated_journal_crypt.yaml
Description:
This PR $subject in order to feed them to teuthology-ovh ( for now ). That enables us to test all the possible configurations we support with deepsea. 
=> qa: add all possible dummy osd-configurations

cli/monitors/terminal_outputter.py, cli/stage_parser.py, cli/tests/test_stage_parse.py
Fixes: #1243
Description:
This PR introduces the following changes to fix the problems reported in #1243 
* filter out test.nop states from the execution plan
* [init] step errors are not reported in the failure summary
=> cli: filter out test.nop steps and don't report [init] step errors

qa/common/common.sh, qa/common/helper.sh, qa/suites/basic/health-ok.sh
This adds coverage of `ceph.migrate.subvolume` to the CI.
(Or, rather, it would if our OpenStack images were using btrfs. . . which they aren't . . .)
Backporting note: cherry-pick 40a5177 only
=> qa/common: create btrfs subvolumes after Stage 0

srv/salt/ceph/rescind/tuned/default.sls
Without this, Stage 5 fails like so:
```
2018-07-29T01:59:30.330 INFO:teuthology.orchestra.run.target149202182148.stdout:[10/11] Executing state ceph.rescind.tuned...
2018-07-29T01:59:30.330 INFO:teuthology.orchestra.run.target149202182148.stdout:         target149202182148.teuthology... fail
2018-07-29T01:59:30.330 INFO:teuthology.orchestra.run.target149202182148.stdout:         target149202182016.teuthology... fail
2018-07-29T01:59:30.330 INFO:teuthology.orchestra.run.target149202182148.stdout:         target149202182123.teuthology... fail
2018-07-29T01:59:30.331 INFO:teuthology.orchestra.run.target149202182148.stdout:         target149202182166.teuthology... ok
2018-07-29T01:59:30.331 INFO:teuthology.orchestra.run.target149202182148.stdout:[11/11] Executing state …
```
=> rescind: prevent empty rendering of ceph.rescind.tuned state file

deepsea.spec.in
Merely mentioning the top-level directory is sufficient to bring in that
directory and everything under it.
This is a Big Stick, and not to be used lightly, but since (a) the deepsea-qa
package is not intended for wide consumption and (b) the directories in
question contain only QA-related stuff, it seems OK to use here.
=> build/ops: streamline qa %files section

deepsea.spec.in
Fixes: https://github.com/SUSE/DeepSea/issues/1218
(cherry picked from commit adca7b300ad4d1f6b15757bb7f2559799f2fd8e0)
=> [backport][ses5] build/ops: add jq runtime dependency to spec file

srv/salt/ceph/configuration/create/default.sls, srv/salt/ceph/ganesha/auth/default.sls, srv/salt/ceph/ganesha/config/default.sls, srv/salt/ceph/ganesha/key/default.sls, srv/salt/ceph/igw/auth/default.sls, srv/salt/ceph/igw/config/default.sls, srv/salt/ceph/igw/key/default.sls, srv/salt/ceph/mds/auth/default.sls, srv/salt/ceph/mds/key/default.sls, srv/salt/ceph/mds/pools/default.sls, srv/salt/ceph/mgr/auth/default.sls, srv/salt/ceph/mgr/key/default.sls, srv/salt/ceph/monitoring/default.sls, srv/salt/ceph/remove/ganesha/default.sls, srv/salt/ceph/remove/mds/default.sls, srv/salt/ceph/remove/mgr/default.sls, srv/salt/ceph/remove/migrated/default.sls, srv/salt/ceph/remove/mon/default.sls, srv/salt/ceph/remove/openattic/default.sls, srv/salt/ceph/remove/rgw/default.sls, srv/salt/ceph/remove/storage/default.sls, srv/salt/ceph/rgw/auth/default.sls, srv/salt/ceph/rgw/key/default.sls
```
When there's a lot of files in the salt job cache, using salt's
builtin file.directory construct is remarkably slow.  Let's start
with about 10,000 files in the cache, all correctly owned:
9920
0
Then, run ceph.stage.2:
[...]
Summary for admin.ceph_master
-------------
Succeeded: 14 (changed=10)
Failed:     0
-------------
Total states run:     14
Total run time:  409.141 s
That's 409 seconds, or a bit under seven minutes.  Now, with this
change applied, which instead invokes `find ... -exec chown ...`,
it only takes a minute twenty, which is quite a bit better:
[...]
Summary for admin.ceph_master
-------------
Succeeded: 14 (changed=10)
Failed:     0
-------------
Total states run:     14
Total run time:   82.443 s
Fixes: https://github.com/SUSE/DeepSea/issues/1131
Signed-off-by: Tim …
```
=> [backport][SES5] Invoke `find` to fix salt job cache permissions

qa/common/deploy.sh
When installing DeepSea from packages, the "deepsea-cli" package might
not get installed (it is not strictly required), and depending on which tests
are being run, the absence of the CLI might not be a problem.
In any case, there is no reason why failure of "deepsea --version" should
fail the entire test.
Fixes #
Description:
**Checklist:**
=> qa/deploy: handle possibility that deepsea-cli is not installed

qa/common/helper.sh
Fixes #1282
Description:
Fixes a case where CI tests fail bogusly.
**Checklist:**
=> qa:  common/helper: storage-only node might be master node 

srv/modules/runners/populate.py
Engulf shouldn't create policy.cfg lines referencing role-mon yml files,
as these are no longer created since the following commits:
- https://github.com/SUSE/DeepSea/commit/59123bbf (master)
- https://github.com/SUSE/DeepSea/commit/87ffece9 (SES5)
=> populate: don't create role-mon yml line during engulf (bsc#1104781)

srv/modules/runners/populate.py
Backport of #1292 
Engulf shouldn't create policy.cfg lines referencing role-mon yml files,
as these are no longer created since the following commits:
- https://github.com/SUSE/DeepSea/commit/59123bbf (master)
- https://github.com/SUSE/DeepSea/commit/87ffece9 (SES5)
(cherry picked from commit d1d1176fb910ee98157ce9769578eb913096159c)
=> [backport][SES5] populate: don't create role-mon yml line during engulf (bsc#1104781)

srv/salt/_modules/wait.py, tests/unit/_modules/test_wait.py
(cherry picked from commit 3626d246766851ea673877981e32964c29cee965)
backport of #1298 
**Checklist:**
=> [backport][ses5] Add unittests for wait.just

man/deepsea-customization.7, man/deepsea-stage-0.7, qa/common/common.sh, srv/salt/ceph/stage/prep/master/default-update-reboot.sls, srv/salt/ceph/stage/prep/master/default.sls, srv/salt/ceph/stage/prep/minion/default-no-update-no-reboot.sls, srv/salt/ceph/stage/prep/minion/default-no-update-reboot.sls, srv/salt/ceph/stage/prep/minion/default-update-reboot.sls, srv/salt/ceph/stage/prep/minion/default.sls
Fixes #1254 
Description: The current default for stage.0 is to always update and restart( if needed ) the node. To be less aggressive, we change the default to no-reboot-update.
Also update stage 0 and customization man pages.
Also created doc bugs: 1103242, 1103247, 1103248 and 1103249
Please advise for which version of ses doc bug must exist? 5 or 6 or both?
=> Change the default for stage to update no reboot

qa/common/common.sh, qa/common/rgw.sh
When running integration test scripts from an interactive shell,
bare "systemctl status" will trigger a pager, requiring manual
intervention to continue.
Fix by always passing --no-pager to systemctl status.
=> qa: use "systemctl --no-pager --full status" and restart rsyslog service after installing curl RPM

srv/salt/_modules/cephinspector.py
This ensures the same code is used for determining /dev/disk/by-id paths
during engulf, as is used when invoking stage.1 to generate profiles.
Fixes: https://github.com/SUSE/DeepSea/issues/1264
**Checklist:**
=> cephinspector: use cephdisks.device in engulf (bsc#1082994)

srv/modules/runners/advise.py, srv/modules/runners/cephprocesses.py, srv/modules/runners/remove.py
```
xxxxxxxx:/deepsea/deepsea # salt-run disengage.safety; salt-run remove.osd 0 5
Removing osds 0, 5 from minions
Press Ctrl-C to abort
Exception occurred in runner remove.osd: Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 395, in _low
data['return'] = self.functions[fun](*args, **kwargs)
File "/srv/modules/runners/remove.py", line 29, in osd
result = __salt__['replace.osd'](*args, called=True, **kwargs)
File "/srv/modules/runners/replace.py", line 65, in osd
grains = local.cmd(host, 'grains.get', ['ceph'], tgt_type='compound')
File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 667, in cmd
**kwargs):
TypeError: get_cli_event_returns() got multiple values for keyword …
```
=> Move from tgt_type to expr_form in .py files

srv/modules/runners/proposal.py, srv/modules/runners/replace.py, srv/salt/_modules/cephdisks.py, srv/salt/_modules/osd.py, srv/salt/_modules/proposal.py, tests/unit/_modules/test_cephdisks.py, tests/unit/runners/test_proposal.py
Fixes #1215
Please have a look already, there are still a few things to do (I've noted them below) but the core business logic should stay more or less the same (unless you find some problems :wink:)
Description:
OSD Migration currently only works if the same slot is used. This works
because the generation of proposals is deterministic, so if all disks
are in the same position we end up with the same proposal.
This commit changes that behaviour: instead of creating a new proposal,
the old one is used and adapted. This happens in the following steps:
1) When `salt-run replace.osd X` is used and a proposal file (e.g.
"data1.ceph.yml" in /srv/pillar/proposals/...) gets the "-replace"
suffix, a new attribute is written for the disks that get replaced
2) When `salt-run proposals.populate` is …
=> OSD Migration for changed disk slots

srv/modules/runners/proposal.py, srv/modules/runners/replace.py, srv/salt/_modules/cephdisks.py, srv/salt/_modules/osd.py, srv/salt/_modules/proposal.py, srv/salt/ceph/functests/1node/replace/delay.sls, srv/salt/ceph/functests/1node/replace/force.sls, srv/salt/ceph/functests/1node/replace/multiple.sls, tests/unit/_modules/test_cephdisks.py, tests/unit/runners/test_proposal.py
Backport of #1302 
**Checklist:**
=> [backport][SES5] OSD Migration for changed disk slots

srv/salt/ceph/ganesha/files/ganesha.conf.j2
Fixes #
This patch can avoid the internal cache pressure warning as seen in bug#1103418
**Checklist:**
=> NFS-Ganesha + Cephfs: Add cache config options

srv/salt/ceph/ganesha/files/ganesha.conf.j2
Fixes #
This patch can avoid the internal cache pressure warning as seen in bug#1103418
Backport of https://github.com/SUSE/DeepSea/pull/1326 
**Checklist:**
=> [backport][SES5] NFS-Ganesha + Cephfs: Add cache config options

srv/salt/ceph/monitoring/prometheus/files/alerts.yml.j2
Without this, prometheus won't start, which breaks all the monitoring. Tested by copying file to running system, ran `salt admin.ceph state.apply ceph.monitoring`, checked grafana and openATTIC display.
=> monitoring: add missing ':' to alerts.yml

tests/unit/runners/test_proposal.py
Fixes #1324
Refactored tests and test data so new fake minions can be added easily. I migrated the test data from virtual disk paths to disk paths from blueshark.
~~### Do not merge~~
~~I am not sure if the tests work in CI but already open the PR to try it out.~~
Edit: Looks like sorting the proposal is needed because the comparison to the pytest fixture fails otherwise
**Checklist:**
=> Improve migration tests

srv/salt/ceph/monitoring/prometheus/exporters/files/rbd.sh
There was an issue with an sed regex that broke the exporter for pools
with IDs greater then 9.
Fixes: bsc#1106872
**Checklist:**
=> monitoring: fix rbd_exporter pool parsing for ids > 9

srv/salt/ceph/monitoring/prometheus/exporters/files/rbd.sh
There was an issue with an sed regex that broke the exporter for pools
with IDs greater then 9.
Fixes: bsc#1106872
Backport of #1338 
**Checklist:**
=> [backport][ses5] monitoring: fix rbd_exporter pool parsing for ids > 9

Makefile
While I believe it's a good idea to have "make rpm" run the unit tests,
we can't have that if the unit tests fail in a py3-only environment.
References: https://github.com/SUSE/DeepSea/issues/1351
**Checklist:**
=> build/ops: make "make rpm" work in a py3-only environment

cli/deepsea.py, cli/monitor.py, cli/stage_parser.py, cli/tests/test_stage_parse.py
This PR adds the support for orchestration salt.state functions with a list of sls identifiers. This fixes a problem in the CLI implementation that generated the following stacktrace:
```
Traceback (most recent call last):
File "/usr/bin/deepsea", line 9, in <module>
load_entry_point('deepsea==0.0.0', 'console_scripts', 'deepsea')()
File "/usr/lib/python2.7/site-packages/deepsea/deepsea.py", line 371, in main
cli(prog_name='deepsea')
File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
return self.main(*args, **kwargs)
File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
rv = self.invoke(ctx)
File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File …
```
=> cli: support list of sls ids in salt.state orch function

qa/common/common.sh, qa/common/deploy.sh, qa/common/pool.sh, qa/suites/basic/health-ok.sh
We used to have an rbd client test (librbd and rbd CLI), but it got disabled as part of the big QA refactor. This PR, along with https://github.com/SUSE/ceph/pull/206, reinstate it as part of tier2.
**Checklist:**
~~- [ ] Referenced issues or internal bugtracker~~
=> qa: reinstate rbd client test as part of tier2

srv/salt/ceph/monitoring/grafana/files/node.json
Thx to @evnu for the math assist.
(cherry picked from commit 1b2a2679d5b305c630dfa0d797b2b65c9f9f43d4)
Supersedes: #1341
Backport of #1344 
**Checklist:**
=> [backport][SES5] monitoring: fix fs fillup time query

man/deepsea-minions.7
Signed-off-by: Jonathan Brielmaier <jbrielmaier@suse.de>
Fixes: wrong formatting in `deapsee-minions` man page.
=> man: add line break between separate commands.

man/deepsea-minions.7
Signed-off-by: Jonathan Brielmaier <jbrielmaier@suse.de>
(cherry picked from commit cbc5db8f8b1ed7956467a87fee1de24b1530f9f6)
Fixes: wrong formatting in `deapsee-minions` man page.
backport of #1361
=> [backport][SES5]man: add line break between separate commands.

cli/stage_parser.py, cli/tests/test_stage_parse.py
=> [SES5] cli: fix parsing of salt.runner when used inside state files

cli/stage_parser.py, cli/tests/test_stage_parse.py
Fixes: #1364
(cherry picked from commit 8ca9753da0b01fee28fa407f24ff9bd8f5e43caf)
forwardport of #1366 
```
xxxxxx :: projects/deepsea/cli ‹forwardport-1366*› » ./run-unit-tests.sh
...snip..
15 passed in 114.88 seconds 
```
=> [forwardport][master] cli: fix parsing of salt.runner when used inside state files

srv/salt/ceph/mines/default.sls
Fixes: https://github.com/SUSE/DeepSea/issues/1367
backport of PR #727
**Checklist:**
=> [backport][SES5] stage 0: update salt mines correctly without restarting minion

Makefile
Running unit tests in "make rpm" is probably a bad idea in SES5 as well.
Running of unit tests could be added to `%check` section of deepsea.spec.in, then they would be run in OBS/IBS builds. But we don't need them for "make rpm" builds, since they require special setup.
=> [backport] [SES5] build/ops: make "make rpm" work without special environment

qa/common/common.sh, qa/common/deploy.sh
=> qa/deploy: use jq instead of python in salt_api_test

qa/common/common.sh, qa/common/deploy.sh
Backport of https://github.com/SUSE/DeepSea/pull/1377
=> [backport][SES5] qa/deploy: use jq instead of python in salt_api_test

srv/salt/ceph/tests/restart/changed_pid.sls, srv/salt/ceph/tests/restart/rgw/changed_pid.sls, srv/salt/ceph/tests/restart/rgw/same_pid.sls, srv/salt/ceph/tests/restart/rgw/save_pid.sls, srv/salt/ceph/tests/restart/same_pid.sls, srv/salt/ceph/tests/restart/save_pid.sls
The restart tests were assuming that "pgrep $CEPH_DAEMON" would always return a pid. See the commit messages for more rationale.
SES5 backport is included in https://github.com/SUSE/DeepSea/pull/1380
**Checklist:**
=> functests: fix problems that occur when process unexpectedly not running

srv/salt/ceph/restart/default.sls, srv/salt/ceph/tests/restart/changed_pid.sls, srv/salt/ceph/tests/restart/rgw/changed_pid.sls, srv/salt/ceph/tests/restart/rgw/same_pid.sls, srv/salt/ceph/tests/restart/rgw/save_pid.sls, srv/salt/ceph/tests/restart/same_pid.sls, srv/salt/ceph/tests/restart/save_pid.sls
Backports:
* #1210 
* #1381 (WARNING: NOT MERGED YET)
---
=> [backport][SES5] Only restart with a running cluster and  functests: fix problems that occur when process unexpectedly not running

qa/common/helper.sh, qa/suites/basic/health-ok.sh
In SES5 we have run_stage_0 in both the IGW and NFS_GANESHA conditionals, which
means Stage 0 gets run twice in the openattic test case.
This commit ensures we only ever re-run Stage 0 once, by putting it into its
own conditional.
**Checklist:**
=> qa/health-ok: repeat Stage 0 only once

qa/common/helper.sh, qa/suites/basic/health-ok.sh
backport of https://github.com/SUSE/DeepSea/pull/1383
---
In SES5 we have run_stage_0 in both the IGW and NFS_GANESHA conditionals, which
means Stage 0 gets run twice in the openattic test case.
This commit ensures we only ever re-run Stage 0 once, by putting it into its
own conditional.
---
The igw role is associated with transient failures in Stages 0 and 4.
This commit attempts to get more debugging info into the log when these
failures happen.
**Checklist:**
=> [backport][SES5] qa/health-ok: repeat Stage 0 only once and dump lrbd.service status in certain failure cases

srv/modules/runners/populate.py
backport of #1391 
**Checklist:**
=> [SES5] Remove error condition, empty cluster network is valid

qa/common/deploy.sh
Issue #1: When the command salt-key -L -l acc | grep -v '^Accepted Keys' fails,
the script was aborting immediately due to "set -e".
Issue #2: When running in an older version of SLES, python3 might not be
installed, and "python3 --version || true" was putting a confusing error
message into the log:
/usr/lib/deepsea/qa/common/deploy.sh: line 128: python3: command not found
Fixes #
Description:
**Checklist:**
=> qa/deploy: fix error-reporting issues

qa/common/deploy.sh
=> [backport] [SES5] qa/deploy: fix error-reporting issues

cli/monitors/terminal_outputter.py
The deepsea cli can be used to run any orchestration, not just ceph.stage.*
**Checklist:**
=> cli: refer to orchestration instead of stage

Makefile
8e2592c2 seems to have resulted in a bunch of duplicate `install` lines
in the Makefile; there's two blocks labelled "# functests/1node", the
second being a superset of the first, so I've gone and removed the first.
=> build: Remove duplicate functests `install` lines

srv/modules/runners/proposal.py
When invoking `salt-run`, all runners are loaded, and thus all globals
in those runners are evaulated.  The proposal runner was invoking
deepsea_minions.DeepseaMinions() to set the target global, which results
in a pillar refresh and a couple of pillar gets across all nodes.  If
any nodes were down, these three operations would each take 15 seconds
to time out, resulting in a delay of up to 45 seconds invoking any
runner if any nodes were down.  It also added a slight (2-3 second)
delay in the normal case where all nodes are up.
**Checklist:**
=> proposal: remove target and std_args globals (bsc#1100609)

srv/modules/runners/push.py
Technically, this is impossible from the original intent of
the runner to convert the old storage format to the new format.
The old format did not support journal sizes.
bnc#1073714
**Checklist:**
=> Remove journal_size if present

srv/salt/ceph/osd/restart/controlled/default.sls
(cherry picked from commit 96239e7f27dd3eeea316301af1b5741f93879bc3)
forwardport of #1423 
**Checklist:**
=> [forwardport] fix: only check OSDs after restarting an OSD

qa/common/common.sh, qa/common/deploy.sh
multipath is not needed with a single igw, and using it like that
apparently triggers a kernel bug, so drop it.
Fixes: https://github.com/SUSE/DeepSea/issues/1385
Signed-off-by: David Disseldorp <ddiss@suse.com>
**Checklist:**
~~- [ ] Referenced issues or internal bugtracker~~
=> [SES5] qa/iscsi: refactor iscsi_mount_and_sanity_test and enable targetcli debug logging

srv/modules/runners/replace.py, srv/salt/_modules/osd.py, tests/unit/_modules/test_osd.py
Fixes bsc#1110939
Description:
commit 1)
Change order of arg passing
commit 2)
In some cases we get `None` from
`content = yaml.safe_load(destroyed)`
~This probably should be factored into a separate function rather than wildly adding if statements..~
Done
I also refactored the yaml.dump code
TODO:
I had to refactor the tests quite a bit. They look more composed imo and should be easier to read and adapt in case of change.
**Checklist:**
=> fix _insert_replace_flag func header bsc#1110939

srv/salt/_modules/osd.py, tests/unit/_modules/test_osd.py
backport of #1424 
Bcache and NVMe devices follow the same device naming convention.
Remove the hardcoded strings and check whether the device ends with a
digit to add the 'p' partition delimiter. Likewise, truncate the 'p'
after separating the partitions when necessary.
Signed-off-by: Eric Jackson ejackson@suse.com
bnc#1107925
**Checklist:**
=> [backport][SES5] Remove hardcoded nvme devices, support generic convention

srv/modules/runners/populate.py, srv/modules/runners/validate.py, srv/modules/utils/settings.py, srv/salt/_modules/packagemanager.py, srv/salt/ceph/mines/default.sls, tests/unit/_modules/test_packagemanager.py, tests/unit/runners/test_validate.py
* add to setup(stage.0) validation
* notifies if there is a pending update
with 'ceph' in its name.
* stops stage.0 when there is salt-master or salt-minion
package in the queue and gives advise on how to proceed
* adds test
Fixes #1126
The checks add 3~seconds to the execution time respectively.
open questions:
1) Should the 'ceph-package' check also be included in stage.3 (adds ~3seconds)
2) I was _trying_ to use `mine.get` in the `validate.py` calls to reduce the invocation time
for those checks. I had to find out that the mines lie quite often.. This might be something we want
to look into a bit closer as we also rely on mines in the `replace.py` (where we do a complete `mine.flush` with a successive `mine.update` .. that's not ideal at …
=> Add validation for pending updates

Makefile, deepsea.spec.in, man/deepsea-stage-0.7, srv/modules/runners/cephprocesses.py, srv/pillar/ceph/blacklist.sls, srv/pillar/ceph/init.sls, srv/salt/_modules/cephprocesses.py, tests/unit/_modules/test_cephprocesses.py, tests/unit/_modules/test_osd.py, tox.ini
* Add file based blacklisting
* disabled && non-running services will be considered as
'not down' hence excluded from the checks.
Adds 60~ unittests
Fixes #1157 
TODO:
**Checklist:**
=> Refactor cephprocesses module and add tests for it V2

Makefile
This does nothing by default, and there's no documentation how to set it.
It was introduced by https://github.com/SUSE/DeepSea/pull/1173
**Checklist:**
=> Makefile: drop redundant PIPCMD

srv/modules/runners/ui_iscsi.py
`ui_iscsi.deploy` should apply state `ceph.igw.restart.force` instead of `ceph.igw.restart` to perform a service `restart` instead of `reload`.
Signed-off-by: Ricardo Marques <rimarques@suse.com>
=> lrbd service restart instead of reload on `ui_iscsi.deploy`

Makefile
=> Makefile: clean up suse conditional blocks

Makefile
Found while verifying https://github.com/SUSE/DeepSea/pull/1450.
That these $(DESTDIR) pieces were missing wouldn't actually cause
a problem for normal RPM builds (the spec file doesn't invoke
`make install` anyway, so won't hit these lines); it's only a
problem for weirdos like me ;-)
=> Makefile: Fix two missing $DESTDIRs

srv/modules/runners/validate.py, tests/unit/runners/test_validate.py
When using custom rgw roles and pushing certificates, prevent name collision
bnc#1105478
**Checklist:**
=> Prevent rgw-ssl name collision

srv/salt/ceph/functests/1node/init.sls
This is a temporary measure, to get the rest of the CI back into shape
until we determine what to do with the engulf function and LVM deployments.
Fixes: https://github.com/SUSE/DeepSea/issues/1453
**Checklist:**
=> qa: disable engulf functional test (not working with LVM)

srv/salt/_modules/osd.py, srv/salt/ceph/monitoring/prometheus/exporters/ceph_rgw_exporter/default-install.sls, srv/salt/ceph/packages/remove/default.sls, srv/salt/ceph/rescind/rgw/monitoring/default.sls
In openSUSE and SLE, packages starting with "python-..." are Python 2.
Since DeepSea is all on Python 3 now, we don't want to install any
packages starting with "python-...".
Also, without this patch Stage 4 fails on openSUSE Leap 15.0. On SLE-15, Stage 4 works even without the patch (not sure why).
Fixes: https://github.com/SUSE/DeepSea/issues/1463
**Checklist:**
=> Install python3-prometheus-client and make osd.py be compatible with Nautilus

Makefile, deepsea.spec.in, srv/modules/runners/validate.py, srv/salt/ceph/configuration/files/deprecated_map.yml, tests/unit/runners/test_validate.py
This is part of the pre-upgrade validations.
Looks like this when executed.
```shell
admin:/deepsea # salt-run validate.config_check cluster=ceph
/srv/salt/ceph/configuration/files/ceph.conf.d/mon.conf::mock tick internal: Key 'mock tick internal' is deprecated since bobtail. Please remove it from your config
False
```
It's not yet 'activated'  in the sense of being part of one of the existing validations (pillar, setup etc..)
Addresses #1008 
The [file](https://github.com/SUSE/DeepSea/pull/1460/files#diff-109c03c6ddf40b08362f7fca3a1651b1) that maintains the map of deprecated k-v is taken from the official ceph documentation. If anyone has a more accurate source, please let me know
**Checklist:**
=> Check configs for deprecated k:v pairs and report

tests/unit/_modules/test_cephdisks.py, tests/unit/_modules/test_osd.py
Prior to this change, we get an error 'RemovedInPytest4Warning: Fixture
"helper_specs" called directly. Fixtures are not meant to be called
directly, are created automatically when test functions request them as
parameters. See https://docs.pytest.org/en/latest/fixture.html for more
information.'
**Checklist:**
=> tests: don't call helper_specs fixture directly

srv/salt/_modules/cephdisks.py, tests/unit/_modules/test_cephdisks.py
Return version in cephdisk.version() instead of printing it. So ``salt '*' cephdisks.version`` will output correct values instead of None.
**Checklist:**
=> Return version instead of printing it

srv/modules/utils/ready.py, tests/unit/runners/test_ready.py
The passing message will be "not installed" only if all minions do not
have iptables installed.  Otherwise, the original behavior takes
precedent.
bsc#1115990
**Checklist:**
=> Consider iptables not installed as passing

srv/salt/_modules/osd.py
Harden split_partition function to do not fail in such case:
```
local:
----------
ceph:
----------
0:
----------
fsid:
4720f8d1-bd87-4e2e-9af9-c6214f1adecc
partitions:
----------
block:
/dev/dm-0
osd:
None
1:
----------
fsid:
8fe7d512-d40a-4d9f-9dcb-9f9328bb6f11
partitions:
----------
block:
/dev/dm-1
osd:
None
```
**Checklist:**
=> Harden split_partition function in osd module

srv/salt/ceph/redeploy/nodes/default.sls, srv/salt/ceph/redeploy/osds/default.sls
Increase the sliding window since some Ceph clusters take a substantial amount of time to evacuate an OSD.
bnc: 1116375
**Checklist:**
=> Change default timeout to 1 hour for redeploying OSDs

srv/salt/ceph/tuned/files/ceph-mgr/tuned.conf, srv/salt/ceph/tuned/files/ceph-mon/tuned.conf, srv/salt/ceph/tuned/files/ceph-osd/tuned.conf
Signed-off-by: Mohamad Gebai <mgebai@suse.com>
**Checklist:**
=> tuned: disable dynamic tuning for all profiles

srv/salt/ceph/tuned/files/ceph-mgr/tuned.conf, srv/salt/ceph/tuned/files/ceph-mon/tuned.conf, srv/salt/ceph/tuned/files/ceph-osd/tuned.conf
Signed-off-by: Mohamad Gebai <mgebai@suse.com>
suse internal: bsc#1119260
**Checklist:**
=> [SES5][backport] tuned: disable dynamic tuning for all profiles

srv/modules/runners/openstack.py
This patch adds a format() call to
eliminate the unwanted addition of "!!python/unicode" as part of the
prefix output.
Signed-off-by: Walter A. Boring IV <waboring@hemna.com>
Fixes #1495 
Description:
**Checklist:**
=> Fix: #1495  Fix unicode output error

srv/salt/ceph/openstack/cinder-backup/files/keyring.j2, srv/salt/ceph/openstack/cinder/files/keyring.j2, srv/salt/ceph/openstack/glance/files/keyring.j2
This patch fixes incorrect pool names in the auth caps for
cinder, cinder-backup, and glance users.  The pools are created
with names of
<prefix>cloud-volumes
<prefix>cloud-backups
<prefix>cloud-vms
<prefix>cloud-images
but the auth caps were created with pool names of
<prefix>volumes
<prefix>backups
<prefix>vms
<prefix>images
This patch fixes the auth caps pool names to use
<prefix>cloud-volumes
<prefix>cloud-backups
<prefix>cloud-vms
<prefix>cloud-images
Signed-off-by: Walter A. Boring IV <waboring@hemna.com>
Fixes #
Description:
**Checklist:**
=> Fix: #1493  Fixes auth caps for openstack.integrate

srv/salt/_modules/osd.py, tests/unit/_modules/test_osd.py
=> [SES5]Save and restore reweight in addition to weight

srv/modules/runners/minions.py
Description:
look for values of test.ping returns rather only the existence of the key
There seems to be a change on how test.ping returns 'down' minions.
Previously (salt 2016.x) it seemed to be fine to query the presence of
the key in the return. With at least salt-2018.x this is not true anymore
You get a return of {'node1': True, 'node2': False} (the entry remains in
the return of test.ping)
This entails that we always return True in 'minions.ready' although a node is
down.
**Checklist:**
=> minion.ready returns bogus in the latest versions of salt

Makefile, srv/modules/runners/push.py, tests/unit/_modules/test_cephdisks.py, tests/unit/_modules/test_osd.py, tests/unit/_modules/test_rgw.py, tests/unit/runners/test_changed.py, tests/unit/runners/test_proposal.py, tests/unit/runners/test_push.py, tests/unit/runners/test_sharedsecret.py, tox.ini
I think it's time to move our testing to python3 as we solely support python3 with the master-derived releases.
Changes due to:
* [StandardError was removed - Use Exception](https://docs.python.org/3/whatsnew/3.0.html#changes-to-exceptions)
* DeprecationWarning: invalid escape sequence \\*
* [\_\_builtin\_\_ renamed to builtins](https://docs.python.org/3/whatsnew/3.0.html#library-changes)
* [cmp was dropped](https://docs.python.org/3.0/whatsnew/3.0.html#ordering-comparisons)
Remark 1)
We still have to use a 'pyfakefs version < 3.3' as we rely on it's 'glob'. It's quite some work to move it to the new glob/fakefs api. Maybe after we reworked osd.py
Remark 2)
I skipped one test [test_prepare_device_file](https://github.com/SUSE/DeepSea/compare/pytest-py3?expand=1#diff-dc55f3e34c9ae82715049de …
=> Move pytest to base_python 3.6 and adapt tests accordingly

tests/unit/_modules/test_osd.py
They block other PR's from running successful tests.
=> Fix lint errors

srv/salt/_modules/osd.py, tests/unit/_modules/test_osd.py
Devices such as nvme append a 'p' for partitions, for example nvme0n1p1.
The 'p' must not be truncated for devices such as /dev/sdp.
bsc: 1123226
**Checklist:**
=> Check for digit before 'p'

srv/modules/runners/openstack.py
This patch adds a format() call to
eliminate the unwanted addition of "!!python/unicode" as part of the
prefix output.
Signed-off-by: Walter A. Boring IV <waboring@hemna.com>
Fixes #1495 
Description:
**Checklist:**
=> [backport][SES5] Fix: #1495  Fix unicode output error

tests/unit/_modules/test_osd.py
This \__builtin\__ was not replaced in PR #1492 
**Checklist:**
=> Addendum to #1492 (pytest to 3.6)

Makefile, deepsea.spec.in, srv/modules/runners/advise.py, srv/modules/runners/filequeue.py, srv/salt/ceph/functests/1node/rebuild/init.sls, srv/salt/ceph/obliterate/default.sls, srv/salt/ceph/obliterate/init.sls, srv/salt/ceph/obliterate/lock/default.sls, srv/salt/ceph/obliterate/lock/init.sls, srv/salt/ceph/obliterate/unlock/default.sls, srv/salt/ceph/obliterate/unlock/init.sls, srv/salt/ceph/rebuild/default.sls, srv/salt/ceph/rebuild/init.sls, tests/unit/runners/test_filequeue.py
Rather than migrate storage nodes incrementally, the rebuild
orchestration removes all OSDs and then recreates the OSDs.  The
filequeue and lock allow for graceful restarts after resolving
failures.
bsc#1105082
**Checklist:**
=> [SES5] Add rebuild orchestration, obliterate state

Makefile
Before this commit, we were generating the version number using
plain "git describe", which (according to the man page)
"finds the most recent tag that is reachable from a commit. If the tag
points to the commit, then only the tag is shown."
This had the undesirable effect of sometimes producing version numbers
that look like this:
0.8.9+2.g14f2f94e
and other times like this:
0.8.9
Depending on whether HEAD pointed to a tag or not. By passing the --long
option, we assure that the long format is used always.
Fixes #
Description:
**Checklist:**
=> Makefile: pass --long option to git describe

.gitignore, Makefile, deepsea.spec.in, srv/modules/runners/validate.py, srv/salt/_modules/osd.py, srv/salt/_modules/packagemanager.py, srv/salt/ceph/maintenance/upgrade/master/default.sls, srv/salt/ceph/maintenance/upgrade/minion/default.sls, srv/salt/ceph/osd/takeover/default.sls, srv/salt/ceph/osd/takeover/init.sls, srv/salt/ceph/updates/restart/default.sls, srv/salt/ceph/upgrade/zypper-dup.sls
* Do not execute a salt update in a orchestration
* Implement the ceph-disk->ceph-volume take-over
* Replace command we schedule reboots with
Due to changed behavior on the salt side we have to change the way we issue
reboots. See https://github.com/SUSE/DeepSea/issues/1508 for an explanation and
more information.
This will be the first branch to test the automated upgrade with.
**Checklist:**
=> Various fixes for the upgrade procedure

srv/salt/ceph/ganesha/install/default.sls
Description:
The management of nfs-ganesha through Ceph dashboard does not require the nfs-ganesha-utils package anymore.
=> ganesha: drop nfs-ganesha-utils install

srv/modules/runners/validate.py
The previous tag is missleading and suggests that
openattic is still valid and enabled.
In SES6(nautilus) oA is being replaced with the ceph-dashboard
**Checklist:**
=> Change validation tag from 'openattic' to 'openattic-disabled'

srv/salt/_modules/osd.py, srv/salt/ceph/functests/1node/symlink/init.sls, srv/salt/ceph/tests/symlink/init.sls, tests/unit/_modules/test_osd.py
The split_partition function never addressed failures such as broken
symlinks.  Adding a check with an appropriate return cascades into
several other operations.
bsc: 1123344
**Checklist:**
=> Handle broken symlinks

srv/salt/_modules/osd.py, tests/unit/_modules/test_osd.py
Only the device mapper entries were unmapped.  Now, the partitions on separate media are also removed.
bsc: 1122326
**Checklist:**
=> Address removal of dmcrypt partitions

.gitignore, Makefile, cli/tests/test_monitor.py, deepsea.spec.in, srv/modules/runners/disks.py, srv/modules/runners/push.py, srv/pillar/ceph/init.sls, srv/salt/_modules/dg.py, srv/salt/ceph/configuration/files/drive_groups.yml, srv/salt/ceph/stage/deploy/core/default.sls, tests/unit/_modules/test_dg.py, tests/unit/runners/test_disks.py
This is a first draft of the code that will transform a drive_group proposal to an actual list of devices.
Please read the wiki pages for [DriveGroups](https://github.com/SUSE/DeepSea/wiki/Drive-Groups) to get an idea on how specifications will look like.
~If you want to give this patch a try, there is a `drive_group.sls` in `/srv/pillar/ceph/` which can be adapted to your needs.~
I'll write a proper howto in the wikis soon.
~In this implementation the drive_group will reside in the pillar again..~
it will not. It will pull it from a file an stuff it down to the minions.
Expected to fail:
~* linter (there is a FIXME in it, which shouldn't be removed, yet - works besides this)~
done
~The runner call is `disks.test` which is just a temp name.~ …
=> Assign drives based on filter rules (DriveGroups) SES-150

deepsea.spec.in
Description:
Fix ownership of restart/{grafana,prometheus} dir
=> Fix ownership of restart/{grafana,prometheus} dir

srv/salt/ceph/stage/configure/default.sls, srv/salt/ceph/stage/deploy/default.sls, srv/salt/ceph/stage/deploy/monitoring.sls
Otherwise role assignments are not accessible since jinja is evaluated
before anything is run, including push.proposals and pillar sync (and thus
role-based switches get evaluated before roles are in the pillar).
=> monitoring: defer deployment to stage 3

Makefile, deepsea.spec.in, srv/salt/ceph/salt/crc/default.sls, srv/salt/ceph/salt/crc/init.sls, srv/salt/ceph/salt/default.sls, srv/salt/ceph/salt/init.sls, srv/salt/ceph/stage/prep/minion/default-no-update-no-reboot.sls, srv/salt/ceph/stage/prep/minion/default-no-update-reboot.sls, srv/salt/ceph/stage/prep/minion/default-update-reboot.sls, srv/salt/ceph/stage/prep/minion/default.sls
salt 2019 complains if there is no such setting.
bonus:
got rid of superfluous whitespaces
=> force 'adler32' as CRC method

srv/salt/ceph/stage/deploy/core/default.sls
Immediately after deploying ceph-mgr, it takes a few seconds for the
various modules to become available.  If we don't wait for this, any
subqeuent `ceph` commands that require mgr will fail (for example
`ceph mgr module enable [...]`).
**Checklist:**
=> stage 3: wait for mgr to be available after it's initially deployed

Makefile, deepsea.spec.in, srv/salt/ceph/dashboard/default.sls, srv/salt/ceph/dashboard/init.sls, srv/salt/ceph/stage/deploy/core/default.sls
I adapted the logic as follows:
* Username will default to 'admin' if not defined in the pillar (which takes precedence)
* Password will be generated with a salt internal function (`random.get_str(10)`) unless defined in the pillar (which takes precedence)
Since only `ceph mgr module enable dashboard` and `ceph dashboard create-self-signed-cert` are idempotent, there needs to be a check for the presence of the `dashboard_user` before actually creating the user.
After a user is created, the password will be stored in a grain structure looking like this:
``` yaml
dasboard_creds:
username_1:
password_1
username_2:
password_2
```
This structure will not allow to add multiple users at once (maybe we should?) but it will guarantee that switching to a new user, by changing the value in the …
=> Add dashboard orchestration

srv/modules/runners/populate.py, srv/salt/_modules/scrape_targets.py, srv/salt/ceph/monitoring/grafana/default.sls, srv/salt/ceph/monitoring/prometheus/push_scrape_configs.sls, tests/unit/_modules/test_scrape_targets.py
This adds scrape target partitioning to the prometheus deployment. For now partitioning is implemented for he node_exporter scrape targets. See also https://github.com/SUSE/DeepSea/wiki/New-Monitoring
Also adds Grafana configuration that the gr dashboard requires. See Step five of http://docs.ceph.com/docs/master/mgr/dashboard/#enabling-the-embedding-of-grafana-dashboards
=> scrape target partitioning, grafana config for dashboard (SES-261)

srv/salt/ceph/metapackage/default.sls
Without this, DeepSea fails in openSUSE because the osfullname grain contains
the string "Leap". As a result, the Jinja conditional evaluates to false and
the file becomes empty, causing Salt to generate a bizarre error.
(This is not cherry-picked from master because the fix for this issue in master
is too complicated.)
Fixes #
Description:
**Checklist:**
=> [SES5] metapackage: add test.nop stanza

Makefile, srv/salt/ceph/functests/1node/init.sls
This fixes a regression introduced by 9ce9f95cab1f1e24afa4bb405dd82b4e6ce0f06c
which was found by the CI.
The commit in question added the following directories:
srv/salt/ceph/functests/1node/symlink/
srv/salt/ceph/tests/symlink/
each containing a single file called "init.sls". However, since the commit did
not add the respective lines to Makefile, the new directories and files did not
make it into the deepsea-qa RPM, nor are they created when DeepSea is installed
via the "make install" method.
=> Makefile: install symlink tests and functests

Makefile, deepsea.spec.in, srv/modules/runners/disk_led.py, srv/pillar/ceph/disk_led.sls, srv/pillar/ceph/init.sls, srv/salt/ceph/packages/common/default.sls, tests/unit/runners/test_disk_led.py
Add runner to enable/disable storage enclosure LED.
The interface is based on
- https://docs.google.com/document/d/1kGoGq5qRWBnuyH7ZTCGfb16uD7sd9hddIY6mqtFy8q8/edit#
- https://pad.ceph.com/p/blinky-lights
Examples:
```
$ salt-run disk_led.device data2.ceph vdf fault off
$ salt-run disk_led.device data2.ceph /dev/vdf fault on
$ salt-run disk_led.device data2.ceph /dev/disk/by-id/scsi-SATA_ST3200XXXX2AS_5XWXXXR6 ident off
$ salt-run disk_led.device data1.ceph SanDisk_X400_M.2_1260_512GB_558924904728 ident on
```
**Checklist:**
=> Add runner to enable/disable storage enclosure LED

srv/salt/ceph/configuration/files/ceph.conf.j2
Not having this causes a newly deployed Nautilus cluster to come
up in HEALTH_WARN:
```
cluster:
id:     6c4a1148-a9ac-3dab-982f-0cb9d2ec1ada
health: HEALTH_WARN
4 monitors have not enabled msgr2
```
Fixes: bsc#1128964
**Checklist:**
=> ceph.conf: disable msgr2

cli/common.py, cli/monitors/terminal_outputter.py
Before:
```
[12/15]   ceph.packages.common on
hses-node1.suse.de......................................... ⏳ (34s)
|_ pkg.installed(lsscsi, smartmontools, hwinfo, pciutils, gptfdisk, python3-boto, python3-rados, iperf, lsof, jq, tuned, libgio-2_0-0, polkit) ⏳
```
After:
```
[12/83]   ceph.packages.common on
node3.oa.local.......................................................... ❌ (40s)
|_ pkg.installed(lsscsi, smartmontools, hwinfo, pciutils, gptfdisk,
python3-boto, python3-rados, iperf, lsof, jq, tuned,
libgio-2_0-0, polkit)............................................. ❌
node1.oa.local.......................................................... ❌ (40s)
|_ pkg.installed(lsscsi, smartmontools, hwinfo, pciutils, gptfdisk,
python3-boto, python3-rados, iperf, lsof, jq, tuned,
libgio-2_0-0, …
```
=> cli: automatically wrap of step lines

srv/modules/runners/net.py, srv/modules/runners/populate.py, srv/modules/runners/validate.py, srv/salt/_modules/public.py, srv/salt/ceph/configuration/files/rgw-ssl.conf, srv/salt/ceph/configuration/files/rgw.conf, tests/unit/_modules/test_public.py, tests/unit/runners/test_populate.py, tests/unit/runners/test_validate.py
Admin must specify the IPv6 public and cluster networks in the pillar.
**Checklist:**
=> Support IPv6

Makefile, deepsea.spec.in, srv/salt/ceph/functests/1node/init.sls, srv/salt/ceph/functests/1node/orchestrator/init.sls, srv/salt/ceph/mgr/orchestrator/default.sls, srv/salt/ceph/mgr/orchestrator/init.sls, srv/salt/ceph/stage/deploy/core/default.sls, srv/salt/ceph/tests/orchestrator/init.sls
This enables the deepsea mgr orchestrator module, sets it as the
current orchestrator backend, and configures it to talk to the
salt-api service.
**Checklist:**
=> stage 3: configure deepsea mgr orchestrator module

srv/salt/ceph/functests/1node/apparmor/init.sls
The ceph-mgr apparmor profile is currently broken, so if
apparmor is left in enforcing mode, subsequent functional
tests will fail after ceph-mgr is restarted during the
terminate tests.
**Checklist:**
=> qa: disable apparmor at end of functest

srv/salt/ceph/configuration/files/rgw-ssl.conf, srv/salt/ceph/configuration/files/rgw.conf
Fixes: https://github.com/SUSE/DeepSea/issues/1028
Description:
It is recommended to default to beast as the rgw frontend from mimic release onwards. Support this as the new default. I'd love some opinions on how to handle the upgrade scenarios. 
**Checklist:**
=> rgw: start making beast as a default frontend

srv/salt/_modules/osd.py, tests/unit/_modules/test_osd.py
The implementation differs from it's master commit(8e2592c2dc543aa8a6ad758eec79d8625bc1c0c8) which is probably a mistake.
Fixes #1528 
~TODO unittests~ done
**Checklist:**
=> [SES5] Do not return content in case there is no matching by_path

Makefile, deepsea.spec.in, srv/salt/ceph/salt/crc/crc_method.conf, srv/salt/ceph/salt/crc/default.sls, srv/salt/ceph/salt/crc/init.sls, srv/salt/ceph/salt/crc/master/default.sls, srv/salt/ceph/salt/crc/master/init.sls, srv/salt/ceph/salt/crc/minion/default.sls, srv/salt/ceph/salt/crc/minion/init.sls, srv/salt/ceph/stage/prep/master/default-no-update-no-reboot.sls, srv/salt/ceph/stage/prep/master/default-no-update-reboot.sls, srv/salt/ceph/stage/prep/master/default-update-reboot.sls, srv/salt/ceph/stage/prep/master/default.sls, srv/salt/ceph/stage/prep/minion/default-no-update-no-reboot.sls, srv/salt/ceph/stage/prep/minion/default-no-update-reboot.sls, srv/salt/ceph/stage/prep/minion/default-update-reboot.sls, srv/salt/ceph/stage/prep/minion/default.sls
Fixes #1593 
Fixes: aa40d37501600d1dd9c6c2bf650e61e49058c74a
~For me it seems to now suffice to have this entry *only* in the master conf.~
nope, see https://github.com/SUSE/DeepSea/pull/1594#issuecomment-477898215
This PR will add the 'crc_method' to `/etc/salt/minion.d/crc_method.conf` and `/etc/salt/master.d/crc_method.conf` respectively.
resolves: SES-351
*Checklist:**
=> Move crc_method to master.d/crc_method

srv/salt/ceph/stage/iscsi/core/default.sls
This PR fixes a bug that occurs when the cluster DNS configuration maps the same hostname to different IP addresses. We will now make sure the dashboard uses the correct IP address where the iSCSI gateway is listening.
=> iscsi: use iSCSi gateway public IP address in dashboard configuration

Makefile
Fixes: https://github.com/SUSE/DeepSea/issues/1616
=> Makefile: make "make rpm" less likely to produce a wrong version number

srv/salt/ceph/stage/prep/minion/default-no-update-no-reboot.sls, srv/salt/ceph/stage/prep/minion/default-no-update-reboot.sls, srv/salt/ceph/stage/prep/minion/default-update-reboot.sls, srv/salt/ceph/stage/prep/minion/default.sls
If deepsea_minions is compound target (e.g. G@deepsea:*) stage 0 will only succeed if salt is told about the compound target type.
=> crc_method: deepsea_minions can be a compound target

srv/salt/ceph/monitoring/grafana/default.sls
This simply looks better with the mgr dashboard.
=> monitoring: set grafana default theme to light

srv/modules/runners/proposal.py
Fix typo in URL that references Drive-Groups wiki.  Should be "https://github.com/SUSE/DeepSea/wiki/Drive-Groups"
Description: Fixes misinformation when users try to use deprecated "proposal.populate", pointing them to the Drive-Groups wiki on github.
**Checklist:**
=> Fix typo: URL reference to Drive-Groups wiki

srv/salt/ceph/packages/common/default.sls, srv/salt/ceph/stage/deploy/core/default.sls
ceph-volume needs to be present before stage.3
in earlier version we installed ceph separately in stage.3
Adding it to the list of basic requirements (installed in stage.0)
**Checklist:**
=> install ceph in packages.common

Makefile
=> [SES5] Makefile: make "make rpm" less likely to produce a wrong version number

srv/salt/_modules/dg.py
In a post-upgrade scenario the user still has old-style profiles defined in the
pillar.
Since we don't force the user to move to the new drive-group implementation
right after the upgrade, we have to detect that they are running in 'legacy'
mode and stop.
Fixes #
Description:
**Checklist:**
=> Avoid running drivegroup based osd deployment post-upgrade

srv/salt/ceph/igw/config/apply_iscsi_config.sls, srv/salt/ceph/igw/config/create_iscsi_config.sls, srv/salt/ceph/igw/files/iscsi-gateway.cfg.j2, srv/salt/ceph/stage/iscsi/core/default.sls
This PR adds the options to enable/disable SSL in ceph-iscsi REST API.
Currently SSL is disabled by default due to a bug in the communication between ceph-dashboard and ceph-iscsi when SSL is enabled.
=> iscsi: REST API ssl support

srv/salt/_modules/dg.py
This awful crutch should make life easier until
http://tracker.ceph.com/issues/38548 is fixed.
=> ceph-volume: use re to extract json string from c-v output

srv/modules/runners/disks.py
disks.details/deploy is used before a cluster is deployed
and no json will be returned
**Checklist:**
=> do no parse ceph output when no valid json

srv/salt/_modules/cephdisks.py
This affects disks.details and disks.report/deploy
We have a function that explicitly asks for disks
that are used by ceph. The default should be 'None'.
bsc:1131161
**Checklist:**
=> core: do not skip disks that are not used by ceph

deepsea.spec.in
otherwise we overwrite a customized file on update
=> build: make drive_group.yml 'noreplace'

Makefile, tox.ini
Explicitly specifying python3.6 means we can't run unit tests on
openSUSE Tumbleweed, which has python3.7, so let's just make it
use python3, which means whatever 3-series python happens to be
installed.
=> tox: use python3 instead of python3.6

srv/modules/runners/deepsea.py, tests/unit/runners/test_deepsea.py
Fixes the following bug:
```
>>> DEEPSEA_VERSION = '0.8.10+git.0.72e3fed70'
>>> re.findall(r'^\d\.\d\.?\d?', DEEPSEA_VERSION)
['0.8.1']
```
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1134216
TO DO:
=> runners/deepsea.py: fix deepsea RPM version detection

srv/modules/runners/deepsea.py, tests/unit/runners/test_deepsea.py
Fixes the following bug:
>>> DEEPSEA_VERSION = '0.8.10+git.0.72e3fed70'
>>> re.findall(r'^\d\.\d\.?\d?', DEEPSEA_VERSION)
['0.8.1']
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1134216
(cherry picked from commit 6787108a6784885c07e7a38825e36bb9625a6192)
=> [SES5] runners/deepsea.py: fix deepsea RPM version detection

srv/salt/ceph/monitoring/default.sls
The includes prometheus.update_service_discovery and prometheus.alertmanager do not exist anymore.
**Checklist:**
=> Remove obsolete includes

srv/modules/runners/disks.py, srv/salt/_modules/dg.py, tests/unit/runners/test_disks.py
This serves mainly the purpose of allowing to show matching disks
in a already deployed cluster.
There needs to be such a functionality in order to make migration
from profile-based to drive-group-based deployments easier.
Docs will point people towards:
`salt-run disks.list include_unavailable`
**Checklist:**
=> core: add include_unavailable flag for disks.py

srv/salt/ceph/apparmor/default-teardown.sls, srv/salt/ceph/apparmor/default.sls
SLE15 brings apparmor by default. Tear that down in a default installation.
=> By default teardown apparmor

srv/modules/runners/osd.py, srv/modules/runners/replace.py, srv/salt/ceph/purge/default.sls, srv/salt/ceph/rescind/storage/default.sls, tests/unit/runners/test_osd.py
This simplifies ceph.purge osd handling and avoids jinja based
osd_id iterations in sls files.
bsc#1133706
**Checklist:**
=> core: osd.remove to accept compound targets

srv/modules/runners/mgr_orch.py, tests/unit/runners/test_mgr_orch.py
This changes describe_service() so it will return a dict for each
service, which includes at minimum service_instance (i.e. the daemon
ID), and also rados_config_location and service_url for ganesha
and igw instances respectively.
**Checklist:**
=> mgr_orch: return ganesha and iscsi endpoint URLs

srv/salt/_modules/dg.py
Salt grains reported FQDN while ceph volume was expecting only short hostname.
Signed-off-by: Shyukri Shyukriev <shshyukriev@suse.com>
**Checklist:**
=> Extract short hostname from salt grains to feed ceph c_v properly 

srv/salt/ceph/time/chrony/files/chrony.conf.j2
Without an allow statement, Chrony does not listen on port 123
Fixes: https://github.com/SUSE/DeepSea/issues/1614
=> chrony: allow NTP access from local network

man/deepsea-commands.7, srv/modules/runners/disks.py, srv/modules/runners/rebuild.py, srv/salt/_modules/osd.py, tests/unit/runners/test_rebuild.py
Description:
Serially removes and redeploys OSDs.
```
salt-run rebuild.node TARGET...
salt-run rebuild.aggressive TARGET...
salt-run rebuild.identical TARGET...
```
The difference betwen `node` and `aggressive` is an `active+clean` is performed for each OSD with node and is only performed between the nodes with aggressive.  The Ceph cluster must recover in either case before the rebuild proceeds.
One caveat is that the Ceph cluster will reach HEALTH_ERR and recover.  That is still under investigation, but no data loss occurs.
**Checklist:**
=> Implement rebuild runner

srv/salt/ceph/dashboard/default.sls
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1129225
**Checklist:**
=> Use correct config name for Dashboard SSL port

Makefile, deepsea.spec.in, srv/modules/runners/select.py, srv/salt/_modules/deepsea.py, srv/salt/ceph/dashboard/default.sls, srv/salt/ceph/igw/config/create_iscsi_config.sls, srv/salt/ceph/monitoring/grafana/create_configs.sls, srv/salt/ceph/ssl/default.sls, srv/salt/ceph/ssl/distribute_ca.sls, srv/salt/ceph/ssl/init.sls, srv/salt/ceph/stage/configure/default.sls, srv/salt/ceph/stage/deploy/core/default.sls
This PR adds the capability to DeepSea to management SSL certificates by using its own CA.
A CA certificate is created, and a wildcard certificate is also created and signed by the CA in stage 2. The wildcard domain corresponds to the domain of the cluster.
We then use the wildcard certificate in all services that are SSL capable like dashboard, ceph-iscsi, grafana, and radosgw.
**Edit** (removed RGW commit from the PR)
=> SSL certificate deployment and management

deepsea.spec.in
We are now explicitly declaring all packages (with the exception of core Ceph itself) that deepsea might insist on installing as part of a Ceph deployment.
=> spec: add explicit prometheus, grafana runtime deps

srv/salt/_modules/dg.py, tests/unit/_modules/test_dg.py
1) Error messages should not be executed.
2) Unify error messages in case `wal` and no `db`
3) Fix filestore deployment
**Checklist:**
=> dg: make error conditions consistent; don't execute a error message

srv/salt/_modules/iscsi.py
Fixes `iscsi.wait_for_gateway` module function when building the gateway URL using IPv6 addresses.
=> iscsi: fix gateway URL when using IPv6 address

doc/pillar/alertmanager_receiver_snmp.yml, srv/salt/ceph/monitoring/alertmanager/default.sls, srv/salt/ceph/rescind/alertmanager/default.sls
Install the prometheus-webhook-snmp Prometheus Alertmanager reveiver if pillar ``monitoring:alertmanager:receiver:snmp:enabled`` is set to True.
To enable and configure the Prometheus Alertmanager SNMP receiver the pillar data might look like:
```
monitoring:
alertmanager:
receiver:
snmp:
enabled: True
config:
host: localhost
port: 9099
snmp_host: snmp.foo-bar.com
snmp_community: private
metrics: True
```
**Checklist:**
=> Deploy Prometheus Alertmanager SNMP receiver

srv/modules/runners/disks.py, srv/salt/_modules/dg.py, tests/unit/runners/test_disks.py
This parameter is useful for using disks.report and a forceful
disks.deploy.
The command is already mentioned in https://bugzilla.suse.com/show_bug.cgi?id=1135340
**Checklist:**
=> dg: Add parameter to bypass the pillar_check of dg.py

srv/salt/ceph/configuration/files/drive_groups.yml
Also add a few lines explaining what this does
**Checklist:**
=> dg: adapt default drive group to only match 'roles:storage'

srv/salt/ceph/stage/deploy/monitoring.sls
=> monitoring: polulate alertmanager peers must run on salt master

srv/salt/_modules/cephprocesses.py, tests/unit/_modules/test_cephprocesses.py
bsc#1136818
do not exit if there is a missing pillar struct. This is the case in a new node addition
**Checklist:**
=>  cephprocesses: do not exit on missing pillar struct 

srv/salt/ceph/apparmor/default-disable.sls
The reasoning behind this is that aa-disable fails if the profiles in
question was not in either complain or enforce mode before. For thsi
state it doesn't matter if its disabled or never was enabled.
Fixes: bsc#1130930
Not 100% if this might not mask other failure modes of aa-disable, just couldn't think of any.
=> apparmor: ignore aa-disabled return code

srv/salt/ceph/rescind/time/ntp/default.sls
On SUSE distros, at least, the correct package name is "ntp",
not "ntpd".
=> rescind/ntp: remove the correct RPM

tests/unit/_modules/test_dg.py
pytest.raises expected a message= parameter in the past.
This has changed now
(https://docs.pytest.org/en/4.6-maintenance/deprecations.html#message-parameter-of-pytest-raises)
Description:
This currently blocks merging for other PRs. Please treat with priority.
=> tests: adapt to new pytest syntax (pytest.raises)

srv/salt/_modules/cephprocesses.py, srv/salt/_modules/mds.py, srv/salt/ceph/mds/auth/default.sls, srv/salt/ceph/mds/default.sls, srv/salt/ceph/mds/key/default.sls, srv/salt/ceph/mds/keyring/default.sls, srv/salt/ceph/mds/restart/controlled/default-shared.sls, srv/salt/ceph/mds/restart/controlled/default.sls, srv/salt/ceph/mds/restart/force/default.sls, srv/salt/ceph/mds/shutdown.sls, srv/salt/ceph/rescind/mds/default.sls, srv/salt/ceph/rescind/mds/keyring/default.sls, tests/unit/_modules/test_cephprocesses.py, tests/unit/_modules/test_mds.py
This adds a "mds." prefix the the daemon name in case a mds hostname starts
with a digit.
Fixes: bsc#1138442
This fixes the mds names for new deployments. daemon names that would start with a digit (i.e. when a hostname starts with a digit) get a `mds.` prefix.
=> mds: numerical mds names are forbidden (have been deprecated since 2014)

srv/salt/_modules/mds.py, srv/salt/ceph/mds/auth/default.sls, srv/salt/ceph/mds/default.sls, srv/salt/ceph/mds/key/default.sls, srv/salt/ceph/mds/keyring/default.sls, srv/salt/ceph/mds/migrate-numerical-names.sls, srv/salt/ceph/mds/remove-mds-with-numeric-names.sls, srv/salt/ceph/mds/restart/controlled/default-shared.sls, srv/salt/ceph/mds/restart/controlled/default.sls, srv/salt/ceph/mds/restart/force/default.sls, srv/salt/ceph/mds/shutdown.sls, srv/salt/ceph/rescind/mds/default.sls, srv/salt/ceph/rescind/mds/keyring/default.sls, tests/unit/_modules/test_mds.py
This fixes the mds names for new deployments. daemon names that would start with a digit (i.e. when a hostname starts with a digit) get a `mds.` prefix.
This also adds an orchestration to migrate from the invalid names to the new naming scheme. Starting the migration with no invalid names present should not change anything, i.e. be safe to run at any time with an mds cluster present.
=> SES5: fix mds numerical names

srv/salt/_modules/dg.py, tests/unit/_modules/test_dg.py
This was still missing. See wiki
**Checklist:**
~- [ ] Adapted documentation~ changed in the wiki soon
=> core: add osds_per_device flag

srv/salt/_modules/dg.py, tests/unit/_modules/test_dg.py
Add workarounds for:
1) Do not accept disks < 5GB
2) Do not accept /dev/mapper disks (this needs more thinking as you actually may want to deploy /dev/mapper devices)
Tests for various cases added.
The workarounds need to be adapted with the addition of #1690. With this PR we source the `disks list` from the ceph_volume library and not from the CLI. Also, we moved the logic in `cephdisks.py`.
suse_internal: bsc#1141368, bsc#1141367, bsc#1141503
**Checklist:**
=> dg: workaround ceph-volume infused bugs 

Makefile
Fixes #
Update Makefile to use python3 on Centos
Description:
**Checklist:**
- [ n ] Added unittests and or functional tests
- [ n ] Adapted documentation
- [ n ] Referenced issues or internal bugtracker
- [ y ] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)
=> fix(makefile): update for centos/python3

Makefile
Helps # https://github.com/SUSE/DeepSea/issues/57. Supercedes #1697 
Description:
This PR fixes `make install` on Ubuntu (Debian) with python3.
**Checklist:**
- [ n ] Added unittests and or functional tests
- [ n ] Adapted documentation
- [ n ] Referenced issues or internal bugtracker
- [ y ] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)
=> makefile: update for ubuntu/python 3

Makefile
Fixes #
Description:
This PR changes hardcoded `salt:salt` string to dynamic variable.
**Checklist:**
- [ n ] Added unittests and or functional tests
- [  n ] Adapted documentation
- [ n ] Referenced issues or internal bugtracker
- [ y ] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)
=> fix(makefile): remove hardcoded user:group

srv/modules/runners/disk_led.py, tests/unit/runners/test_disk_led.py
* Check the result type of 'udev.links' before iterating.
* Check if the identifier is in 'grains.get disks' before iterating over the device names (including all the other stuff). This will reduce the work to do in some cases.
**Checklist:**
=> The disk_led runner crashes (bsc#1142821)

srv/salt/_modules/dg.py, tests/unit/_modules/test_dg.py
The official docs state that this is already possible. Adding
**Checklist:**
=> Allow literal wal db journal sizes

srv/modules/runners/osd.py, srv/salt/_modules/cephdisks.py
before:
`salt-run osd.remove(replace) $osd_id`
[..snip..]     
```                                                                                                                                                                                                                                                                                                                                              
14:                                                                                                                                                                                                                                            
True 
```
after:
```
14: …
```
=> remove/replace: add path to status report for better identification

srv/salt/_modules/cephdisks.py, tests/unit/_modules/test_cephdisks.py
=> flip logic for /available/ disks filtering

srv/salt/ceph/configuration/files/rgw-ssl.conf, srv/salt/ceph/configuration/files/rgw.conf
This is only useful for s3 clients which don't support path style access, and
even in those cases there needs to be an additional dnsmasq setting or the like
that can correctly redirect `<bucketname>.<rgw-endpoint>` to `<rgw-endpoint>`.
For the remainder of use cases; if this is configured incorrectly it always leads
to bugs for all s3 clients and it is hard to get this right, as many rgws may be
terminated with a load balancer in which case we need the endpoint to be that.
So moving forward, we'd make this option manually configurable for those sites
that really need the vhost style access, as this requires some knowledge on the
s3 clients and their site dns setting which is hard to predict correctly anyway
Fixes: #842
**Checklist:**
=> conf: rgw: drop rgw dns name configurable

srv/salt/_modules/cephdisks.py, srv/salt/_modules/dg.py
Proposed solution for "#Bug 1145600 - Unable to remove/rebuild Filestore OSDs through Deepsea", I also added it on `dg.py` since I saw that it's applied there as well.
Description:
Add the 'ceph.type' tag for filestore OSDs
**Checklist:**
=> Added data tag in cephdisks/dg for filestore OSDs

srv/modules/runners/remove.py
I hate changing code to accommodate tests, but I don't see another path
for this one.  The structure of a Salt orchestration file provides `arg`
as a keyword to the runner internally.  Changing from using `osd_list`
to `args` broke the tests, but matches the user requirement.
**Checklist:**
=> Accommodate Salt integration tests

Makefile
Description:
Makefile does not include 'ext_lib' runners dir.
admin:~/DeepSea # salt-run mon.deploy
'mon' __virtual__ returned False: No module named 'ext_lib'
Exception ignored in: <bound method IPCClient.__del__ of <salt.transport.ipc.IPCMessageClient object at 0x7f6e513360f0>>
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/salt/transport/ipc.py", line 374, in __del__
File "/usr/lib/python3.6/site-packages/salt/transport/ipc.py", line 405, in close
File "/usr/lib64/python3.6/logging/__init__.py", line 1296, in debug
File "/usr/lib/python3.6/site-packages/salt/log/setup.py", line 343, in _log
File "/usr/lib64/python3.6/logging/__init__.py", line 1443, in _log
File "/usr/lib/python3.6/site-packages/salt/log/setup.py", line 363, in makeRecord
NameError: name …
=> Add 'ext_lib' runners to 'make install'

srv/modules/runners/advise.py, srv/modules/runners/bootstrap.py, srv/modules/runners/ceph.py, srv/modules/runners/config.py, srv/modules/runners/ext_lib/hash_dir.py, srv/modules/runners/ext_lib/utils.py, srv/modules/runners/host.py, srv/modules/runners/mgr.py, srv/modules/runners/mon.py, srv/salt/_modules/cephprocesses.py, srv/salt/_modules/mgr.py, srv/salt/_modules/podman.py, srv/salt/ceph/mgr/keyring/default.sls, srv/salt/ceph/packages/common/default.sls
Description:
This PR enables DS-next to bootstrap a cluster(mon&mgr) using containers.
* Added/Completed the `salt-run bootstrap.ceph` runner.
`salt-run bootstrap.ceph [non_interactive=True/False]`
Will bootstrap a cluster from nothing to N monitors and N managers (N depending on your policy.cfg).
* Added non-interactive modes for mon/mgr
* Added a unitfied `promp` method that supports non_interactive calls
CAVEAT:
* I experienced issues when invoking podman(version 1.01) via the remote salt context.
`salt \admin* podman.get_ceph_version`
would make podman/conmon/runc stuck, and runc's child processes even defunct. This would eventually time out in salt, but not in podman, leaving zombie processes behind.
This behavior was *not* seen when …
=> [next] Initial bootstrap code - SES-764

deepsea.spec.in
Fix-up for PR #1725 
Signed-off-by: Michael Fritch <mfritch@suse.com>
**Checklist:**
=> [next] Add 'ext_lib' runners to RPM spec

deepsea.spec.in
warning: File listed twice: /srv/salt/ceph/apparmor/files/ceph.d
warning: File listed twice: /srv/salt/ceph/apparmor/files/ceph.d/common
warning: File listed twice: /srv/salt/ceph/configuration/files/ceph.conf.checksum
warning: File listed twice: /usr/lib/python3.6/site-packages/deepsea-0.9.22+69.gf6d75310-py3.6.egg-info/PKG-INFO
warning: File listed twice: /usr/lib/python3.6/site-packages/deepsea-0.9.22+69.gf6d75310-py3.6.egg-info/SOURCES.txt
warning: File listed twice: /usr/lib/python3.6/site-packages/deepsea-0.9.22+69.gf6d75310-py3.6.egg-info/dependency_links.txt
warning: File listed twice: /usr/lib/python3.6/site-packages/deepsea-0.9.22+69.gf6d75310-py3.6.egg-info/entry_points.txt
warning: File listed twice: /usr/lib/python3.6/site-packages/deepsea-0.9.22+69.gf6d75310-py3.6.egg-info/to …
=> Fix rpmbuild warnings

.gitignore, Makefile
Description:
The 'make tarball' and 'make rpm' targets were failing in various ways when run as user 'root' and also when run as a 'non-root' user.
**Checklist:**
=> Fixup rpmbuild in Makefile

srv/modules/runners/advise.py, tests/unit/runners/test_advise.py
=> Report malformed responses from misbehaving minions

srv/salt/ceph/mds/pools/default.sls
With unless the state is executed when one condition returns false. For
example it'll try to create the cephfs_data pool if the pool is present
but the cephfs instance is not yet.
Negating the condition and using onlyif yields the expected behaviour.
=> cephfs: fix pool creation prerequisite (bsc#1149557)

srv/salt/ceph/mds/pools/default.sls
With unless the state is executed when one condition returns false. For
example it'll try to create the cephfs_data pool if the pool is present
but the cephfs instance is not yet.
Negating the condition and using onlyif yields the expected behaviour.
(cherry picked from commit 8667b12adbd66a773e29cc7c59e97e496a586b05)
Backport for #1750
=> cephfs: fix pool creation prerequisite

srv/salt/ceph/apparmor/default-teardown.sls
Adding apparmor=0 to grub.cfg causes aa-teardown to always fail
bnc#1149405
**Checklist:**
=> [SES6] Handle the apparmor disabled at boot scenario

srv/salt/ceph/apparmor/default-teardown.sls
Adding apparmor=0 to grub.cfg causes aa-teardown to always fail
Port #1738 
**Checklist:**
=> Handle the apparmor disabled at boot scenario

srv/salt/_modules/kernel.py
=> [SES6] Prevent IOLoop error by calling Salt modules correctly

srv/modules/runners/changed.py, srv/modules/runners/select.py, srv/salt/_modules/iscsi.py, srv/salt/ceph/igw/config/apply_iscsi_config.sls, srv/salt/ceph/igw/config/create_iscsi_config.sls, srv/salt/ceph/igw/files/iscsi-gateway.cfg.j2, srv/salt/ceph/stage/deploy/core/default.sls, srv/salt/ceph/stage/iscsi/core/default.sls, srv/salt/ceph/stage/iscsi/dashboard.sls, srv/salt/ceph/stage/iscsi/default.sls, tests/unit/runners/test_changed.py
Fixes: bsc#1134536
This PR makes the deployment of iscsi (ceph-iscsi) service to have SSL enabled by default for its REST API.
=> iscsi: SSL enabled deployment by default

deepsea.spec.in, srv/modules/runners/status.py, srv/modules/runners/upgrade.py, srv/modules/utils/status.py
This is similar to status.report, but specifically intended to advise the user on what order to perform an upgrade in.  The underlying assumption is that the admin node has already been upgraded to the latest possible version.  Then, when you run `salt-run upgrade.status`, you'll see similar to one of the following:
1) If everything is the same version:
```
All nodes are running:
ceph: ceph version 14.2.1-468-g994fd9e0cc (994fd9e0ccc50c2f3a55a3b7a3d4e0ba74786d50) nautilus (stable)
os: SUSE Linux Enterprise Server 15 SP1
````
2) If there's a mix of versions:
```
The newest installed software versions are:
ceph: ceph version 14.2.1-468-g994fd9e0cc (994fd9e0ccc50c2f3a55a3b7a3d4e0ba74786d50) nautilus (stable)
os: SUSE Linux Enterprise Server 15 SP1
Nodes running these software versions: …
```
=> Add status function to advise on upgrade order

srv/salt/_modules/kernel.py
=> Prevent IOLoop error by calling Salt modules correctly

srv/salt/_modules/kernel.py
=> [SES5] Prevent IOLoop error by calling Salt modules correctly

srv/salt/_modules/cephprocesses.py, tests/unit/_modules/test_cephprocesses.py
=> [SES5] Restrict lsof to ceph user (performs better on some servers)

Makefile
Description:
The `make pyc` target was succeeding even though py_complie failed to generate valid bytecode:
```
#make sure to create bytecode with the correct version
find srv/ -name '*.py' -exec python3 -m py_compile {} \;
File "srv/modules/runners/cmd.py", line 10
undef run(**kwargs):
^
SyntaxError: invalid syntax
find cli/ -name '*.py' -exec python3 -m py_compile {} \;
0
```
This is also causing the `make install` target to succeed despite the failed `pyc` dependency.
New behavior of `make pyc` is as follows:
```
#make sure to create bytecode with the correct version
find srv/ -name '*.py' -exec python3 -m py_compile {} +
File "srv/modules/runners/cmd.py", line 10
undef run(**kwargs):
^
SyntaxError: invalid syntax
make: *** [Makefile:67: pyc] Error 1
2
``` …
=> 'make pyc' target should fail if unable to compile

srv/modules/runners/ext_lib/decorators.py, srv/modules/runners/ext_lib/exceptions.py, srv/modules/runners/ext_lib/utils.py, srv/modules/runners/test.py
This will not only handle the Exception case but also
return the correct values based on the context (orchestrator, runner)
This allows us to have consistent behavior independent of whether we are calling a runner or a module underneath.
We have three modes:
`human` (default)
We're returning the aggregated results in a  human readable form (success/failure)
----------------------
`orchestrator`
We're returning a datastructure of our choice (current this returns a list of returnvalues, which is not *terribly* insightful). We can adapt this returnvalue anytime when we have real requirements from the orchestrator.
----------------------
`runner`
That's for internal uses only. This will re-raise the Exception in form of a str when an isssue is encountered.
If it succeeds it will currently …
=> [next] Refine the runner function decorator

Makefile, deepsea.spec.in, srv/salt/_modules/wait.py, srv/salt/ceph/restart/osd/default.sls, srv/salt/ceph/restart/osd/lax/default.sls, srv/salt/ceph/wait/until/all_osds_in/default.sls, srv/salt/ceph/wait/until/all_osds_in/init.sls
=> [SES5] Check that all OSDs are "in" during restart

Makefile
=> [backport][SES6] 'make pyc' target should fail if unable to compile

srv/modules/runners/ext_lib/doc.py, srv/modules/runners/test.py
* rely on a doc_template living in doc.py
This will make sure to have a consistent way of writing help texts
for all our runners.
* use pydoc's pager() functionality to use the systems default pager
=> [next] add help() func to test runner

srv/modules/runners/config.py, srv/modules/runners/ext_lib/decorators.py, srv/modules/runners/ext_lib/exceptions.py, srv/modules/runners/ext_lib/hash_dir.py, srv/modules/runners/ext_lib/operation.py, srv/modules/runners/ext_lib/utils.py, srv/modules/runners/test.py
* pillar sync
* module sync
* custom dummy prompt
also I improved the handling for non-existent role queries.
bonus: added a DEEPSEA_DEBUG env variable check that drops
into a post mortem debugger.
=> [next] Extend the demo runner (test.py) with interactive prompts

Makefile
Description:
No need for the Makefile to become interactive if all the dependencies are already installed.
**Checklist:**
=> Do not run sudo installer unless necessary

deepsea.spec.in
Description:
The pyc files require build host to have a compatible python3 to build an rpm.  
**Checklist:**
=> Remove python dependency on host when building local rpm

srv/modules/runners/validate.py, srv/modules/utils/ready.py, srv/salt/ceph/stage/deploy/core/default.sls
From Salt 2018.3, the retcode is honored and orchestrations fail
correctly.
**Checklist:**
=> Runners can work as intended in orchestrations

srv/salt/ceph/purge/default.sls
Swapped the order of 'ceph'reset' and 'osd.remove' in order to provide a
fix for bcs #1150168
Signed-off-by: Georgios Kyratsas <gkyratsas@suse.com>
Fixes # `ceph.purge`
Description:
I have deployed a basic test for `ceph.purge` in order to have it in CI where purge was failing every single time (reported in bcs #1150168). So I worked with @swiftgist and he helped me find the issue.
**Checklist:**
=> srv/salt/ceph/purge: Changed order of runner calls

srv/salt/ceph/purge/default.sls
Fixes #
Description: Backport PR #1793 to `SES6` branch in order to fix the bug bcs #1150168 regarding `ceph.purge`.
**Checklist:**
=> Backport: srv/salt/ceph/purge: Changed order of runner calls

Makefile, etc/salt/master.d/logging.conf, srv/modules/runners/disks.py, srv/modules/runners/osd.py, srv/modules/utils/tee.py, tox.ini
The console output remains the same, but the output is also logged to
/var/log/salt/master.  A restart of the salt-master is necessary.
jira: SES-813
**Checklist:**
=> [SES6] Split output to console and Salt log

srv/salt/ceph/remove/mds/default.sls
=> [SES6] Allow for graceful rerunning when removing the cephfs configuration

deepsea.spec.in
=> build/ops: fix dir ownership for srv/modules/modules

srv/modules/runners/osd.py
When a OSD is not actively deployed anymore
but is still present in the crushmap you want to be
able to replace it.
This patch extends the condition for such a case.
suse_internal: bsc#1157469
=> osd/replace: only access metadata if present

srv/modules/runners/osd.py
When a OSD is not actively deployed anymore
but is still present in the crushmap you want to be
able to replace it.
This patch extends the condition for such a case.
(cherry picked from commit 1ea490ebb849caf4fb3679380dc0511347ac7522)
backport of #1807 
**Checklist:**
=> [backport][ses6] osd/replace: only access metadata if present

srv/salt/_modules/cephdisks.py, tests/unit/_modules/test_cephdisks.py
$subject
suse_internal: bsc#1158196
**Checklist:**
=> cephdisks: exclude disks that are assigned to raid configurations

srv/salt/ceph/dashboard/default.sls
=> Allow custom grafana endpoint

srv/salt/_modules/helper.py
Patch-by: Joerg Reuter <jreuter@suse.com>
suse_internal: bsc#1158184
**Checklist:**
=> use non-blocking i/o with .wait

srv/salt/_modules/helper.py
(cherry picked from commit 903e25833c2a5176772a1016715a3b4868191217)
backport of #1812 
**Checklist:**
=> [backport][ses6] use non-blocking i/o with .wait

srv/salt/_modules/cephdisks.py, tests/unit/_modules/test_cephdisks.py
Fixes: bsc#1158196
Although it's still controversial to use RAID devices as OSDs, this patch excludes all /dev/md* devices from the list of possible OSDs.
**Checklist:**
=> [SES6] cephdisks: exclude mdraid devices

srv/salt/ceph/time/ntp/default.sls
Fixes: https://github.com/SUSE/DeepSea/issues/1822
**Checklist:**
=> [SES5] ceph.time: work around buggy "service.running"

srv/salt/_modules/osd.py, tests/unit/_modules/test_osd.py
During the transition from a partition based OSD to an LVM based OSD,
the grains are no longer updated.  As a result, two different storage
nodes can report the same OSD id, since the original still has a stale grain
entry.  Not including the grains will correct this collision.
bsc: 1160172
**Checklist:**
=> Grains are not used by ceph-volume

srv/salt/_modules/iscsi.py
This PR fixes some iSCSI default values to match the ones configured in `ceph-iscsi`:
https://github.com/SUSE/ceph-iscsi/blob/ses6/ceph_iscsi_config/gateway_setting.py#L212
Signed-off-by: Ricardo Marques <rimarques@suse.com>
=> Fix iSCSI default values

srv/salt/ceph/monitoring/prometheus/files/ses_default_alerts.yml
Backported from https://github.com/ceph/ceph/pull/34227/commits/6935dc55921ef533e939719bad7dc12324450bbb.
Adapt metric names and queries to node_exporter in SES5.
Fixes: bsc#1152100
**Checklist:**
=> Prometheus sents pool filling up warning emails

srv/salt/ceph/rescind/grafana/default.sls, srv/salt/ceph/rescind/mgr/dashboard/default.sls
The ceph-mgr-dashboard requires the ceph-grafana-dashboards, so only
uninstall the ceph-grafana-dashboards from minions that have neither
grafana nor mgr roles.
bsc: 1168359
**Checklist:**
=> Do not remove ceph-grafana-dashboards on mgr nodes

srv/modules/runners/osd.py
Fixes bsc#1171451
Description:
We seem to have an issue with ceph 14.2.8+ and osd replacements/removals where the step in `osd.remove/replace` that is supposed to destroy/purge the osd from the crushmap bails out when the osd is not in the expected 'down' state. This should happen automatically after the osd daemon has stopped. Apparently there's a timing issue somewhere. An easy and non-intrusive workaround is to manually force the osd down _after_ checks have passed.
**Checklist:**
=> osd: forcefully mark an osd as down after stopping the service

srv/salt/ceph/stage/configure/default.sls
For users with maintenance windows attempting to avoid running Stage 0,
synchronize Salt files in Stage 2 as well to prevent difficult to diagnose problems.
bsc:1170752
**Checklist:**
=> Sync salt dynamic modules

srv/salt/ceph/monitoring/prometheus/exporters/node_exporter.sls
Fixes bsc#1174292
Description: Fixes and issue with an update of the node-exporter package by installing the compatible version instead of the updated one.
**Checklist:**
=> prevent installation of node_exporter update due to LTTS

srv/salt/ceph/configuration/files/ceph.conf.j2
They are no longer needed.
Fixes: bsc#1174545
Fixes #
Description:
**Checklist:**
=> ceph.conf: remove the mon_health_preluminous_compat settings

srv/salt/ceph/apparmor/default-teardown.sls
=> aa-teardown can fail if apparmor is disabled on the boot command line

srv/modules/runners/disks.py, srv/salt/_modules/dg.py
Since the blkid_api is not available, use blkid() directly.  Add a
separate command currently rather than changing disks.report.
bsc: 1171002, 1171887
**Checklist:**
=> Ignore disks with GPT headers or unavailable

srv/salt/ceph/monitoring/prometheus/files/prometheus.yml.j2
One part of the issue is that the metrics from the ceph mgr contain labels for `instance`, though, the `instance` label is also automatically populated by Prometheus. When Prometheus does that, the instance label becomes the hostname of the Ceph manager node, which is wrong. By setting `honor_labels` in the scrape configuration of `ceph-mgr` to `true`, the instances labels exported by the Prometheus manager module are preserved.
Partly fixes bsc#1175585
**Checklist:**
=> fix many-to-many not allowed in Grafana dashboard

Makefile, deepsea.spec.in, srv/modules/modules/master.py, srv/salt/ceph/ganesha/config/default.sls, srv/salt/ceph/ganesha/pool/default.sls, srv/salt/ceph/ganesha/pool/init.sls, srv/salt/ceph/ganesha/rados_config.sls, srv/salt/ceph/stage/ganesha/core/default.sls, srv/salt/ceph/stage/ganesha/default.sls, srv/salt/ceph/stage/ganesha/pool.sls
With a sufficient number of objects in a pool, the `rados -p POOL -N
ganesha ls` command can take several minutes to complete.  The side
effect is the dashboard can timeout.  Do *not* use cephfs_data nor rgw
for storing ganesha configurations.
bnc: 1172689
**Checklist:**
=> Add dedicated ganesha_config pool for dashboard

srv/modules/runners/validate.py
If a user misconfigured their fqdn like so:
```
target-00
```
[salt can't determine the `domain`](https://github.com/saltstack/salt/blob/7c0b30d9a423a4dca21c9dcaa5a35849417f5597/salt/grains/core.py#L1633-L1654
)
```python
In [2]: 'target-00'.partition('.')[::2]                                         
Out[2]: ('target-00', '')
```
[And we fail here ](https://github.com/SUSE/DeepSea/blob/04335830b8ba1630071a19fbfe400d089a139fa2/srv/salt/_modules/deepsea.py#L94-L99)
with:
`Exception: According to the 'domain' grain, the cluster does not have a DNS domain configured`
This is probably too late. Also the error message is not very descriptive.
My concern is that we break existing (working) installations that don't use SSL (yet).
Maybe raising a …
=> validate: check if domain grain is set

srv/modules/runners/net.py
Found in the field.  When `remove_subnet_list` is None, the error is 
```
File "/srv/modules/runners/net.py", line 470, in _remove_minion_exclude
remove_subnets = remove_subnet_list.split(",")
AttributeError: 'NoneType' object has no attribute 'split'
```
**Checklist:**
=> Fix case where remove_subnet_list is None

Makefile, deepsea.spec.in, srv/modules/runners/upgrade.py, srv/salt/_modules/osd.py, srv/salt/ceph/upgrade/ses7/adopt.sls, srv/salt/ceph/upgrade/ses7/files/registries.conf.j2
This adds:
* SES6->7 pre-upgrade checks to the upgrade.status runner (bsc#1174601, bsc#1174605, jsc#SES-1196)
* upgrade.ceph_salt_config, to generate JSON for later use with `ceph-salt import`
* upgrade.generate_service_specs, to genrate YAML for later use with `ceph orch apply`
* ceph.upgrade.ses7.adopt state, to be used to run `cephadm adopt` for core daemons (mon, mgr, osd)
This PR supersedes #1840 which only included the upgrade.ceph_salt_config piece. I've fixed the "time_init: disabled" thing @Martin-Weiss mentioned. I've left the bootstrap_minion in place, because when I last tested this, it seemed ceph-salt still required it (even though it should be optional now) - possibly I did something wrong with my setup, so need to re-test that part.
**Checklist:**
=> Add SES6->7 Upgrade Helpers

deepsea.spec.in
A tiny addition to 6d2687ac, needed to fix the build in IBS, which fails with:
```
... checking filelist
deepsea-[...].rpm: directories not owned by a package:
- /srv/salt/ceph/crash/files
```
For full log, see https://build.suse.de/package/live_build_log/home:tserong/deepsea/SLE_15_SP1/x86_64
Curiously, `make rpm` from the source tree seems to work just fine, and not hit this error.
=> spec: Add /srv/salt/ceph/crash/files directory

srv/salt/ceph/upgrade/ses7/adopt.sls
Note that while this causes the adopted containers to be run with --init, the user must still run `ceph config set mgr mgr/cephadm/container_init true` at some point, so that any new containers created in future are also run with --init.
Fixes https://bugzilla.suse.com/show_bug.cgi?id=1177588
=> Pass --container-init to `cephadm adopt` (bsc#1177588)

srv/modules/runners/upgrade.py
This commit changes the exported ceph-salt config to set time_server disabled, which means `ceph-salt apply` will not make any changes to whatever existing time server configuration is in place.
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1177607
=> runners/upgrade: disable time_server in ceph_salt_config (bsc#1177607)

srv/salt/_modules/mds.py, srv/salt/ceph/mds/auth/default.sls, srv/salt/ceph/mds/default.sls, srv/salt/ceph/mds/key/default.sls, srv/salt/ceph/mds/keyring/default.sls, srv/salt/ceph/mds/restart/controlled/default.sls, srv/salt/ceph/mds/restart/force/default.sls, srv/salt/ceph/mds/shutdown.sls, srv/salt/ceph/rescind/mds/default.sls, srv/salt/ceph/rescind/mds/keyring/default.sls
Description:
This pr enables deploying multiple MDS daemons per node. This is configured by adding `mds_daemons_per_node: $n` to the pillar. This can be done either globally (via ` /srv/pillar/ceph/stack/global.yml`) or only on specific MDS nodes (via one of the files in `/srv/pillar/ceph/stack/ceph/minions/`). Rescind, restart and the shirnk to update functionality can handle multiple daemons per node.
=> Add multi MDS per node feature

deepsea.spec.in
As of dde7dbe94325e4aebb4f4b876bc22cec0db43b15 [1] DeepSea only works with ceph
versions with the refactored "ceph-volume batch" command.
By making this explicit in deepsea.spec, users will not be able to install an
incompatible version combination and problematic configurations will be flagged
earlier.
[1] https://github.com/SUSE/DeepSea/pull/1854
=> spec: declare incompatibility with ceph < 14.2.13

srv/salt/ceph/rgw/dashboard.sls
When RGW is deployed with SSL according to the SES6 documentation [1],
we are ensured that rgw_init will be set to the string "default-ssl".
[1] https://documentation.suse.com/ses/6/single-html/ses-admin/#ogw-ssl-simple
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1178355
=> rgw/dashboard: use rgw_frontend_ssl_port in SSL scenario

deepsea.spec.in
This means removing deepsea will also automatically remove deepsea-cli (see https://github.com/SUSE/doc-ses/issues/816 for related discussion).
=> spec: Make deepsea-cli require deepsea

srv/salt/ceph/monitoring/grafana/create_configs.sls, srv/salt/ceph/monitoring/prometheus/default.sls
Fixes issues in using pillar values for setting custom Grafana certificates and providing additional command line flags for Prometheus (to increase retention time, for instance).
The template inside these conditions has probably never worked, as it cannot be compiled. The conditional code is only compiled if the pillar values are specified, so it didn't reveal an issue if those features weren't used, which seems to have always been the case.
**Checklist:**
=> Fix setting custom Grafana certificates and Prometheus CLI flags

srv/modules/runners/ganesha.py
Commit ab6cb716 introduced a dedicated ganesha_config pool, but ganesha.report was still trying to find ganesha config in cephfs and rgw pools.  It would of course find one of those pools, but with no ganesha config object therein, resulting in an error:
```
rados_conf:
The minion function caused an exception: Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/salt/minion.py", line 1684, in _thread_return
return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
File "/usr/lib/python3.6/site-packages/salt/executors/direct_call.py", line 12, in execute
return func(*args, **kwargs)
File "/var/cache/salt/minion/extmods/modules/ganesha.py", line 145, in get_gateway_conf_raw
raise Exception("Object conf-{} does not exist".format(gateway_id)) …
```
=> ganesha: use ganesha_config pool in ganesha.report (bsc#1179621)

srv/salt/ceph/monitoring/prometheus/default.sls, srv/salt/ceph/monitoring/prometheus/files/prometheus.yml.j2
f24acb4b changed the name of the node exporter pillar variables from "node" to "node_exporter", but missed making a matching change to the prometheus.yml config file.
This commit also fixes application of custom prometheus rule_files (there was a missing space when invoking `basename rule_file`).
Fixes https://bugzilla.suse.com/show_bug.cgi?id=1179029
=> monitoring: fix node_exporter overrides in prometheus.yml (bsc#1179029)

srv/salt/ceph/configuration/files/ceph.conf.j2
This setting is no longer necessary since doc updates from https://github.com/SUSE/doc-ses/pull/348 (see also
https://github.com/SUSE/doc-ses/issues/314#issuecomment-639432080)
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1180594
=> ceph.conf: don't disable msgr2 (bsc#1180594)

srv/modules/runners/upgrade.py
Since "cephadm bootstrap" must not be run on upgrades, these values are not
needed and, even worse, they cause ceph-salt to get confused.
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1180960
=> runners/upgrade: drop bootstrap_minion and bootstrap_mon_ip

srv/salt/ceph/updates/salt/default.sls
Implement the latest salt-minion.service restart best practice.
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1181099
=> ceph.updates.salt: restart salt-minion.service with bg=True

srv/salt/ceph/monitoring/prometheus/files/prometheus.yml.j2
Scrape configurations cannot be loaded externally by using a statement
like `include` inside the Prometheus configuration file. The
configuration management system is supposed to create the Prometheus
configuration file appropriately. By using service discovery the user
wouldn't be able to configure some details like the `scrape_interval` or
those would need to be configured separately.
This implementation enables to provide a whole block to
`/srv/pillar/ceph/stack/global.yml` under the
`monitoring:prometheus:custom_scrape_configs` hierarchy and does so by
iterating the keys and values for least implementation effort.
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1179029
=> monitoring: enable custom scrape configurations

man/deepsea-commands.7, srv/modules/runners/changed.py, srv/salt/ceph/functests/1node/restart/common.sls, srv/salt/ceph/stage/deploy/core/default.sls, srv/salt/ceph/stage/iscsi/core/default.sls, tests/unit/runners/test_changed.py
This rather large change makes DeepSea schedule all daemons for restart if global.conf has changed.  The original (unimplemented) idea is that there was going to be a tree of roles, so each individual role could depend on global.conf, so if global.conf changed, it would propagate through this tree.  Unfortunately, that was never going to work due to the way the checksum verification/generation is done.  The original implementation called changed.mon, then changed.osd, then changed.mgr in that order.  If each of those in turn were to check if the global config had changed, then that'd be true on the first call, so the mons would get their restart flag set, but would no longer be true for subsequent calls (the mgr and osd wouldn't be restarted).  So I got rid of that entire tree concept …
=> Rework config change detection to handle global.conf correctly (bsc#1181183)

srv/salt/ceph/dashboard/default.sls, srv/salt/ceph/rgw/dashboard.sls, srv/salt/ceph/stage/iscsi/dashboard.sls
Ceph Nautilus 14.2.17+ requires that user, rgw and iscsi credentials passed to `ceph dashboard` commands come via a file, rather than being specified directly as literal parameters (see https://github.com/ceph/ceph/pull/38832)
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1183600
=> Use -i to pass credentials to "ceph dashboard" commands (bsc#1183600)

srv/salt/ceph/monitoring/grafana/default.sls
Embedding Grafana graphs is allowed up to Grafana 6.1 by default and since [version 6.2](https://grafana.com/blog/2019/05/22/grafana-v6.2-released/
), embedding needs to be explicitly enabled.
Since Grafana has been updated in DeepSea from version 5.x to version 7.x, the change in the configuration is required.
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1186131
**Checklist:**
=> Allow embedding of Grafana graphs

srv/salt/ceph/functests/1node/restart/common.sls, srv/salt/ceph/restart/mds/default-sequential.sls
When restarting the MDS during stage 4, we were invoking ceph.processes to check if all processes were running.  The problem with doing this is that if you have custom global ceph configuration set up prior to initial deployment *and* are also deploying other stage 4 services which are normally deployed *after* MDS (i.e. RGW or Ganesha), the check for custom configuration changes flags all services for restart, so when ceph.processes is invoked it waits for all daemons to be running, even those which aren't yet deployed.  That was never going to work, so instead we're now only checking for MDS processes when restarting MDSes, which makes more sense than checking all processes anyway.
**Checklist:**
=> mds/restart: only check MDS processes (not all processes)

srv/salt/_modules/dg.py
This partially reverts 8199a3220f53e46e907a844321ae1c86475f9acb, which made DriveGroups ignore disks which `ceph-volume inventory` reported as "unavailable".  The problem with this is that it means that shared DB devices are listed as unavailable, which in turn means that when you replace an OSD whose DB is on a shared device, the DB of the *new* OSD doesn't get put on the shared device, and instead you end up with a standalone OSD.
One side effect of this is that when adding a new set of disks (spinners + SSDs), depending on the drive group configuration, the journals for the new disks may end up on existing SSDs (see https://bugzilla.suse.com/show_bug.cgi?id=1171002).  As best as I can tell, we can't fix both things at the same time in code, and if this latter problem recurs, the best …
=> dg: include unavailable disks (bsc#1181725)

srv/modules/runners/validate.py
Although this code seems to have been working for about 5 years, it doesn't do so anymore for me. I'm not sure what happened, but a second is insufficient now, and that reproducibly.
When changing the time to wait for a response up to two seconds, it works.
When the `-t <int>` argument is removed, a default of 5 seconds is used, so I decided to go with that.
---
So even if it turns out to be a local issue and we won't merge this change (or possibly won't create another DeepSea package to be released for SES 5), it may serve me to look the issue up if I forgot how to circumvent it or might serve as a documentation for others, who might run into it.
Note that I'm currently unable to simply `sesdev create ses5 --single-node` an SES5 …
=> SES5: Fixes no UCST response after 1 seconds

srv/modules/runners/upgrade.py, srv/salt/ceph/upgrade/ses7/adopt.sls
When using a local container registry with access credentials, these need to be specified in /srv/pillar/ceph/stack/global.yml so that the ceph container image can be pulled when adopting existing services. Here's an example of the format:
```
ses7_container_image: 192.168.121.1:5000/my/ceph/image
ses7_container_registry_auth:
registry: 192.168.121.1:5000
username: my_username_here
password: my_very_secure_password_here
```
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1181095
**Checklist:**
=> upgrade: Add ability to specify registry credentials (bsc#1181095)

srv/salt/_modules/osd.py, srv/salt/ceph/osd/restart/controlled/default.sls
When restarting OSDs, previously we were checking that the OSD processes were running (using psutil), but not that the OSDs had completely started up.  This potentially means that if an OSD took rather longer than usual to start, the restart sequence could move along to the next node, and we could end up with multiple OSDs down across multiple nodes while doing a rolling restart.
This commit adds a call to `ceph daemon osd.$OSD_ID status` for each OSD, to ensure that the OSD has finished starting up properly.  In the normal case this will add a couple of seconds per OSD to the restart process.  Worst case, it'll hit a timeout at 64 seconds and bail out, then you need to investigate why the OSD didn't come up.
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1185422
Signed-off-by: Tim …
=> Wait for OSDs to be active after restarting (bsc#1185422)

srv/salt/ceph/monitoring/prometheus/exporters/node_exporter.sls
There's a problem in /bin/fillup, where it sometimes doesn't parse multiline strings properly in sysconfig files.  This results in
corruption of /etc/sysconfig/prometheus-node_exporter when the golang-github-prometheus-node_exporter package is updated.  We can work around this by putting all the arguments on one line.  See https://bugzilla.opensuse.org/show_bug.cgi?id=1153280 and https://github.com/openSUSE/fillup/issues/1 for the underyling issue.
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1188486
=> monitoring: put node_exporter ARGS all on one line (bsc#1188486)

.pylintrc, .travis.yml, tox.ini
Commit f8a6269 switched to using generic python3, allegedly because Tumbleweed had python 3.7, not 3.6.  I assume that was true at the time, because I wrote it, but given that python 3.6 *is* currently available on Tumbleweed, perhaps I was mistaken.  Anyway, it makes the most sense to force testing with python3.6, because that's what we deploy against with SES6 on SLE 15 SP1.
This commit also:
- Forces the use of isort < 5 when running lint, because version 5 produces a pile of "module 'isort' has no attribute 'SortImports'" errors, and no actual useful lint output.
- Gets rid of the file permission checks when running in Travis CI, because Travis sets umask 002, which messes up the file permissions during `git clone`, and causes all the tests to fail.
Signed-off-by: Tim Serong …
=> Use python3.6 for tox and travis

srv/modules/runners/upgrade.py
When sorting nodes for display, the upgrade.status runner was only taking into account the nodes with roles 'master', 'mon', 'mgr', 'storage', 'mds', 'rgw', 'igw' and 'ganesha'.  It wasn't handling the 'prometheus' or 'grafana' roles.  If the latter two roles are assigned to nodes that also have one of the "main" roles, this is not a problem, but if prometheus and/or grafana are deployed on separate nodes by themselves (with no other roles), those nodes don't appear in the list of nodes to upgrade, leading one to think that everything is upgraded, when it's potentially not.
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1195366
=> Ensure upgrade.status lists nodes with non-ceph roles (bsc#1195366)

srv/modules/runners/rebuild.py, srv/salt/_modules/osd.py, tests/unit/_modules/test_osd.py, tests/unit/runners/test_rebuild.py
When running rebuild.node it waits for PGs to be in the active+clean
state.
If PGs are, for example scrubbing, the user only gets the message: "Waiting for PGs to recover..."
This branch adds extra information, showing the actual state of PGs and,
in the case that they're scrubbing, it sugests to disable scrubbing and
trying.
The return value of quiescent method has been changed to return (in addition to the return result) a message that the rebuild runner can display to the user as a warning.
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1194807
Signed-off-by: Xavi Garcia <xavi.garcia@suse.com>
=> Extra information when PGs take too long to be in active+clean state

srv/salt/ceph/upgrade/ses7/adopt.sls
This updates the OS and Ceph version checks used when upgrading from SES6. We don't want to merge this immediately - we need to wait and synchronize this with main the SES 7.1 update.
=> Update ceph.upgrade.ses7.adopt for SES 7.1

srv/modules/runners/disks.py, srv/salt/_modules/osd.py, tests/unit/_modules/test_osd.py
Previously, `salt-run rebuild.node $NODE` would override the targets specified in drive_groups.yml, and attempt to apply
*all* drive groups to the specified node (of course only the first one would succeed and the rest would likely do nothing).  This commit makes sure that only the drive groups whose configured targets actually match the specified node are applied (see https://bugzilla.suse.com/show_bug.cgi?id=1198929)
There's also a second commit in here which makes rebuild.node work if there's no PGs at all, which I hit while testing the above. This is an edge case that I have difficulty imagining anyone hitting on a real cluster, because by the time you get to rebuilding a node you're probably running a cluster with actual data in it.
=> Take drivegroup targets into account for rebuild.node (bsc#1198929)
