srv/modules/runners/validate.py

As mentioned in bsc#1000620, if the pillar data is largely
nonexistent (due to a misconfiguration in that bug),
validate.py will bail out with KeyError exceptions.  Because
it throws an exception rather than returning False in this
case, the "validate failed" state in ceph/stage/deploy.sls
doesn't trigger, and salt attempts to run all the other
deploy states which fail rather spectacularly at that point.
This commit makes validate.py cope properly with missing
keys, although some of the error text when the keys aren't
there could still be improved (empty strings get interpolated
in a couple of places).

validate.py: handle missing keys gracefully

---

deepsea.spec

In addition cleaned up globing of directories.
Signed-off-by: Owen Synge <osynge@suse.com>

Change permissions to match salt for shared directories.

---

srv/salt/ceph/packages/common_deps.sls
srv/salt/ceph/stage/prep/default.sls

stage.0: install sgdisk in all minions

---

srv/modules/runners/nettest.py
srv/salt/ceph/iperf/init.sls
srv/salt/ceph/iperf/packages-suse.sls
srv/salt/ceph/iperf/packages.sls
srv/salt/ceph/iperf/remove.sls
srv/salt/ceph/iperf/systemd-iperf.service
srv/salt/ceph/stage/iperf3.sls
srv/salt/ceph/stage/ping.sls

Add ping and iperf3 network tests.

Wip nettest

---

srv/salt/ceph/time/ntp.sls

stage.3: fix bug in sync time formula

---

deepsea.spec
srv/salt/ceph/igw/restart/default.sls
srv/salt/ceph/igw/restart/init.sls
srv/salt/ceph/mds/restart/default.sls
srv/salt/ceph/mds/restart/init.sls
srv/salt/ceph/mon/restart/default.sls
srv/salt/ceph/mon/restart/init.sls
srv/salt/ceph/osd/restart/default.sls
srv/salt/ceph/osd/restart/init.sls
srv/salt/ceph/restart/default.sls
srv/salt/ceph/restart/init.sls
srv/salt/ceph/rgw/restart/default.sls
srv/salt/ceph/rgw/restart/init.sls
srv/salt/ceph/wait/default.sls
srv/salt/ceph/wait/init.sls

Work for fate #320981

---

Makefile
deepsea.spec
srv/modules/runners/nettest.py
srv/salt/ceph/diagnose/README.md
srv/salt/ceph/diagnose/iperf3-concurrent.sls
srv/salt/ceph/diagnose/iperf3.sls
srv/salt/ceph/diagnose/ping.sls
srv/salt/ceph/iperf/ceph_diagnose_iperf_client.py
srv/salt/ceph/iperf/ceph_diagnose_iperf_client_add.sls
srv/salt/ceph/iperf/ceph_diagnose_iperf_client_remove.sls
srv/salt/ceph/iperf/init.sls
srv/salt/ceph/iperf/packages.sls
srv/salt/ceph/iperf/remove.sls

Add nettests:
ping
iperf3
iperf3-concurrent

Wip test nettests parallel

---

srv/salt/ceph/diagnose/README.md

diagnosis README: fix typos

---

README.md

Updated README.md and added a "Support" section, referring to the Wiki and mailing list.

Updated README.md (added support resources)

---

README.md
contributing.md

doc: add contribution guidelines

---

srv/salt/ceph/updates/default-zypper-kernel-default.sls

enforce kernel-default

---

Makefile
setup.py
tox.ini

..which also requires a setup.py.  Also adding the defaultest structure

Adding tox.ini

---

README.md

Signed-off-by: Lenz Grimmer <lenz@grimmer.com>

Updated README.md (fixed typo, corrected URL to contribution guidelines)

---

srv/modules/runners/validate.py

validate: remove double assignment in `get_printer`

---

README.md

Signed-Off-By: Abhishek Lekshmanan <abhishek@suse.com>

README: clarify that RGW works for single site

---

srv/modules/runners/validate.py

In certain cases it makes sense to warn the user instead of erroring
out, adding the ability for this.
Fixes: #83

validate: add ability to warn & warn when fqdn is localhost

---

srv/modules/runners/validate.py
tests/unit/_modules/test_validate.py

Refactoring validate.py to use setdefault while creating error lists

validate: use setdefault when creating error lists

---

srv/modules/runners/populate.py

populate: refactor methods to add public interface

---

srv/modules/runners/populate.py

Since it is a method in the class we need to call it with self.
otherwise we'll end up with a NameError

populate: use self while calling add_pub_interface

---

srv/modules/runners/populate.py
srv/modules/runners/push.py

fail hard if stage 2 fails to create directory

---

srv/salt/ceph/cherrypy/README
srv/salt/ceph/cherrypy/configure.sls
srv/salt/ceph/cherrypy/default.sls
srv/salt/ceph/cherrypy/files/cherrypy.conf
srv/salt/ceph/cherrypy/files/cherrypy.conf.j2
srv/salt/ceph/cherrypy/files/eauth.conf
srv/salt/ceph/cherrypy/init.sls
srv/salt/ceph/cherrypy/install.sls
srv/salt/ceph/cherrypy/start.sls

Adding salt files for configuring and installing the salt-api.

Wip cherry

---

srv/modules/runners/push.py

As we use errno in create_dirs function (else we get an exception again)

push: import errno

---

contributing.md

Signed-off-by: Lenz Grimmer <lenz@grimmer.com>

Updated URL in contributing.md to enable forking with fewer clicks.

---

srv/modules/runners/populate.py

populate: don't create role-storage directory

---

srv/salt/ceph/cherrypy/files/eauth.conf

Allow runner calls from the salt-api for admin

---

srv/modules/runners/validate.py

Ganesha validation should only fail on missing mds or rgw node if
ganesha is actually deployed.
Also adds some refactoring to simplify pillar iteration.
Fixes: #128 

validate: ganesha validation is too strict

---

srv/salt/ceph/stage/radosgw/default.sls

RGW: Add users only if rgw_configurations

---

srv/modules/runners/cephservices.py
tests/unit/runners/test_cephservices.py

Add cephservices.py, unit tests

---

srv/salt/ceph/openattic/default.sls

Enable openattic services

---

srv/modules/runners/validate.py

This PR allows the user to specify that wants to deploy a Ceph cluster in a development environment, and thus avoiding the minimum number of storage nodes restriction.
The specification of then type of environment is done using an env variable called  `DEV_ENV` 
Example: `$ DEV_ENV=true salt-run state.orch ceph.stage.deploy` will run stage 3 with the environment set to "dev".

stage 3: add "dev_env" flag to enable/disable 4 node restriction

---

Makefile
srv/modules/runners/populate.py
srv/salt/_modules/cephdisks.py
srv/salt/ceph/mines/files/mine_functions.conf
srv/salt/ceph/packages/common/default-zypper.sls
srv/salt/ceph/packages/common/default.sls
tests/unit/_modules/helpers.py
tests/unit/_modules/test_cephdisks.py
tox.ini

rewrite cephdisks / hardware detection ref #70

---

srv/modules/runners/cephservices.py
tests/unit/runners/test_cephservices.py

Correction for delay, add _timeout and unit tests

cephservices

---

srv/salt/_modules/cephdisks.py

cephdisks: fix unknown function name

---

srv/modules/runners/populate.py

Remove ganesha_members()

---

srv/modules/runners/push.py
tests/unit/runners/test_push.py
tox.ini

Also fixes non-portable import of stack-py. See #168

Add unit tests for push

---

srv/salt/ceph/ganesha/restart/default.sls
srv/salt/ceph/ganesha/restart/init.sls
srv/salt/ceph/restart/default.sls

Add restart functionality for ganesha

---

srv/salt/ceph/stage/cephfs/default.sls
srv/salt/ceph/stage/ganesha/default.sls
srv/salt/ceph/stage/iscsi/default.sls
srv/salt/ceph/stage/radosgw/default.sls

Have a graceful, quiet operation when services are not assigned

Add conditionals to service orchestrations

---

srv/modules/runners/disengage.py

Fixing check

---

Makefile
tox-pytest.ini

Only run pytests for rpm target

---

deepsea.spec

Add missing ganesha/restart entries in spec

---

srv/salt/ceph/rescind/gold/default.sls
srv/salt/ceph/rescind/gold/init.sls
srv/salt/ceph/rescind/silver/default.sls
srv/salt/ceph/rescind/silver/init.sls

Rescind: remove non-required gold and silver directory

---

contrib/wolffish/src/salt-events/salt-events.html
contrib/wolffish/src/salt-events/salt-events.js
contrib/wolffish/src/wf-auth/wf-auth.html
contrib/wolffish/src/wolffish-app/wolffish-app.html

A simple element to listen for, and disseminate salt events to any element that cares to listen.

Salt Events Element for WF

---

srv/modules/runners/ui_iscsi.py

Added docs to status, deploy, and undeploy functions

---

srv/modules/runners/benchmark.py
srv/modules/runners/ready.py
srv/modules/runners/validate.py

replace cmd.run with cmd.shell

---

srv/salt/ceph/ganesha/files/ganesha.service

NFS-Ganesha:fix syntax for service file

---

README.md

Add detailed suggestions to Salt installation and configuration to
prepare for DeepSea, and include a practical example. Clarify DeepSea
configuration by adding more information about editing
`/srv/pillar/ceph/master_minion.sls`.
Signed-off-by: Blaine Gardner <blaine.gardner@suse.com>

Add more detail to user config documentation

---

deepsea.spec

Fixes buildissues with recently added 'single-restart' feature

Fix build issues for single-restart feature 

---

Makefile
deepsea.spec
srv/modules/runners/populate.py
srv/modules/runners/validate.py
srv/salt/ceph/time/default.sls
srv/salt/ceph/time/disabled.sls
srv/salt/ceph/time/ntp/default.sls
srv/salt/ceph/time/ntp/files/ntp.conf.j2

ntp client

---

srv/salt/ceph/time/README

doc: finesse the ceph time README

---

srv/modules/runners/validate.py

This PR fixes the problem referenced in #261 

validate: ensure there is at least one storage node in dev_env mode

---

srv/modules/runners/ui-rgw.py
srv/modules/runners/ui_rgw.py
srv/pillar/ceph/rgw.sls-example
tests/unit/runners/test_ui_rgw.py

Wip ui rgw

---

srv/modules/runners/ready.py

Add apparmor check

---

Makefile
deepsea.spec

Fix missing ganesha.service file in installation and RPM generation

---

srv/modules/runners/ui_rgw.py

ui_rgw: Fix the returned port in rgw gatways URL endpoints

---

srv/salt/ceph/remove/ganesha/default.sls
srv/salt/ceph/remove/mds/default.sls

$subject + typo in mds removal

avoid empty rendering and master targeting if no ganesha role

---

tests/unit/runners/test_ui_rgw.py

Fix unit tests to supply configuration and client file

---

srv/modules/runners/validate.py

Support ceph namespace storage as well

---

srv/salt/ceph/time/ntp/default.sls

sntp needs ntp package installed first

---

Makefile
deepsea.spec
srv/salt/ceph/configuration/files/ceph.conf.d/README

Add bluestore comment, include README in rpm

---

srv/salt/ceph/rescind/rgw/default.sls

Do not remove radosgw binary from master

---

srv/modules/runners/validate.py

Now it's possible to deploy less than 3 MON setups for testing/development
Signed-off-by: Kai Wagner <kwagner@suse.com>

Added the DEV_ENV check to the monitor validation

---

CHANGELOG
deepsea.spec

Sync with buildservice

---

.gitignore

.gitignore: add junit*.xml

---

deepsea.spec

Addresses #297 and review comments from https://build.opensuse.org/request/show/496707

spec file fixes

---

srv/modules/runners/ui_ganesha.py
srv/salt/_modules/ganesha.py
srv/salt/ceph/ganesha/config/default-ui.sls
srv/salt/ceph/ganesha/config/default.sls
srv/salt/ceph/ganesha/config/init.sls
srv/salt/ceph/ganesha/install/default.sls

This PR adds the implementation of an API to manage the NFS-Ganesha exports in the form of a runner.
The PR is tagged with [WIP] because it's still lacking unit tests.

[WIP] NFS-Ganesha API runner

---

srv/modules/runners/remove.py
srv/salt/_modules/cephdisks.py
srv/salt/_modules/osd.py
srv/salt/ceph/osd/default.sls
srv/salt/ceph/rescind/storage/default.sls
srv/salt/ceph/rescind/storage/terminate/default.sls

Improvements in OSD handling, code organization and support for removing single OSDs

Wip osd remove

---

srv/salt/ceph/purge/default.sls

Terminate step is separate now, call directly

---

srv/salt/ceph/monitoring/grafana/init.sls

add promtheus data source to grafana

---

qa/README
qa/workunits/basic-health-ok.sh

This has been tested in teuthology/OVH.

qa: added basic-health-ok test script

---

qa/common/common.sh
qa/workunits/basic-health-ok.sh

This (basic-health-ok.sh) passes in teuthology

qa: move common stuff to common.sh

---

srv/modules/runners/net.py
srv/salt/_modules/multi.py

Signed-off-by: Alex Lau (AvengerMoJo) <alau@suse.com>

Add jumbo frame validation ping

---

srv/modules/runners/ui_rgw.py
tests/unit/runners/test_ui_rgw.py

Add system user_id info

---

doc/examples/policy.cfg-rolebased

Changed the formatting of the rolebased policy.cfg + oA role
Signed-off-by: Kai Wagner <kwagner@suse.com>

Changed the formatting of the rolebased policy.cfg + oA role

---

srv/modules/runners/populate.py
srv/salt/_modules/cephinspector.py

First pass at some basic hardware profile detection.
Added detection of fsid from existing cluster and overwriting cluster.yml per our TODO.

hardware profile detection, fsid overwrite

---

srv/salt/ceph/ganesha/files/ganesha.conf.j2

NFS-Ganesha: Add "Protocols" and "Transport" in ganesha.conf

---

qa/common/common.sh
qa/suites/basic/health-rgw.sh

This currently gets all the way to the end before failing due to #341.

qa: Add rgw curl test to basic suite

---

srv/modules/runners/ui_iscsi.py
tests/unit/runners/test_ui_iscsi.py

ui_iscsi: Default lrbd.conf when cache file not available

---

srv/salt/_modules/osd.py

refactor is_partitioned to use _run()

---

srv/salt/ceph/stage/prep/minion/default.sls

s/Starting/Processing/ in rolling update -> stage.0

---

srv/salt/_modules/osd.py
tests/unit/_modules/test_osd.py

OSDCOnfig unit tests

---

srv/modules/runners/validate.py

Don't validate profiles if in DEV_ENV

---

srv/modules/runners/ui_ganesha.py

Fixed handling of FQDN hostnames

---

srv/modules/runners/populate.py
srv/salt/_modules/cephinspector.py

Based atop of https://github.com/SUSE/DeepSea/pull/345. Let's merge that first, or close 345 and merge this one.

public and cluster network detection

---

srv/modules/runners/proposal.py

proposals: propose nvme-ssd proposals

---

qa/README
qa/common/common.sh
qa/suites/basic/health-mds.sh
qa/suites/basic/health-nfs-ganesha.sh
qa/suites/basic/health-ok.sh
qa/suites/basic/health-rgw.sh

It came to my attention that not everyone has jq installed :-)

qa: install jq dependency at beginning of each test

---

Makefile
deepsea.spec
srv/modules/runners/populate.py
srv/salt/_modules/cephinspector.py

populate: import admin, mon and osd bootstrap keys

---

srv/salt/_modules/osd.py

Not sure if it was left out intentionally, but it looks like it's just missing.

missing else block in no-partition branch

---

srv/salt/ceph/stage/radosgw/default.sls

radosgw: create bucket only if rgw role defined

---

srv/modules/runners/rescinded.py
srv/salt/_modules/osd.py
srv/salt/ceph/migrate/nodes/default.sls
srv/salt/ceph/osd/auth/default.sls
srv/salt/ceph/osd/files/storage.j2
srv/salt/ceph/osd/key/default.sls
srv/salt/ceph/osd/keyring/default.sls
srv/salt/ceph/redeploy/nodes/default.sls

Fixes reweight issue and partial removals

Add and use storage keyring, remove strays

---

srv/salt/_modules/packagemanager.py
srv/salt/ceph/maintenance/upgrade/minion/default.sls

packagemanager: fixup updates needed check for zypper dup

---

srv/modules/runners/status.py

Add condition to avoid uninitialized var most_common_items

---

srv/salt/ceph/configuration/files/ceph.conf.d/README

Reflect https://github.com/ceph/ceph/pull/15177

doc: bluestore no longer experimental

---

srv/salt/ceph/configuration/files/ceph.conf.j2
srv/salt/ceph/configuration/files/ceph.conf.rbd

configuration: add RBD specific configuration template

---

srv/salt/ceph/mon/files/keyring.j2

Added caps mgr 'allow *' to the admin keyring

---

srv/modules/runners/populate.py

populate: only process minion interfaces with inet entries

---

srv/salt/ceph/stage/removal/default-remove.sls

Move pool removal to alternate default

---

srv/salt/_modules/osd.py

resolves #406 see also for details

specify --filestore as ceph-disks default changed

---

Makefile
deepsea.spec
srv/modules/runners/push.py
srv/salt/ceph/migrate/policy/default.sls
srv/salt/ceph/migrate/policy/init.sls

Add policy migration

---

srv/salt/ceph/stage/prep/master/default-no-update-no-reboot.sls
srv/salt/ceph/stage/prep/master/default-no-update-reboot.sls
srv/salt/ceph/stage/prep/master/default-update-no-reboot.sls
srv/salt/ceph/stage/prep/minion/default-no-update-no-reboot.sls
srv/salt/ceph/stage/prep/minion/default-no-update-reboot.sls
srv/salt/ceph/stage/prep/minion/default-update-no-reboot.sls

An alternative solution to https://github.com/SUSE/DeepSea/pull/387 based off of https://github.com/SUSE/DeepSea/issues/368

Alternative stage 0 in speparate files

---

srv/salt/ceph/igw/default-nopool.sls
srv/salt/ceph/igw/default.sls
srv/salt/ceph/igw/files/lrbd.conf.j2

Create demo image as part of iSCSI setup

---

srv/modules/runners/populate.py

populate: ensure firewall/apparmor are disabled

---

deepsea.spec

rpm: Fixing install of sharedsecret.conf file

---

srv/salt/_modules/wait.py

https://github.com/ceph/ceph/pull/15643/

Support upstream health data structure change

---

qa/common/common.sh
qa/common/helper.sh
qa/suites/basic/health-mds.sh
qa/suites/basic/health-nfs-ganesha.sh
qa/suites/basic/health-ok.sh
qa/suites/basic/health-rgw.sh
qa/suites/ceph-test/librbd.sh

This passes `basic/health-ok` in teuthology.

qa: Exuberantly refactor the integration test suite

---

Makefile
deepsea.spec
srv/salt/ceph/monitoring/grafana/files/ceph-cluster.json
srv/salt/ceph/monitoring/grafana/files/ceph-osd.json
srv/salt/ceph/monitoring/grafana/files/ceph-pools.json
srv/salt/ceph/monitoring/grafana/files/ceph-rbd.json
srv/salt/ceph/monitoring/grafana/files/node.json
srv/salt/ceph/monitoring/grafana/init.sls
srv/salt/ceph/monitoring/prometheus/exporters/files/rbd.sh
srv/salt/ceph/monitoring/prometheus/exporters/files/smartmon.sh
srv/salt/ceph/monitoring/prometheus/exporters/node_exporter.sls
srv/salt/ceph/monitoring/prometheus/exporters/rbd_exporter.sls
srv/salt/ceph/monitoring/prometheus/update_service_discovery.sls
srv/salt/ceph/stage/deploy/default.sls

Furthermore this PR restructures the dashboard deployment. Dashboards are now added via the grafana http api instead of pointing grafana at a json file. This means that the url of all dashboards will change.

add smartmon and rbd monitoring

---

Makefile
deepsea.spec
srv/modules/runners/populate.py
srv/salt/_modules/cephinspector.py
srv/salt/ceph/configuration/files/ceph.conf.d/README
srv/salt/ceph/configuration/files/ceph.conf.j2
srv/salt/ceph/remove/mgr/default.sls
srv/salt/ceph/remove/mgr/init.sls
srv/salt/ceph/stage/removal/default-remove.sls
srv/salt/ceph/stage/removal/default.sls

These few pieces weren't included in #398.

Finish remaining mgr minor works (engulf, remove, mgr.conf)

---

README.md

README: add travis build status

---

Makefile
deepsea.spec
srv/salt/ceph/stage/benchmark/default.sls
srv/salt/ceph/stage/benchmark/init.sls

benchmarks: fix spec file; fix Makefile; remove unused stage file

---

doc/examples/policy.cfg-generic
doc/examples/policy.cfg-regex
doc/examples/policy.cfg-rolebased
srv/modules/runners/populate.py
srv/modules/runners/proposal.py
srv/salt/ceph/stage/discovery/default.sls

This PR adds some final changes to the proposal runner to improve usability. Furthermore it becomes the new default for stage 1.
The example policy.cfg files are changed to use the default profile created by the new runner.

Propose custom ratios

---

qa/common/common.sh

qa: adjust qa policy.cfg to new storage profile name

---

srv/salt/ceph/monitoring/grafana/files/ceph-cluster.json
srv/salt/ceph/monitoring/grafana/files/ceph-osd.json

monitoring: fix query format for status panels

---

srv/salt/_modules/osd.py

1)Don't use old style exceptions
2)Catch a bug with only osds+journal deployments

Exception handling and None checks in osd+journal scenarios

---

qa/common/common.sh
qa/common/helper.sh
srv/salt/ceph/mon/files/keyring.j2
srv/salt/ceph/mon/key/default.sls

Ensure /etc/ceph/ceph.client.admin.keyring matches the actual admin keyring caps

---

srv/salt/ceph/monitoring/prometheus/exporters/node_exporter.sls
srv/salt/ceph/monitoring/prometheus/exporters/rbd_exporter.sls

Better to redirect std_err to /dev/null

exporter cron jobs: don't spam system log

---

qa/common/common.sh
qa/suites/basic/health-igw.sh
srv/salt/ceph/igw/import/default.sls

Note: merge https://github.com/SUSE/ceph/pull/136 when this is merged.

qa: add iSCSI gateway smoke test

---

srv/modules/runners/ready.py
tests/unit/runners/test_ready.py

Allow custom chains in firewall check, add unit tests

---

srv/salt/ceph/monitoring/grafana/files/ceph-pools.json

Fix typo in Grafana 'Ceph - Pools' dashboard.

---

srv/modules/runners/validate.py
srv/salt/ceph/stage/services/default.sls

finish refactor, add openattic check

Wip validate

---

srv/salt/ceph/remove/rgw/default.sls

Remove default.rgw.meta too

---

srv/salt/ceph/igw/config/default.sls

Fixes: https://github.com/SUSE/DeepSea/issues/498

igw: enable rbd application for iscsi-images pool

---

srv/pillar/ceph/openattic.sls-example
srv/salt/ceph/rescind/openattic/default-drop.sls

Migrate example to alternate default

---

srv/salt/ceph/openattic/oaconfig/default.sls

Icinga is no longer a dependency for openATTIC

---

Makefile
deepsea.spec
man/deepsea.commands.7

Add command reference

---

Makefile
deepsea.spec

Do I need to add the rgw example in pillar somewhere as well?

add rgw-ssl files to Make install

---

srv/salt/ceph/stage/prep/master/default-no-update-no-reboot.sls
srv/salt/ceph/stage/prep/master/default-no-update-reboot.sls
srv/salt/ceph/stage/prep/master/default-update-no-reboot.sls
srv/salt/ceph/stage/prep/master/default.sls

Enable salt-api

---

srv/salt/ceph/monitoring/grafana/files/ceph-cluster.json
srv/salt/ceph/monitoring/grafana/files/ceph-osd.json

grafana: make some dashboards easier to read on smaller screens

---

srv/salt/ceph/stage/prep/master/default-no-update-no-reboot.sls
srv/salt/ceph/stage/prep/master/default-no-update-reboot.sls
srv/salt/ceph/stage/prep/master/default-update-no-reboot.sls
srv/salt/ceph/stage/prep/master/default.sls

This reverts commit 10819044aed3fcff2ec3d76d5eb06776f4c31669.

Revert "Enable salt-api"

---

README.md

Snagged that description from a suggested improvement for the SES manual.
Signed-off-by: Lenz Grimmer <lgrimmer@suse.com>

README.md: clarified the meaning of the `DEV_ENV` setting

---

qa/common/common.sh
qa/common/nfs-ganesha.sh
qa/common/rgw.sh
qa/suites/basic/health-nfs-ganesha.sh

This completes the implementation of the basic test matrix - see "Test Matrix" section in https://gitlab.suse.de/ceph/documentation/blob/master/testing/plan/nfs_ganesha.rst

qa: nfs-ganesha: implement RGW and CephFS+RGW FSAL test cases

---

srv/modules/runners/populate.py

When importing existing pre-Luminous clusters, there won't be any mgr daemons
running, so role-mgr won't be assigned.  Since mgr is required for Luminous,
it seems reasonable to automatically assign role-mgr to the mons.

populate: apply role-mgr to mons if no mgrs found on import (bsc#1050551)

---

deepsea.spec

Modules need python-rados

---

srv/salt/ceph/rescind/openattic/default.sls

Do not stop apache2 when removing openATTIC

---

srv/salt/ceph/migrate/policy/default.sls

Refresh pillar after migrating

---

qa/common/common.sh

qa: common: bail out if DeepSea not installed

---

Makefile
qa/common/common.sh
qa/common/rgw.sh
qa/suites/basic/health-rgw-ssl.sh
srv/salt/ceph/stage/discovery/default.sls

Creates the rgw ssl configuration and does a curl test with no ssl
verification

[DNM] wip: qa: add basic rgw ssl deployment tests

---

qa/README
qa/README.wip
qa/common/common.sh
qa/suites/basic/health-ok.sh

Along with some README tweaks.

qa: add Ceph version sanity test to basic/health-ok.sh

---

srv/modules/runners/validate.py
srv/salt/ceph/salt-api/start.sls
srv/salt/ceph/stage/prep/master/default-no-update-no-reboot.sls
srv/salt/ceph/stage/prep/master/default-no-update-reboot.sls
srv/salt/ceph/stage/prep/master/default-update-no-reboot.sls
srv/salt/ceph/stage/prep/master/default.sls

Enable salt-api, add validation

---

srv/salt/ceph/monitoring/grafana/files/ceph-rgw-users.json

Modify the Grafana 'Ceph - Object Gateway users' dashboard. This PR is related to https://tracker.openattic.org/browse/OP-2214.

Modify Grafana 'Ceph - Object Gateway users' dashboard.

---

srv/modules/runners/push.py

Call proposal function for smoother workflow

---

srv/salt/ceph/maintenance/upgrade/minion/default.sls

Carryover from there: https://github.com/SUSE/DeepSea/commit/66aee0c5c5b8e967f3652cd78b2d4f285a2ba6f9

hardfail was changed to exception. Failhard is missing

---

Makefile
deepsea.spec
man/deepsea.commands.7
srv/salt/ceph/rescind/mds-nfs/default.sls
srv/salt/ceph/rescind/mds-nfs/init.sls
srv/salt/ceph/rescind/rgw-nfs/default.sls
srv/salt/ceph/rescind/rgw-nfs/init.sls

Remove rgw-nfs role

---

doc/examples/policy.cfg-rolebased

Signed-off-by: Kai Wagner <kwagner@suse.com>

Added nfs-ganesha role to the rolebased example file

---

Makefile
deepsea.spec
qa/README

Fixes: https://github.com/SUSE/DeepSea/issues/543

build/ops: package the qa scripts

---

srv/modules/runners/populate.py

populate: check validity of deepsea_minions before proceeding with engulf

---

srv/salt/_modules/cephinspector.py

cephinspector: refactor engulf to handle bluestore

---

srv/modules/runners/push.py

When migrating from filestore to bluestore on policy files that were
produced during engulf, the policy files are already in the new data
structure.

push: handle new policy format during migration

---

srv/salt/ceph/configuration/files/ceph.conf-shared.j2
srv/salt/ceph/remove/mon/default.sls

Fix ceph.remove.mon and shared ceph.conf

---

srv/modules/runners/populate.py

populate: 'from validate import' fails on teuthology

---

srv/salt/_modules/public.py

Handle OVH setup of multiple networks in a string

---

srv/salt/ceph/monitoring/grafana/files/ceph-cluster.json
srv/salt/ceph/monitoring/grafana/files/ceph-osd.json
srv/salt/ceph/monitoring/grafana/files/ceph-pools.json
srv/salt/ceph/monitoring/grafana/files/ceph-rbd.json
srv/salt/ceph/monitoring/grafana/files/ceph-rgw-users.json
srv/salt/ceph/monitoring/grafana/files/node.json
srv/salt/ceph/monitoring/prometheus/exporters/files/rbd.sh

- Several fixes and improvements to dashboards
- Allow deployment of updated dashboards
- Improve rbd-exporter to monitor rbd images in all pools

Monitoring updates

---

srv/modules/runners/proposal.py

proposal runner: add more details to help text

---

srv/modules/runners/advise.py
srv/salt/ceph/stage/configure/default.sls

Inform admin about networks

---

srv/salt/ceph/configuration/create/default-shared.sls
srv/salt/ceph/configuration/create/default.sls
srv/salt/ceph/stage/configure/default.sls
srv/salt/ceph/stage/deploy/default.sls

Fix regeneration of ceph.conf, keep states in Stage 3

---

srv/modules/runners/advise.py

Remove loop to correct and simplify

---

srv/modules/runners/select.py
srv/modules/runners/ui_rgw.py
srv/salt/ceph/configuration/files/ceph.conf.j2
tests/unit/runners/test_ui_rgw.py

Also, allow admin to override snippets in ceph.conf.d.

Fix rgw config generation in ceph.conf

---

srv/modules/runners/select.py
srv/salt/ceph/configuration/files/ceph.conf.j2

Handle no match with variable array

---

srv/modules/runners/select.py
srv/salt/ceph/configuration/files/ceph.conf.j2
srv/salt/ceph/configuration/files/ceph.conf.rgw
srv/salt/ceph/configuration/files/ceph.conf.rgw-ssl

The ceph.conf will have rgw sections if
any minion has the rgw role OR
rgw_configurations is set and minions have those roles

Handle missing combination

---

srv/modules/runners/benchmark.py
srv/pillar/ceph/benchmarks/config.yml
srv/pillar/ceph/benchmarks/fio/rw_staggered_dirs.yml
srv/pillar/ceph/benchmarks/templates/rw_staggered_dirs.j2
srv/salt/ceph/benchmarks/cephfs.sls
srv/salt/ceph/cephfs/benchmarks/mount.sls

- support custom cephfs mount options
- support per-client fio job templates

benchmarking improvements

---

srv/modules/runners/populate.py

Fix corner case with unassigned minions

---

srv/salt/ceph/configuration/files/ceph.conf.rgw
srv/salt/ceph/configuration/files/ceph.conf.rgw-ssl

Resolves: #616
Signed-off-by: Marc Koderer <marc.koderer@sap.com>

Remove blanks in rgw section

---

srv/modules/runners/populate.py

populate: fix local client call to support compound expressions

---

qa/common/common.sh
qa/common/rgw.sh
qa/suites/basic/health-ok-encrypted.sh

[Tests] Deployment of OSDS on encrypted disks

qa: Adding tests for encrypted disks

---

.gitignore

Add ctags file to .gitignore

---

srv/salt/ceph/monitoring/prometheus/exporters/node_exporter.sls
srv/salt/ceph/monitoring/prometheus/exporters/rbd_exporter.sls

Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1058502

rbd_exporter: make cron dependency explicit

---

srv/pillar/ceph/deepsea_minions.sls

Add another Salt target example

---

Makefile

makefile: fix non-interactive zypper option

---

Makefile
srv/pillar/ceph/deepsea_minions.sls
srv/salt/ceph/monitoring/grafana/files/ceph-rgw.json
srv/salt/ceph/monitoring/prometheus/exporters/node_exporter.sls
srv/salt/ceph/monitoring/prometheus/exporters/rbd_exporter.sls

Add some 'Top 10' dashboard widgets.
See https://tracker.openattic.org/browse/OP-2676 for more information.

Display 'Top 10' stats in the Grafana RGW dashboard (OP-2676)

---

qa/common/common.sh
qa/suites/basic/health-ok.sh
qa/suites/basic/health-openattic.sh

References: https://bugzilla.suse.com/show_bug.cgi?id=1051598

qa: common: test ceph-osd@$ID.service runtime enablement

---

srv/salt/ceph/monitoring/prometheus/exporters/files/rbd.sh
srv/salt/ceph/monitoring/prometheus/exporters/files/smartmon.sh

moitoring: lock cron based exporters against overlapping runs

---

srv/salt/ceph/monitoring/prometheus/exporters/files/rbd.sh
srv/salt/ceph/monitoring/prometheus/exporters/files/smartmon.sh

monitoring: log messages to stderr

---

srv/salt/ceph/monitoring/prometheus/exporters/files/rbd.sh

monitoring: run rbd exporter only on fast-diff enabled images

---

cli/monitors/terminal_outputter.py

This PR fixes a bug reported by @tserong that occurred while outputting the failure summary.
The stack trace of the bug was:
```
Failures summary:
ceph.monitoring (/srv/salt/ceph/monitoring):
admin.ceph:
grafana: Unable to run command '['rpm', '-qa', '--queryformat', '%{NAME}_|-%{VERSION}_|-%{RELEASE}_|-%|EPOCH?{%{EPOCH}}:{}|\\n']' with the context '{'timeout': None, 'with_communicate': True, 'shell': False, 'bg': False, 'stderr': -2, 'env': {'LANG': 'en_US.UTF-8', 'LC_NUMERIC': 'C', 'NOTIFY_SOCKET': '/run/systemd/notify', 'LC_MESSAGES': 'C', 'LC_IDENTIFICATION': 'C', 'LC_MONETARY': 'C', 'DEBIAN_FRONTEND': 'noninteractive', 'LC_COLLATE': 'C', 'LC_CTYPE': 'C', 'LC_ADDRESS': 'C', 'LC_MEASUREMENT': 'C', 'LC_TELEPHONE': 'C', 'LC_PAPER': 'C', 'LC_NAME': 'C', 'PATH': …
```

cli: fix failure output of substates when no state id is present

---

cli/stage_parser.py

Some runners are executed during jinja evaluation of SLS files. If these runners have side-effects such has create/modify a file in the filesystem, the file is created with the current process user as the owner.
When running the stages with the `salt-run`command, Salt will execute the runners with the "salt" user. Therefore, deepsea-cli must also run the stage parsing phase with the "salt" user.

cli: run stage parsing phase as "salt" user

---

cli/__main__.py
cli/common.py
cli/config.py
cli/deepsea.py
cli/stage_parser.py

The existing root checking procedure was too conservative. Even `--help` messages were not possible to see if the user was not root.
This PR fixes the above problem.

cli: Fixes root privileges checking

---

srv/salt/ceph/monitoring/grafana/files/node.json

node dashboard: fix networ io legend and remove io time graph

---

srv/modules/runners/populate.py

Signed-off-by: Marc Koderer <marc.koderer@sap.com>

Fix missing newline in populate.py

---

cli/common.py
cli/monitors/terminal_outputter.py

cli: Use ASCII when no UTF-8 glyphs are supported

---

srv/salt/ceph/sysctl/default.sls

Fix destination filename

---

srv/salt/_modules/osd.py
srv/salt/ceph/packages/common/default.sls
srv/salt/ceph/stage/prep/minion/default-no-update-no-reboot.sls
srv/salt/ceph/stage/prep/minion/default-no-update-reboot.sls
srv/salt/ceph/stage/prep/minion/default-update-no-reboot.sls
srv/salt/ceph/stage/prep/minion/default.sls

Correct package dependency, remove error message

---

srv/salt/_modules/multi.py

Remove redundant error message

---

srv/salt/_modules/cephdisks.py
tests/unit/_modules/test_cephdisks.py

Check returncode, fallback to default detection

---

srv/modules/runners/populate.py
srv/modules/runners/validate.py
srv/salt/_modules/cephimages.py
srv/salt/_modules/cephinspector.py

Replace tabs with spaces

---

Makefile
deepsea.spec

Fix Makefile, spec file for man installation

---

Makefile

Add subvolume to Makefile

---

Makefile
deepsea.spec
man/deepsea-commands.7
man/deepsea-stages.7

Man page touchups, Makefile corrections

---

srv/salt/ceph/stage/prep/master/default-no-update-no-reboot.sls
srv/salt/ceph/stage/prep/master/default-no-update-reboot.sls
srv/salt/ceph/stage/prep/master/default-update-no-reboot.sls
srv/salt/ceph/stage/prep/master/default.sls

Swap first steps, give salt-api more time

---

srv/salt/_modules/osd.py

Running osd.remove always works.  Running six osd.remove as part of
an orchestration fails in interesting ways.  One process fails to
terminate in time with a SIGKILL.  NVMe devices register as not
existing, but are on a second check.  Lastly, the grains only need
one matching device name.

Fix timing, retry, multiple device match for removing OSDs

---

srv/salt/ceph/stage/discovery/default.sls
srv/salt/ceph/stage/prep/master/default-no-update-no-reboot.sls
srv/salt/ceph/stage/prep/master/default-no-update-reboot.sls
srv/salt/ceph/stage/prep/master/default-update-no-reboot.sls
srv/salt/ceph/stage/prep/master/default.sls

Moved salt-api validation from stage 0 to stage 1

---

qa/common/helper.sh

qa: examine exit status when "deepsea stage" completes

---

srv/modules/runners/benchmark.py

Signed-off-by: Mohamad Gebai <mgebai@suse.com>

benchmarks: use client_glob for baseline benchmark

---

Makefile
deepsea.spec
srv/salt/_modules/osd.py
srv/salt/ceph/osd/default.sls
srv/salt/ceph/osd/grains/default.sls
srv/salt/ceph/osd/grains/init.sls
srv/salt/ceph/stage/deploy/default.sls

Update grains unconditionally

---

srv/salt/ceph/openattic/default.sls

service openattic-rpcd doesn't exist

disable openattic-rpcd

---

cli/monitor.py

cli: Fix monitor Stage#start_step return values

---

Makefile
deepsea.spec

It really starts to get funny -> ref https://github.com/SUSE/DeepSea/pull/746

Adding remaining bits to makefile/spec from package.remove part

---

man/deepsea-commands.7

[doc] add changed.X commands to man page

---

man/deepsea.1

man deepsea.commands needs to be man deepsea-commands

Fix ref to deepsea-commands page

---

srv/salt/ceph/stage/cephfs/default.sls

restart mds if config changed on stage.4

---

srv/salt/_modules/rgw.py

* Check if the user already exists before it is created, otherwise the JSON file is overwritten with empty content. This situation occurs if the users deploys his cluster multiple times via DeepSea.
* If it already exist, take care that the JSON file exists. Create it if necessary. This situation happens when the user was created manually beforehand.

Improve rgw.add_users()

---

srv/modules/runners/validate.py
srv/salt/ceph/time/ntp/default.sls
srv/salt/ceph/time/ntp/files/ntp.conf.j2

Support for multiple ntp servers in ntp.conf

---

README.md
salt.md

Wip saltconf

---

.travis.yml

Enable lint checking

---

srv/salt/_modules/cephdisks.py

& increase log verbosity to simplify debugging. See #758 
Resolves: #771 

Add db/wal/journal idents for encrypted disks in cephdisks.py

---

srv/modules/runners/advise.py
srv/salt/ceph/maintenance/upgrade/minion/default.sls

Safety net for a failed engulfment

---

srv/modules/runners/populate.py

populate: explicitly import validate runner

---

README.md

Added instructions on how to configure `/srv/pillar/ceph/deepsea_minions.sls` to the installation instructions.

Added note about configuring deepsea_minions to README.md

---

srv/salt/_modules/osd.py
tests/unit/_modules/test_osd.py

Fix is_prepared

---

srv/salt/ceph/monitoring/grafana/files/node.json

Resolves: #801
Signed-off-by: Marc Koderer <marc.koderer@sap.com>

Remove /var filter in Grafana node view

---

srv/salt/ceph/monitoring/prometheus/exporters/ceph_rgw_exporter/default.sls

This PR will fix the slspath issue in #805 .

Replace slspath with absolute file path.

---

qa/common/rgw.sh
qa/suites/basic/health-rgw.sh

qa-rgw: added rgw system user validation

---

srv/salt/ceph/stage/removal/default.sls

stage/remove: fail hard if osd drain fails to prevent data loss

---

srv/modules/runners/ui_iscsi.py
srv/salt/_modules/iscsi.py

This PR introduces the support for deploying and undeploying the lrbd iSCSI configuration on individual iSCSI gateways.
It also enhances the status information retrieved from each gateway.

ui_iscsi: support individual management of iSCSI gateways

---

srv/modules/runners/select.py

Correct variable name

---

srv/modules/runners/changed.py

attempt to fix the linter

---

Makefile
deepsea.spec
setup.py
srv/modules/runners/deepsea.py

Addressing oA version requirement

version packaging

---

srv/salt/_modules/cephdisks.py

backport of #774 
(cherry picked from commit ee5dad9d0715ac4211152816dcc5c58e157f0f3c)
That's a candidate for a more thorough review. Lot's of lint changes..

[backport] Add db/wal/journal idents for encrypted disks

---

Makefile
deepsea.spec
setup.py
srv/modules/runners/deepsea.py

version packaging
backport of #854 

[backport] Wip backport 854

---

srv/salt/ceph/packages/default.sls
srv/salt/ceph/stage/deploy/core/default.sls

stage 3: don't update ceph packages, only install

---

Makefile

* let sed actually write that file
* generate setup.py in the repo dir
* pycompile before building (not sure on that one)

fix make rpm

---

Makefile
deepsea.spec
srv/salt/_modules/cephprocesses.py
srv/salt/ceph/processes/admin/default.sls
srv/salt/ceph/processes/admin/init.sls
srv/salt/ceph/processes/ganesha/default.sls
srv/salt/ceph/processes/ganesha/init.sls
srv/salt/ceph/processes/igw/default.sls
srv/salt/ceph/processes/igw/init.sls
srv/salt/ceph/processes/mds/default.sls
srv/salt/ceph/processes/mds/init.sls
srv/salt/ceph/processes/mgr/default.sls
srv/salt/ceph/processes/mgr/init.sls
srv/salt/ceph/processes/mon/default.sls
srv/salt/ceph/processes/mon/init.sls
srv/salt/ceph/processes/openattic/default.sls
srv/salt/ceph/processes/openattic/init.sls
srv/salt/ceph/processes/osd/default.sls
srv/salt/ceph/processes/osd/init.sls
srv/salt/ceph/processes/rgw/default.sls
srv/salt/ceph/processes/rgw/init.sls
srv/salt/ceph/restart/ganesha/lax/default.sls
srv/salt/ceph/restart/igw/lax/default.sls
srv/salt/ceph/restart/mds/lax/default.sls
srv/salt/ceph/restart/mgr/lax/default.sls
srv/salt/ceph/restart/mon/lax/default.sls
srv/salt/ceph/restart/openattic/lax/default.sls
srv/salt/ceph/restart/osd/lax/default.sls
srv/salt/ceph/restart/rgw/lax/default.sls

backport of #868 
(cherry picked from commit f007f750aaa0b1bff119f1d1e5fae591b0fa5b03)

[backport] allow indipendent service checks

---

srv/modules/runners/cephprocesses.py

backport of #875
(cherry picked from commit b7d1305)
(cherry picked from commit c9c4da8)

[backport] pass role arg as kwargs to match process the requested role 

---

srv/salt/ceph/monitoring/grafana/files/ceph-rgw-users.json
srv/salt/ceph/monitoring/grafana/files/ceph-rgw.json
srv/salt/ceph/monitoring/prometheus/exporters/ceph_rgw_exporter/cron/default-disable-bucket-metrics.sls
srv/salt/ceph/monitoring/prometheus/exporters/ceph_rgw_exporter/files/ceph_rgw.py

backport of #847 
(cherry picked from commit 2250895)
(cherry picked from commit e6c51bd)

[backport] Refactor Prometheus RGW exporter #847

---

qa/common/common.sh

netstat is going away in SLE15

qa: replace netstat with ss

---

qa/suites/basic/health-igw.sh
qa/suites/basic/health-mds.sh
qa/suites/basic/health-nfs-ganesha.sh
qa/suites/basic/health-ok.sh
qa/suites/basic/health-openattic.sh
qa/suites/basic/health-rgw.sh
qa/suites/ceph-test/librbd.sh
qa/suites/ceph-test/pynfs.sh

The scripts were not recognizing "--help", for example. Also added "--cli"
option to pynfs.sh.
Backport: https://github.com/SUSE/DeepSea/pull/899

qa: test script fixes needed to revive pynfs.sh

---

srv/modules/runners/push.py

add exception for mailformed policy.cfg

---

qa/suites/basic/health-igw.sh
qa/suites/basic/health-mds.sh
qa/suites/basic/health-nfs-ganesha.sh
qa/suites/basic/health-ok.sh
qa/suites/basic/health-openattic.sh
qa/suites/basic/health-rgw.sh
qa/suites/ceph-test/librbd.sh
qa/suites/ceph-test/pynfs.sh

Backport of https://github.com/SUSE/DeepSea/pull/898
Do not merge until that one goes in and the cherry-picks have been double checked.

SES5 backport: qa: test script fixes needed to revive pynfs.sh

---

srv/salt/_modules/rgw.py

Check if valid access key/secret key before calling s3connect

---

qa/common/common.sh
qa/suites/basic/health-ok.sh

qa: fixes for rados_write_test

---

qa/common/common.sh
qa/common/json.sh
qa/suites/basic/health-igw.sh
qa/suites/basic/health-mds.sh
qa/suites/basic/health-nfs-ganesha.sh
qa/suites/basic/health-openattic.sh
qa/suites/ceph-test/pynfs.sh

[SES5] qa: pre-create pools before running Stage 4

---

deepsea.spec.in
srv/salt/ceph/rescind/benchmark-blockdev/default.sls
srv/salt/ceph/rescind/benchmark-blockdev/init.sls

Fixes: https://github.com/SUSE/DeepSea/issues/932
Signed-off-by: David Disseldorp <ddiss@suse.de>

benchmark-blockdev: add rescind stub

---

srv/salt/_modules/rgw.py

Check if valid access key/secret key before calling

---

srv/salt/_modules/osd.py
tests/unit/_modules/test_osd.py

Handle missing wal/db

---

srv/salt/ceph/monitoring/prometheus/exporters/files/smartmon.sh
srv/salt/ceph/monitoring/prometheus/exporters/node_exporter.sls

I have not yet tested the this for lack of a suitable test environment but will do so. If anyone wants to test drive this...feel free.

fix updated node exporter

---

srv/salt/_modules/osd.py

Include /dev/disk/by-id/scsi*

---

srv/salt/ceph/monitoring/prometheus/exporters/node_exporter.sls

monitoring/node_exporter: add switch depending on node_exporter version

---

srv/modules/runners/validate.py

correct workflow for deepsea_minion setting

---

srv/salt/ceph/stage/prep/master/default-no-update-no-reboot.sls
srv/salt/ceph/stage/prep/master/default-no-update-reboot.sls
srv/salt/ceph/stage/prep/master/default-update-no-reboot.sls
srv/salt/ceph/stage/prep/master/default.sls

[backport][SES5] Sync modules before deploying salt-api

---

CHANGELOG

Fixes # None
Description:
We need to provide an email address in order to get the package merged in the buildservice.

sanitize CHANGELOG

---

srv/salt/_modules/osd.py
tests/unit/_modules/test_osd.py

Check for WAL/DB present but not configured

---

srv/modules/runners/populate.py

This removes the assumption in the engulfer that there can be no more
than one public or cluster network.  Without this change, running engulf
on a cluster with (e.g.) public_network = 10.27.21.0/24, 10.27.20.0/24
will result in the following error:
[ERROR   ] Failed to determine cluster's public_network.
[ERROR   ] Failed to replace derived public_network with public_network
of existing cluster.
Note that this still leaves the public_network and cluster_network settings
as strings in the pillar data (changing the pillar data to be an array would
have been somewhat more invasive).
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1076010
Fixes: https://github.com/SUSE/DeepSea/issues/582

populate: support multiple public, cluster networks in engulf (bsc#1076010)

---

qa/suites/basic/health-ok.sh

Depends on #1006 
Description:
A 'smoke-test' version of health-ok by adding '--mini' switch that skips:
* Re-run stage.0
* restart services
* conf change
* verification of restarted services

Add a --mini switch to the health-ok suite

---

deepsea.spec.in
qa/common/common.sh
qa/common/nfs-ganesha.sh
qa/common/rgw.sh

[SES5] qa: run zypper refresh in try/wait loop

---

srv/modules/runners/validate.py

There are some issues with `ceph_version`, will try to address them in this PR.

validate: ceph_version improvements

---

Makefile
deepsea.spec.in
srv/modules/runners/ready.py
srv/salt/ceph/apparmor/complain.sls
srv/salt/ceph/apparmor/disable.sls
srv/salt/ceph/apparmor/files/ceph.d/common
srv/salt/ceph/apparmor/files/usr.bin.ceph-mds
srv/salt/ceph/apparmor/files/usr.bin.ceph-mgr
srv/salt/ceph/apparmor/files/usr.bin.ceph-mon
srv/salt/ceph/apparmor/files/usr.bin.ceph-osd
srv/salt/ceph/apparmor/files/usr.bin.radosgw
srv/salt/ceph/apparmor/init.sls

(cherry picked from commit 55668b7c7b9f6cafd06f8421fb53a3864316272a)

apparmor: add initial profiles

---

srv/modules/runners/validate.py

Fixes #1032 
Description:
See issue

Fix bool kv subscription issue (regression from #982)

---

srv/salt/ceph/redeploy/nodes/init.sls

Correct init variable

---

srv/salt/_modules/osd.py
tests/unit/_modules/test_osd.py

[backport][SES5] Handle missing wal/db, add unit tests

---

srv/salt/_modules/osd.py

[backport][SES5] Include /dev/disk/by-id/scsi*

---

qa/suites/basic/health-ok.sh

[backport][SES5] Add a --mini switch to the health-ok

---

srv/salt/ceph/redeploy/nodes/init.sls

[backport][SES5] Correct init variable

---

srv/salt/_modules/osd.py
tests/unit/_modules/test_osd.py

[backport][SES5] Check for WAL/DB present but not configured

---

Makefile
deepsea.spec.in
srv/salt/ceph/smoketests/keyrings/init.sls
srv/salt/ceph/tests/keyrings/README
srv/salt/ceph/tests/keyrings/admin.sls
srv/salt/ceph/tests/keyrings/igw.sls
srv/salt/ceph/tests/keyrings/init.sls
srv/salt/ceph/tests/keyrings/mds.sls
srv/salt/ceph/tests/keyrings/mgr.sls
srv/salt/ceph/tests/keyrings/mon.sls
srv/salt/ceph/tests/keyrings/rgw.sls
srv/salt/ceph/tests/keyrings/storage.sls

Initial verification that keyrings work.  Some check restrictions.

Add keyring smoketest

---

Makefile
deepsea.spec.in
srv/salt/ceph/rescind/configuration/default.sls
srv/salt/ceph/rescind/configuration/init.sls
srv/salt/ceph/rescind/default.sls
srv/salt/ceph/rescind/nop.sls

Rescind ceph.conf from minions without roles

---

srv/modules/runners/changed.py

fix backport error from 6423a7cbc95f970a70b0acd6c0d5157bd1362c02

---

srv/modules/runners/populate.py

runners/populate: don't create public_address proposals for mon/igw

---

srv/salt/_modules/cephprocesses.py

partly fixes #1080 
There is more to do for #1080 in the current release.
Details can be found in the issue.

Add missing role to cephprocesses map

---

srv/modules/runners/validate.py

Correct keyword and typo

---

srv/salt/ceph/apparmor/default-complain.sls
srv/salt/ceph/apparmor/default-disable.sls
srv/salt/ceph/apparmor/default-enforce.sls
srv/salt/ceph/apparmor/files/usr.sbin.httpd-prefork
srv/salt/ceph/apparmor/files/usr.sbin.oaconfig
srv/salt/ceph/apparmor/profiles.sls

Adds initial openATTIC AppArmor profiles
Signed-off-by: Laura Paduano lpaduano@suse.com

openATTIC AppArmor

---

srv/salt/ceph/macros/README.md
srv/salt/ceph/macros/os_switch.sls

This allows to either add, say a SUSE.sls or a more complex SUSE directory with several more complex sls files.

macros/os_switch: consider not only dirs but also files, add README

---

contributing.md

Add instructions for running the testsuite locally.

Add local test instructions

---

srv/modules/runners/populate.py

[backport][SES5] runners/populate: don't create public_address proposals for mon/igw

---

Makefile
deepsea.spec.in
srv/modules/runners/ready.py
srv/salt/ceph/apparmor/default-complain.sls
srv/salt/ceph/apparmor/default-disable.sls
srv/salt/ceph/apparmor/default-enforce.sls
srv/salt/ceph/apparmor/default.sls
srv/salt/ceph/apparmor/files/ceph.d/common
srv/salt/ceph/apparmor/files/usr.bin.ceph-mds
srv/salt/ceph/apparmor/files/usr.bin.ceph-mgr
srv/salt/ceph/apparmor/files/usr.bin.ceph-mon
srv/salt/ceph/apparmor/files/usr.bin.ceph-osd
srv/salt/ceph/apparmor/files/usr.bin.radosgw
srv/salt/ceph/apparmor/files/usr.sbin.httpd-prefork
srv/salt/ceph/apparmor/files/usr.sbin.oaconfig
srv/salt/ceph/apparmor/init.sls
srv/salt/ceph/apparmor/install/SUSE.sls
srv/salt/ceph/apparmor/install/default.sls
srv/salt/ceph/apparmor/install/init.sls
srv/salt/ceph/apparmor/profiles.sls
srv/salt/ceph/macros/README.md
srv/salt/ceph/macros/os_switch.sls
srv/salt/ceph/smoketests/apparmor/init.sls

[Backport][SES5] inital apparmor support

---

srv/salt/_modules/fs.py

Description:
Handle the concrete exceptions and uses exc_info=True in logging to capture the complete traceback

Fix bare excepts in fs module and log a complete traceback

---

qa/common/helper.sh

This fixes a fixme in 2 functions.

Use jq to process json instead of a chain of shell commands

---

Makefile
srv/modules/runners/cephprocesses.py
srv/modules/runners/cmd.py
srv/salt/_modules/cephprocesses.py
srv/salt/_modules/wait.py

fix lint issues

---

srv/salt/_modules/deepsea.py

Remove unnecessary variable name

---

Makefile

Fixes #
Fix four `make install` issues listed in description below.
Description:
**Issue 1:  copy-files stage failure**
See #1170
**Issue 2: python3 may be missing**
```
sed "s/DEVVERSION/"0.9.5+9.gadb3de7"/" setup.py.in > setup.py
#make sure to create bytecode with the correct version
find srv/ -name '*.py' -exec python3 -m py_compile {} \;
find: ‘python3’: No such file or directory
find: ‘python3’: No such file or directory
```
**Issue 3: /bin/sh is not bash (on Debian)**
```
/bin/sh: 1: source: not found
/bin/sh: 1: source: not found
```
**Issue 4: Failure on Debian family .. ...**
```
find cli/ -name '*.py' -exec python3 -m py_compile {} \;
python3-setuptools python3-click python3-tox
make: python3-setuptools: Command not found
make: *** [Makefile:836: install-deps] Error 127
``` …

Makefile fixes for Fedora/Centos/Debian/SLES

---

srv/modules/utils/ready.py

Make lint happy

---

srv/salt/ceph/restart/default.sls

Only restart with a running cluster

---

srv/modules/runners/validate.py
tests/unit/runners/test_validate.py

Fixes #723 
Description:
call `modprobe` in stage 4 (services) to check if rbd is available as a kernel module.

add 'rbd' kernel module validation

---

srv/modules/runners/benchmark.py

Description:
The following error occurs if an osd is removed and benchmark is run after that:
```
admin-server:/ # salt-run state.orch ceph.benchmarks.baseline
Running osd benchmarks..............[ERROR   ] Exception occurred in runner benchmark.baseline: Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 395, in _low
data['return'] = self.functions[fun](*args, **kwargs)
File "/srv/modules/runners/benchmark.py", line 284, in baseline
parsed_results = [ast.literal_eval(r[master_minion]) for r in results]
File "/usr/lib64/python2.7/ast.py", line 49, in literal_eval
node_or_string = parse(node_or_string, mode='eval')
File "/usr/lib64/python2.7/ast.py", line 37, in parse
return compile(source, filename, mode, PyCF_ONLY_AST)
File "<unknown>", …
```

FIX issue that would make benchmark.baseline fail if an osd is removed 

---

qa/common/common.sh
qa/common/deploy.sh
qa/common/helper.sh
qa/common/json.sh
qa/common/policy.sh
qa/common/zypper.sh
qa/suites/basic/health-ok.sh
qa/suites/basic/stage-5.sh

Fixes https://github.com/SUSE/DeepSea/issues/1237

qa: add script to test Stage 5 

---

.github/PULL_REQUEST_TEMPLATE.md

The current Pullrequest template is outdated. 

Add checklist to Pullrequest template

---

qa/common/common.sh

Fixes: https://github.com/SUSE/DeepSea/issues/1276
**Checklist:**
- ~~[ ] Added unittests and or functional tests~~
- ~~[ ] Adapted documentation~~

qa: run lsblk and ceph-disk on storage node only

---

srv/salt/_modules/wait.py

introduced in pr #1161
suse internal: 1104801
**Checklist:**

Fix wait.py duplications and wrong class invocation.

---

cli/.coveragerc
cli/monitors/terminal_outputter.py
cli/run-unit-tests.sh
cli/stage_parser.py
cli/tests/Dockerfile
cli/tests/helper.py
cli/tests/start.sh
cli/tests/test_monitor.py
cli/tests/test_stage_parse.py
tox.ini

Backport of https://github.com/SUSE/DeepSea/pull/1246

[backport][ses5] cli: filter out test.nop steps and don't report [init] step errors

---

srv/salt/_modules/cephdisks.py
srv/salt/_modules/osd.py
srv/salt/_modules/proposal.py
tests/unit/_modules/test_cephdisks.py
tests/unit/_modules/test_osd.py
tests/unit/_modules/test_proposal.py

Refactor device detection, allow override

---

srv/salt/_modules/cephdisks.py
srv/salt/_modules/osd.py
srv/salt/_modules/proposal.py
tests/unit/_modules/test_cephdisks.py
tests/unit/_modules/test_osd.py
tests/unit/_modules/test_proposal.py

(cherry picked from commit 165aea6fd01518d14fecc967bb8840c46eb20c7d)
backport of #1222 
**Checklist:**

[backport][ses5] Refactor device detection, allow override

---

srv/salt/_modules/osd.py
tests/unit/_modules/test_osd.py

(cherry picked from commit 3d3f47281a63080a722d4c4fff566de74bdfcc6e)
backport of #1259 
**Checklist:**

[backport][ses5] Do not create untracked partition

---

deepsea.spec.in

Fixes #1266 
**Checklist:**
(IMO almost none of the above items are necessary for this PR)

build: add python-six to RPM Requires

---

qa/common/deploy.sh
qa/common/rgw.sh

**Checklist:**
~~- [ ] Referenced issues or internal bugtracker~~

qa: common/deploy: run "zypper ps -s" on all nodes

---

srv/salt/_modules/wait.py
tests/unit/_modules/test_wait.py

Description:
Added an ad-hoc fix for wait.just in #1273 
This PR is delivering tests subsequently for the changed function. 
**Checklist:**

Add unittests for wait.just

---

srv/salt/_modules/cephinspector.py

[backport][SES5] cephinspector: use cephdisks.device in engulf (bsc#1082994)

---

man/deepsea-commands.7
srv/modules/runners/rescinded.py
srv/salt/_modules/osd.py
srv/salt/ceph/remove/storage/default.sls
srv/salt/ceph/remove/storage/drain/default.sls

[backport][SES5] Stage 5: delete CRUSH host buckets orphaned when storage node is deleted

---

.github/PULL_REQUEST_TEMPLATE.md

Add wiki to PULLREQUEST_TEMPLATE
**Checklist:**

Add wiki to PULLREQUEST_TEMPLATE

---

.github/PULL_REQUEST_TEMPLATE.md

Add pullrequest template with backporting info to SES5

---

Makefile

[SES5] Add make tarball to usage

---

srv/modules/runners/proposal.py

Fix an actually funny (maybe intended) typo.

---

srv/modules/runners/proposal.py

[backport][SES5] Fix an actually funny (maybe intended) typo.

---

srv/salt/ceph/tuned/mgr/default.sls
srv/salt/ceph/tuned/mon/default.sls
srv/salt/ceph/tuned/osd/default.sls

I don't know if this is really necessary, but it seems like a good practice to
follow.
**Checklist:**
~~- [ ] Referenced issues or internal bugtracker~~

tuned: make stanza names unique

---

srv/salt/ceph/monitoring/grafana/files/node.json

Thx to @evnu for the math assist.
**Checklist:**

monitoring: fix fs fillup time query

---

cli/deepsea.py
cli/monitor.py
cli/stage_parser.py
cli/tests/test_stage_parse.py

(cherry picked from commit f735e7764ff7b0a5340ad18778cf6b9a09689b1e)
forwardport of #1353 

[forwardport][master] cli: support list of sls ids in salt.state orch function

---

srv/modules/runners/remove.py
srv/modules/runners/replace.py

backport of #1359 
**Checklist:**

[backport][SES5] remove/replace interference fixes

---

CHANGELOG

Move changelog from buildservice back to the repository.

Changelog for 0.8.6 release

---

man/deepsea-commands.7

Missing closing quotes in deepsea-commands.7

man: missing closing quotes

---

srv/modules/runners/populate.py

Remove error condition, empty cluster network is valid

---

Makefile

Signed-off-by: Shyukri Shyukriev <shshyukriev@suse.com>
Fixes #1285
Description:
Try the way provided in the issue description.
**Checklist:**

Install salt-api requirement prior to building the package.

---

srv/salt/ceph/igw/config/default.sls

Specify only supported image feature: layering

---

qa/common/deploy.sh

Once this PR is merged, the CI will be able to grep the log for the string "deploy phase complete!"

[SES5] qa: always report completion of deploy phase

---

Makefile
deepsea.spec.in
srv/modules/runners/populate.py
srv/salt/_modules/cephinspector.py
srv/salt/_modules/functest.py
srv/salt/ceph/functests/1node/engulf/init.sls
srv/salt/ceph/functests/1node/init.sls
srv/salt/ceph/tests/engulf/pillar-save.sls
srv/salt/ceph/tests/engulf/pillar-verify.sls
srv/salt/ceph/tests/engulf/profile-verify.sls
srv/salt/ceph/tests/engulf/proposal-backup.sls
srv/salt/ceph/tests/engulf/proposal-restore.sls

Fixes: #1183, and a couple of other things. Probably shouldn't merge this until I've written some tests and added them to this PR.
Note that we also need https://github.com/SUSE/ceph/pull/207 for this to operate correctly with python3.
**Checklist:**

Fix Engulf on Master

---

qa/common/deploy.sh

Fixes #
https://openqa.suse.de/tests/2139403#step/deepsea_testsuite/29

Use FQDN hostname also for MASTER_MINION

---

Makefile
deepsea.spec.in
srv/modules/runners/populate.py
srv/salt/_modules/functest.py
srv/salt/ceph/functests/1node/engulf/init.sls
srv/salt/ceph/functests/1node/init.sls
srv/salt/ceph/tests/engulf/pillar-save.sls
srv/salt/ceph/tests/engulf/pillar-verify.sls
srv/salt/ceph/tests/engulf/profile-verify.sls
srv/salt/ceph/tests/engulf/proposal-backup.sls
srv/salt/ceph/tests/engulf/proposal-restore.sls

These are the pieces of #1387 which make sense to backport to SES5.
ref: #bsc1108495

[SES5] Make engulf a bit more user friendly

---

srv/modules/runners/push.py

backport of #1400 
**Checklist:**

[backport][SES5] Remove journal_size, if present

---

cli/common.py

cli: prettyprint: force stdout flush in all stdout writes

---

cli/common.py

Fixes: #1434
(cherry picked from commit 6adb0081b753cef22d99d7503cef16d8f6535b3d)
backport of #1435 
**Checklist:**

[backport][ses5] cli: prettyprint: force stdout flush in all stdout writes

---

srv/modules/runners/validate.py

(cherry picked from commit 28fac45468c936ee2b1b9290865497a8f4c5a323)
backport of #1375 
**Checklist:**

[backport][SES5] Prevent rgw-ssl name collision when pushing certificates and

---

srv/salt/ceph/monitoring/grafana/files/ceph-pools.json

monitoring: fix pool usage gauge

---

CHANGELOG

supplementing the changelog with an old bsc ref

[SES5]Add missing bsc bug to v0.8.4 release notes

---

srv/salt/_modules/osd.py

On real hardware we use by-id paths. Resolve those paths to short device names.

ceph-volume dummy: translate by-id device paths to short device paths

---

srv/salt/_modules/osd.py
tests/unit/_modules/test_osd.py

Add retry logic to readlink for seemingly stubborn systems

---

srv/salt/_modules/osd.py
tests/unit/_modules/test_osd.py

Save and restore reweight in addition to weight

---

srv/salt/ceph/packages/common/default.sls

Fixes #
Description:
**Checklist:**

packages/common: Fix typo "realease"

---

Makefile

[backport] Makefile: pass --long option to git describe

---

srv/salt/ceph/ganesha/install/default.sls

Fixes: https://github.com/SUSE/DeepSea/issues/1536

install_ganesha: failhard

---

srv/salt/ceph/restart/grafana/default.sls
srv/salt/ceph/restart/prometheus/default.sls

monitoring: restarts, avoid "matched no target"

---

srv/modules/runners/populate.py

populate should overwrite the stack/default tree at all times

---

Makefile
deepsea.spec.in
srv/salt/ceph/mgr/dashboard/default.sls
srv/salt/ceph/mgr/dashboard/init.sls
srv/salt/ceph/mgr/default.sls
srv/salt/ceph/rescind/mgr/dashboard/default.sls
srv/salt/ceph/rescind/mgr/dashboard/init.sls
srv/salt/ceph/rescind/mgr/default.sls

bsc: 1127770
Fixes: #1550 
**Checklist:**

Install the ceph-mgr-dashboard on mgr nodes

---

Makefile
srv/modules/runners/net.py
srv/salt/_modules/multi.py
srv/salt/ceph/functests/1node/init.sls
srv/salt/ceph/functests/1node/multi/init.sls
srv/salt/ceph/tests/iperf3/init.sls
tests/unit/_modules/test_multi.py

Kill iperf3 processes when complete

---

srv/salt/ceph/mgr/default.sls
srv/salt/ceph/mon/default.sls
srv/salt/ceph/stage/deploy/default.sls

[SES5] Stage 3: fail immediately if MONs or MGRs do not stay up after starting

---

Makefile
deepsea.spec.in
srv/salt/ceph/configuration/files/drive_groups.yml

A convenience directory to easily access necessary files.
**Checklist:**

Add central /etc/deepsea config directory.

---

srv/salt/ceph/monitoring/prometheus/populate_mgr_scrape_configs.sls

prometheus: fix populate_mgr_scrape_configs states to work with deepsea-cli

---

cli/stage_parser.py

cli: fix stdout/stderr redirection for python 2

---

srv/modules/runners/populate.py

Fixes #
Description:
**Checklist:**

populate runner: fix typo "cepg"

---

cli/stage_parser.py

(cherry picked from commit 3ff26802ab644a0d9b7ab6d0cce2b697a8c6ed52)

[backport] [SES5] cli: fix stdout/stderr redirection for python 2

---

cli/monitor.py

cli: fix function args string formating

---

cli/monitors/terminal_outputter.py

Fixes the stack trace shown in this comment:
https://github.com/SUSE/DeepSea/pull/1516#issuecomment-465795371

cli: fix simple outputter when printing stage exception

---

cli/stage_parser.py

cli: handles render failure when minion does not respond

---

srv/salt/_modules/keyring.py
srv/salt/ceph/ganesha/auth/default.sls
srv/salt/ceph/ganesha/config/default.sls
srv/salt/ceph/ganesha/files/ganesha.conf.j2
srv/salt/ceph/ganesha/key/default.sls
srv/salt/ceph/ganesha/keyring/default.sls
srv/salt/ceph/ganesha/rados_config.sls
srv/salt/ceph/ganesha/service/default.sls
srv/salt/ceph/rgw/dashboard.sls
srv/salt/ceph/stage/ganesha/core/default.sls
srv/salt/ceph/stage/radosgw/core/default.sls

This PR changes the deployment of nfs-ganesha to match the requirements of ceph-dashboard.

nfs-ganesha: deploy ganesha configuration in RADOS pool

---

srv/salt/ceph/ganesha/rados_config.sls
srv/salt/ceph/stage/ganesha/core/default.sls

ganesha: find pool during stage execution (instead of in parsing phase)

---

srv/modules/runners/net.py
srv/modules/runners/populate.py
srv/modules/runners/validate.py
srv/salt/_modules/public.py
srv/salt/ceph/configuration/files/rgw-ssl.conf
srv/salt/ceph/configuration/files/rgw.conf
tests/unit/_modules/test_public.py
tests/unit/runners/test_populate.py
tests/unit/runners/test_validate.py

This reverts commit 7fc208925ad4ba95117ac06dea6ad6c6ddcf6f6a.
jira: SES-119
**Checklist:**

Support IPv6

---

cli/deepsea.py

cli: fix print of target name in stage dry-run

---

srv/salt/ceph/monitoring/prometheus/exporters/files/smartmon.sh

(cherry picked from commit ae5a505f1e8ad6f41c5c66bceded275e3ef627fa)
Forward port of #1556

monitoring: update smartmon.sh, fix label dimension inconsistency

---

srv/salt/ceph/monitoring/prometheus/exporters/files/smartmon.sh

[SES5] monitoring: update smartmon.sh, fix label dimension inconsistency

---

srv/modules/runners/net.py
tests/unit/runners/test_net.py
tox.ini

Correctly parse multiple networks

---

srv/modules/runners/ui_iscsi.py

Fixes: bsc#1130223
**Checklist:**

[SES5] ui_iscsi: restart iSCSI gateways sequentially

---

srv/modules/runners/disks.py

disks runner: guard destroyed() against roles:master being absent

---

srv/salt/ceph/dashboard/default.sls

dashboard: support for enabling/disabling SSL and set certificates

---

srv/modules/runners/push.py
tests/unit/runners/test_push.py

[SES5] Correct variable name

---

srv/salt/_modules/dg.py
tests/unit/_modules/test_dg.py

dg: use re.search instead of re.match

---

srv/salt/_modules/dg.py
tests/unit/_modules/test_dg.py

core: add filestore support for dg.py

---

srv/salt/_modules/dg.py
tests/unit/_modules/test_dg.py

core: add wal/db size flag, enable limit: for wal/db devices

---

Makefile
deepsea.spec.in
srv/salt/ceph/monitoring/alertmanager/files/alertmanager.sysconfig.j2
srv/salt/ceph/monitoring/default.sls
srv/salt/ceph/monitoring/disabled.sls
srv/salt/ceph/monitoring/init.sls
srv/salt/ceph/monitoring/prometheus/default.sls
srv/salt/ceph/monitoring/prometheus/files/prometheus.yml.j2
srv/salt/ceph/stage/deploy/monitoring.sls

Forgot a few things.
Fixes bsc#1134467

Some fixes for new monitoring deployment

---

Makefile
srv/modules/runners/rebuild.py
srv/salt/ceph/functests/1node/init.sls
srv/salt/ceph/functests/1node/rebuild/init.sls

rebuild: add functest, fix help message

---

srv/salt/_modules/dg.py
tests/unit/_modules/test_dg.py

* Work around c-v's issue described here: http://tracker.ceph.com/issues/37502
We now create separate calls for each wal/db.
Bonus:
* Improve access time of disks(dg).c_v_commands (and successive .deploy) by 30%
by reducing the amount of dynamic data/db/wal_devices invocations.
* Add log.debug statements in _filter_devices
* Add mechanism to prevent the listing of the same devices under different
columns (wal/db/data).
This is achieved by tracking the assigned devices internally.
This also reduces the amount of checks we have to perform
Testing:
* Re-work 'inventory' generation by implementing a InventoryFactory.
* Added tests for c_v_commands
~depended on #1635 (hence https://github.com/SUSE/DeepSea/commit/611d6d98742811450f9d1f3de839a3929a993ef5)~ merged
**Checklist:** …

core: workaround ceph-volume's wal/db VG spanning issue

---

srv/modules/runners/disks.py

typo: s/to to/to

---

srv/modules/runners/disks.py
srv/salt/_modules/osd.py

This is a utility function for the profile->drivegroup migration.
**Checklist:**

osd: add independent osd discovery method

---

srv/salt/_modules/iscsi.py
srv/salt/ceph/igw/files/iscsi-gateway.cfg.j2
srv/salt/ceph/packages/common/default.sls

iscsi: use FQDN in gateways hostnames

---

srv/salt/ceph/stage/deploy/monitoring.sls

monitoring: manage salt's fileserver cache in monitoring deployment

---

srv/salt/_modules/osd.py

osd: do not assign value to property

---

deepsea.spec.in

build: revert dependencies from deepsea.spec.in

---

srv/salt/ceph/monitoring/prometheus/files/prometheus.yml.j2

monitoring: iterate over pillar yaml to generate prometheus yaml

---

srv/modules/runners/disks.py

discovery: do not format if salt returned an error

---

srv/salt/_modules/dg.py
srv/salt/ceph/configuration/files/drive_groups.yml

The drivegroups wiki also needs to be adjusted accordingly.
edit: it *was* already adapted, see https://github.com/SUSE/DeepSea/wiki/Drive-Groups

fix two documentation issues

---

srv/salt/_modules/osd.py
tests/unit/_modules/test_osd.py

bnc#1133826
bnc#1134723
**Checklist:**

Improve removal with missing disk

---

srv/salt/ceph/restart/mds/default.sls

restarts: if no fs is present, restart mds without coordination

---

Makefile
deepsea.spec.in

Include missing README

---

srv/modules/runners/upgrade.py

Fixes bsc#1135913
bonus: whitespaces and pep8 compliance

disable the automated upgrade

---

srv/salt/_modules/subvolume.py
srv/salt/ceph/subvolume/default.sls
tests/unit/_modules/test_subvolume.py

Fix subvolume mount for generic device or label

---

srv/salt/_modules/dg.py
srv/salt/ceph/configuration/files/drive_groups.yml
tests/unit/_modules/test_dg.py

drivegroups: allow lower case sizing units

---

srv/modules/runners/remove.py

Remove the OSD entry from Ceph regardless of the results from the minion

---

srv/modules/runners/osd.py
srv/modules/runners/rebuild.py
srv/salt/_modules/osd.py
tests/unit/runners/test_osd.py
tests/unit/runners/test_rebuild.py

Evacutate OSDs simultaneously when removing OSDs

---

srv/modules/runners/ui_iscsi.py

[SES5] iscsi: stop restart sequence when one iscsi gw fails to restart

---

Makefile

Fixes #
- Adds Archlinux Support
-  Fix package handling (for archlinux)
-  Few minor fixes and improvementt
Description:
*make install* tested on Ubuntu, CentOS, OpenSUSE 15, Archlinux
**Checklist:**
- [ x] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

feat(makefile): archlinux support & minor updates

---

Makefile
deepsea.spec.in
srv/modules/runners/bootstrap.py
srv/modules/runners/ceph.py
srv/modules/runners/config.py
srv/modules/runners/ext_lib/hash_dir.py
srv/modules/runners/ext_lib/utils.py
srv/modules/runners/mgr.py
srv/modules/runners/mon.py
srv/pillar/ceph/init.sls
srv/pillar/ceph/internal.yml
srv/salt/_modules/podman.py
srv/salt/ceph/configuration/files/ceph.conf.j2
srv/salt/ceph/permissions/default.sls
srv/salt/ceph/permissions/init.sls

* added feature to add mons and mgrs (no bootstrap)
CAVEAT:
The issue with podman not behaving properly when run on a minion *not* in debug mode persists.
NOTE: 
It seems to be fine to run the minions in `daemon` mode
`salt-minion -d`
to resolve the issue mentioned in the previous PR
**Checklist:**

[next] refactor bootstrap, mon and mgr code

---

srv/salt/_modules/purge.py
tests/unit/_modules/test_purge.py

[SES5] Remove igw_config setting during purge

---

README.md

This is a first draft for a new README.
I also removed some statements that are no longer true.
Comments and suggestions are most welcome
**Checklist:**

[next] draft for new readme

---

srv/salt/ceph/stage/removal/default.sls

Can be considered a backport of #1753

stage 5: actually call remove.mds in stage 5

---

srv/modules/runners/ganesha.py
srv/salt/_modules/ganesha.py

This PR adds a function to the ganesha runner to output the information about the current nfs-ganesha gateways and their configuration.

ganesha: report runner to give support info about nfs-ganesha

---

srv/modules/runners/ganesha_upgrade.py
srv/salt/_modules/ganesha.py

Fixes: bsc#1148405
Description:
**Checklist:**

ganesha: don't run the upgrade on fresh nodes

---

srv/salt/_states/deepsea.py
srv/salt/ceph/igw/restart/controlled/default.sls

iscsi: fix iscsi restart before upgrade to ceph-iscsi

---

srv/modules/runners/ganesha.py
srv/salt/_modules/ganesha.py

(cherry picked from commit 45ee069b41a102e1e0935cdaaf4f0e9172957582)

[SES6] ganesha: report runner to give support info about nfs-ganesha

---

srv/salt/_states/deepsea.py
srv/salt/ceph/igw/restart/controlled/default.sls

Fixes: bsc#1136066
(cherry picked from commit 9fe0d1107a9ba27d05c1bdc76d2df446d1c634b5)

[SES6] iscsi: fix iscsi restart before upgrade to ceph-iscsi

---

srv/modules/runners/validate.py
srv/salt/_modules/deepsea.py

stage 0: don't show failure in CLI when checking for missing packages

---

srv/modules/runners/net.py

Signed-off-by: Alex Lau (AvengerMoJo) <alau@suse.com>
(cherry picked from commit 185d7ac3312db2c1b65b6f8728b64695f2e5dbc9)
Fixes #
backport of #1742
Description:
When net.ping with node get mulitple ip, "exclude" option will take out the minion completely with all the interfaces ip, only ip can be left to filter. So adding the "remove" option is to allow exclude actually take out specific subnet ip instead of the minion completely.
**Checklist:**
- [*] Adapted documentation
command and code are doc accordingly

[backport][SES6] Add remove option to the ping to remove multiple ip interface

---

srv/modules/runners/ganesha_upgrade.py
srv/salt/_modules/ganesha.py

[SES6] ganesha: don't run the upgrade on fresh nodes

---

srv/modules/runners/net.py

Signed-off-by: Alex Lau (AvengerMoJo) <alau@suse.com>
Fixes #
Exclude doesn't work the way it should when multiple ip apply to a single node. 
Description:
When net.ping with node get mulitple ip, "exclude" option will take out the minion completely with all the interfaces ip, only ip can be left to filter. So adding the "remove" option is to allow exclude actually take out specific subnet ip instead of the minion completely. 
**Checklist:**
it is more a runner that help reporting the network environment that didn't mean to be called by external. Didn't design a unittest for this. 
- [*] Adapted documentation
command and code are doc accordingly
no offical bug reported yet, it is more like an enhancement for the ping filter 
Not related to the stage of deployment but …

Add remove option to the ping to remove multiple ip interface

---

srv/modules/runners/validate.py
srv/salt/_modules/deepsea.py

Fixes: bsc#1137973
(cherry picked from commit 3246d4e1aeb9cc61a8c68478f9c1b70dd2f20829)

[SES6] stage 0: don't show failure in CLI when checking for missing packages

---

srv/salt/ceph/configuration/files/ceph.conf.j2
srv/salt/ceph/ganesha/keyring/default.sls

ganesha: update ceph.conf in stage 3 instead of 4

---

srv/modules/runners/changed.py
srv/modules/runners/select.py
srv/salt/_modules/iscsi.py
srv/salt/ceph/igw/config/apply_iscsi_config.sls
srv/salt/ceph/igw/config/create_iscsi_config.sls
srv/salt/ceph/igw/files/iscsi-gateway.cfg.j2
srv/salt/ceph/stage/deploy/core/default.sls
srv/salt/ceph/stage/iscsi/core/default.sls
srv/salt/ceph/stage/iscsi/dashboard.sls
srv/salt/ceph/stage/iscsi/default.sls
tests/unit/runners/test_changed.py

Fixes: bsc#1134536
(cherry picked from commit 99488dff9efb113d614d781031efe977b88ed01d)

[backport][SES6] iscsi: SSL enabled deployment by default

---

deepsea.spec.in
srv/modules/runners/status.py
srv/modules/runners/upgrade.py
srv/modules/utils/status.py

[backport][SES6] Add status function to advise on upgrade order

---

srv/salt/_modules/iscsi.py

Fixes:
bsc#1145617 - TPG auth settings lost during upgrade
bsc#1145618 - TPG LUN id lost during upgrade
Description:
I've only tested these changes manually so far. For full coverage I'm working on a rapido based VM which steps through lrbd->ceph-iscsi upgrades for most existing lrbd sample configs.
**Checklist:**
- [ x] Referenced issues or internal bugtracker

lrbd to ceph-iscsi upgrade fixes

---

srv/salt/_modules/iscsi.py

Backport of PR #1731 
Fixes 
bsc#1145617 - TPG auth settings lost during upgrade
bsc#1145618 - TPG LUN id lost during upgrade

[SES6] lrbd to ceph-iscsi upgrade fixes

---

srv/salt/ceph/configuration/files/ceph.conf.j2
srv/salt/ceph/ganesha/keyring/default.sls

Fixes: bsc#1150643
(cherry picked from commit b42b054fb17378429b2177a5ae27bd6e72baf279)

[SES6] ganesha: update ceph.conf in stage 3 instead of 4

---

cli/monitors/terminal_outputter.py

[SES5] cli: fix simple outputter when printing stage exception

---

srv/modules/runners/osd.py
srv/modules/runners/rebuild.py
srv/salt/_modules/osd.py
tests/unit/runners/test_osd.py
tests/unit/runners/test_rebuild.py

[SES6] Remove recursion, add custom retries

---

srv/salt/_modules/cephdisks.py
srv/salt/_modules/dg.py

Fixes #
Description: Backport commit from PR #1723 to `SES6` branch in order to fix the bug regarding filestore parsing.
**Checklist:**

Added data tag in cephdisks/dg for filestore OSDs

---

Makefile
etc/salt/master.d/logging.conf
srv/modules/runners/disks.py
srv/modules/runners/osd.py
srv/modules/utils/tee.py
tests/unit/runners/test_osd.py
tox.ini

Forward port: #1795
**Checklist:**

Wip split output master

---

srv/salt/ceph/remove/cephfs/default.sls

Allow for graceful rerunning when removing the cephfs configuration

---

doc/examples/policy.cfg-full

Description:
Add a full example with all roles that currently exist.
**Checklist:**

ADD doc/examples/policy.cfg-full: full example using all roles

---

srv/modules/runners/validate.py

Warn users of unresolved addresses

---

srv/salt/ceph/dashboard/default.sls

Allow custom grafana endpoint

---

srv/salt/_modules/cephdisks.py
tests/unit/_modules/test_cephdisks.py

backport of #1810 
**Checklist:**

[ses6][backport]: cephdisks: exclude disks that are assigned for raid configurations

---

srv/modules/runners/upgrade.py
srv/salt/_modules/osd.py

Add upgrade check for `straw` algorithm

---

srv/salt/_modules/iscsi.py

Backport of https://github.com/SUSE/DeepSea/pull/1821

[ses6][backport] Fix iSCSI default values

---

srv/salt/_modules/iscsi.py

Do not rely on isinstance

---

srv/salt/ceph/stage/configure/disabled.sls
srv/salt/ceph/stage/deploy/disabled.sls
srv/salt/ceph/stage/discovery/disabled.sls
srv/salt/ceph/stage/prep/disabled.sls
srv/salt/ceph/stage/removal/disabled.sls
srv/salt/ceph/stage/services/disabled.sls

Create disabled files to simplify removal instructions

---

srv/modules/runners/net.py

Skip invalid values and log error.
bnc: 1164869
**Checklist:**

Validate iperf results from modules

---

srv/modules/runners/validate.py
tests/unit/runners/test_validate.py

Correct spelling typo

---

srv/salt/ceph/rescind/tuned/default.sls

Only remove tuned when a minion has no roles

---

Makefile
deepsea.spec.in
srv/salt/_modules/keyring.py
srv/salt/ceph/crash/auth/default.sls
srv/salt/ceph/crash/auth/init.sls
srv/salt/ceph/crash/default.sls
srv/salt/ceph/crash/files/keyring.j2
srv/salt/ceph/crash/init.sls
srv/salt/ceph/crash/key/default.sls
srv/salt/ceph/crash/key/init.sls
srv/salt/ceph/rescind/crash/default.sls
srv/salt/ceph/rescind/crash/init.sls
srv/salt/ceph/rescind/default.sls
srv/salt/ceph/stage/configure/default.sls
srv/salt/ceph/stage/deploy/core/default.sls

Create and distribute keyring for ceph-crash

---

srv/salt/_modules/cephdisks.py
srv/salt/_modules/dg.py
tests/unit/_modules/test_cephdisks.py
tests/unit/_modules/test_dg.py

This is needed for the latest version of ceph
**Checklist:**

lvm batch refactor adaption

---

srv/salt/ceph/ganesha/rados_config.sls

Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1178016
**Checklist:**

Correct pool for condition

---

srv/modules/runners/upgrade.py
tests/unit/runners/test_upgrade.py

Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1181665
Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>
Description:
**Checklist:**

upgrade to cephadm: fix Drive Group generation

---

srv/modules/runners/osd.py

This parses the c-v simple scan result in /etc/ceph/osd to retrieve the
devices the osd.$i uses and then passes them to c-v lvm zap. The zap
subcommand will zap devices no problem, the trick is really just to
figure out which devices to zap.
Fixes bsc#1178657
Description:
**Checklist:**

osd: add method to zap simple osds

---

srv/modules/runners/osd.py

Prior to https://github.com/ceph/ceph/commit/a45bfebb, the `ceph osd ok-to-stop` command output a long, human readable
string.  DeepSea was looking at this string to see if OSDs really were OK to stop.  Since that commit, the output of this command is now a chunk of JSON, which obviously can't work with that string comparison, so let's try to parse the JSON first, in case we're using the latest Nautilus release, and if that fails, fall back to the previous check in case we're still running against an older Ceph.

osd: handle `ceph osd ok-to-stop` output from ceph v14.2.22

---

srv/salt/_modules/osd.py

When restarting OSDs, we wait for them to become available before proceeding to the next OSD.  Previosly, this wait was in a loop with a timeout of 60 seconds.  This commit increases the default timeout to 120 seconds, and also makes it configurable in case that's still too short in some circumstances.  If you need a different timeout, specify it in `/srv/pillar/ceph/stack/global.yml`, e.g.:
```
osd_available_timeout: 240
```
Note that the way the loop is implemented, the sleep in the loop doubles on each iteration.  The runtime of the loop will thus be pretty close to a power of 2, e.g.: 1, 2, 4, 8, 16, 32, 64, ... seconds.  It won't stop when the exact timeout is reached, rather
it will stop at approximately the next power of 2 seconds greater than the specified timeout.
Fixes: …

Bump OSD available timeout to 120, make it configurable (bsc#1192520)

---

srv/modules/runners/osd.py
tests/unit/runners/test_osd.py

Doing this to zap the partition table, as there are issues deploying
OSDs with GPT partition tables after rebuilding the nodes.
Signed-off-by: Xavi Garcia <xavi.garcia@suse.com>
Fixes https://bugzilla.suse.com/show_bug.cgi?id=1194807
There is a problem when zapping partitions that are part of a disk with GPT partition table.
Deepsea is zapping the partition but not the whole disk, so the partition table remains and doesn't allow the later deployment of the OSD in SES6.
This is mainly happening for clusters upgraded from SES5, with non-lvm disks.

Zap disks in rebuild.node when there are no partitions
